OpenMAXBellagio: omxaudiomixertest.h File Reference
components_symbian/symbianaudiomixer/inc/omxaudiomixertest.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <string.h>
#include <pthread.h>
#include <unistd.h>
#include <sys/stat.h>
#include <OMX_Core.h>
#include <OMX_Component.h>
#include <OMX_Types.h>
#include <OMX_Audio.h>
#include <tsemaphore.h>
#include <user_debug_levels.h>
Data Structures
struct appPrivateType
Macros
#define VERSIONMAJOR 1
#define VERSIONMINOR 1
#define VERSIONREVISION 0
#define VERSIONSTEP 0
#define BUFFER_IN_SIZE 16384
Typedefs
typedef struct appPrivateType appPrivateType
Functions
OMX_ERRORTYPE audiomixerEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_IN OMX_PTR pEventData)
OMX_ERRORTYPE audiomixerEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
OMX_ERRORTYPE audiomixerFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
OMX_ERRORTYPE audiosinkEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
OMX_ERRORTYPE audiosinkEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
Macro Definition Documentation
#define BUFFER_IN_SIZE 16384
Definition at line 70 of file components_symbian/symbianaudiomixer/inc/omxaudiomixertest.h.
#define VERSIONMAJOR 1
Specification version
Definition at line 51 of file components_symbian/symbianaudiomixer/inc/omxaudiomixertest.h.
#define VERSIONMINOR 1
Definition at line 52 of file components_symbian/symbianaudiomixer/inc/omxaudiomixertest.h.
#define VERSIONREVISION 0
Definition at line 53 of file components_symbian/symbianaudiomixer/inc/omxaudiomixertest.h.
#define VERSIONSTEP 0
Definition at line 54 of file components_symbian/symbianaudiomixer/inc/omxaudiomixertest.h.
Typedef Documentation
typedef struct appPrivateType appPrivateType
Function Documentation
OMX_ERRORTYPE audiomixerEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
Definition at line 658 of file audio_effects/omxaudiomixertest.c.
References DEB_LEV_FULL_SEQ, DEB_LEV_SIMPLE_SEQ, DEBUG, appPrivateType::eofSem, err, fd, fd1, filesize, filesize1, FRAME_SIZE, OMX_BUFFERFLAG_EOS, OMX_EmptyThisBuffer, OMX_ErrorNone, OMX_FALSE, OMX_TRUE, and tsem_up().
Referenced by main().
OMX_ERRORTYPE audiomixerEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_IN OMX_PTR pEventData)
Definition at line 608 of file audio_effects/omxaudiomixertest.c.
References DEB_LEV_SIMPLE_SEQ, DEBUG, appPrivateType::eofSem, appPrivateType::eventSem, OMX_BUFFERFLAG_EOS, OMX_CommandPortDisable, OMX_CommandPortEnable, OMX_CommandStateSet, OMX_ErrorNone, OMX_EventBufferFlag, OMX_EventCmdComplete, OMX_StateExecuting, OMX_StateIdle, OMX_StateInvalid, OMX_StateLoaded, OMX_StatePause, OMX_StateWaitForResources, and tsem_up().
Referenced by main().
OMX_ERRORTYPE audiomixerFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
Definition at line 739 of file audio_effects/omxaudiomixertest.c.
References appPrivateType::audiosinkhandle, DEB_LEV_ERR, DEB_LEV_FULL_SEQ, DEBUG, err, flagPlaybackOn, OMX_BUFFERHEADERTYPE::nFilledLen, OMX_EmptyThisBuffer, OMX_ErrorNone, OMX_FillThisBuffer, and OMX_BUFFERHEADERTYPE::pBuffer.
Referenced by main().
OMX_ERRORTYPE audiosinkEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
Definition at line 1742 of file audio_use_case.c.
OMX_ERRORTYPE audiosinkEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
Callbacks implementation of the audio source component
Definition at line 1687 of file audio_use_case.c.
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1