OpenMAXBellagio: jcapimin.c File Reference
jcapimin.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Macros
#define JPEG_INTERNALS
Functions
void jpeg_CreateCompress (j_compress_ptr cinfo, int version, size_t structsize)
void jpeg_destroy_compress (j_compress_ptr cinfo)
void jpeg_abort_compress (j_compress_ptr cinfo)
void jpeg_suppress_tables (j_compress_ptr cinfo, boolean suppress)
void jpeg_finish_compress (j_compress_ptr cinfo)
void jpeg_write_marker (j_compress_ptr cinfo, int marker, const JOCTET *dataptr, unsigned int datalen)
void jpeg_write_m_header (j_compress_ptr cinfo, int marker, unsigned int datalen)
void jpeg_write_m_byte (j_compress_ptr cinfo, int val)
void jpeg_write_tables (j_compress_ptr cinfo)
Macro Definition Documentation
#define JPEG_INTERNALS
Definition at line 19 of file jcapimin.c.
Function Documentation
void jpeg_abort_compress (j_compress_ptr cinfo)
Definition at line 102 of file jcapimin.c.
References jpeg_abort().
void jpeg_CreateCompress (j_compress_ptr cinfo, int version, size_t structsize)
Definition at line 30 of file jcapimin.c.
References CSTATE_START, err, ERREXIT2, FALSE, jpeg_common_struct::global_state, jpeg_error_mgr::i, JERR_BAD_LIB_VERSION, JERR_BAD_STRUCT_SIZE, jinit_memory_mgr(), JPEG_LIB_VERSION, MEMZERO, NUM_HUFF_TBLS, NUM_QUANT_TBLS, jpeg_common_struct::progress, and SIZEOF.
void jpeg_destroy_compress (j_compress_ptr cinfo)
Definition at line 90 of file jcapimin.c.
References jpeg_destroy().
Referenced by main(), and omx_jpegenc_component_BufferMgmtFunction().
void jpeg_finish_compress (j_compress_ptr cinfo)
Definition at line 149 of file jcapimin.c.
References CSTATE_RAW_OK, CSTATE_SCANNING, CSTATE_WRCOEFS, ERREXIT, ERREXIT1, JERR_BAD_STATE, JERR_CANT_SUSPEND, JERR_TOO_LITTLE_DATA, and jpeg_abort().
Referenced by main(), and omx_jpegenc_component_BufferMgmtFunction().
void jpeg_suppress_tables (j_compress_ptr cinfo, boolean suppress)
Definition at line 121 of file jcapimin.c.
References jpeg_error_mgr::i, NUM_HUFF_TBLS, NUM_QUANT_TBLS, JQUANT_TBL::sent_table, and JHUFF_TBL::sent_table.
Referenced by jpeg_start_compress(), and jpeg_write_coefficients().
void jpeg_write_m_byte (j_compress_ptr cinfo, int val)
Definition at line 228 of file jcapimin.c.
Referenced by jcopy_markers_execute().
void jpeg_write_m_header (j_compress_ptr cinfo, int marker, unsigned int datalen)
Definition at line 216 of file jcapimin.c.
References CSTATE_RAW_OK, CSTATE_SCANNING, CSTATE_WRCOEFS, ERREXIT1, and JERR_BAD_STATE.
Referenced by jcopy_markers_execute().
void jpeg_write_marker (j_compress_ptr cinfo, int marker, const JOCTET * dataptr, unsigned int datalen)
Definition at line 194 of file jcapimin.c.
References CSTATE_RAW_OK, CSTATE_SCANNING, CSTATE_WRCOEFS, ERREXIT1, info, JERR_BAD_STATE, and JMETHOD.
Referenced by jcopy_markers_execute().
void jpeg_write_tables (j_compress_ptr cinfo)
Definition at line 256 of file jcapimin.c.
References CSTATE_START, ERREXIT1, JERR_BAD_STATE, and jinit_marker_writer().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1