OpenMAXBellagio: jcapistd.c File Reference
jcapistd.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Macros
#define JPEG_INTERNALS
Functions
void jpeg_start_compress (j_compress_ptr cinfo, boolean write_all_tables)
JDIMENSION jpeg_write_scanlines (j_compress_ptr cinfo, JSAMPARRAY scanlines, JDIMENSION num_lines)
JDIMENSION jpeg_write_raw_data (j_compress_ptr cinfo, JSAMPIMAGE data, JDIMENSION num_lines)
Macro Definition Documentation
#define JPEG_INTERNALS
Definition at line 17 of file jcapistd.c.
Function Documentation
void jpeg_start_compress (j_compress_ptr cinfo, boolean write_all_tables)
Definition at line 38 of file jcapistd.c.
References CSTATE_RAW_OK, CSTATE_SCANNING, CSTATE_START, ERREXIT1, FALSE, JERR_BAD_STATE, jinit_compress_master(), and jpeg_suppress_tables().
Referenced by main(), and omx_jpegenc_component_BufferMgmtFunction().
JDIMENSION jpeg_write_raw_data (j_compress_ptr cinfo, JSAMPIMAGE data, JDIMENSION num_lines)
Definition at line 120 of file jcapistd.c.
References CSTATE_RAW_OK, DCTSIZE, ERREXIT, ERREXIT1, JERR_BAD_STATE, JERR_BUFFER_SIZE, JWRN_TOO_MUCH_DATA, and WARNMS.
JDIMENSION jpeg_write_scanlines (j_compress_ptr cinfo, JSAMPARRAY scanlines, JDIMENSION num_lines)
Definition at line 77 of file jcapistd.c.
References CSTATE_SCANNING, ERREXIT1, JERR_BAD_STATE, JWRN_TOO_MUCH_DATA, and WARNMS.
Referenced by main(), and omx_jpegenc_component_BufferMgmtFunction().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1