OpenMAXBellagio: jcomapi.c File Reference
jcomapi.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Macros
#define JPEG_INTERNALS
Functions
void jpeg_abort (j_common_ptr cinfo)
void jpeg_destroy (j_common_ptr cinfo)
JQUANT_TBL * jpeg_alloc_quant_table (j_common_ptr cinfo)
JHUFF_TBL * jpeg_alloc_huff_table (j_common_ptr cinfo)
Macro Definition Documentation
#define JPEG_INTERNALS
Definition at line 12 of file jcomapi.c.
Function Documentation
void jpeg_abort (j_common_ptr cinfo)
Definition at line 29 of file jcomapi.c.
References CSTATE_START, DSTATE_START, JPOOL_NUMPOOLS, and JPOOL_PERMANENT.
Referenced by jpeg_abort_compress(), jpeg_abort_decompress(), jpeg_finish_compress(), jpeg_finish_decompress(), and jpeg_read_header().
JHUFF_TBL* jpeg_alloc_huff_table (j_common_ptr cinfo)
Definition at line 98 of file jcomapi.c.
References FALSE, JPOOL_PERMANENT, JHUFF_TBL::sent_table, and SIZEOF.
JQUANT_TBL* jpeg_alloc_quant_table (j_common_ptr cinfo)
Definition at line 86 of file jcomapi.c.
References FALSE, JPOOL_PERMANENT, JQUANT_TBL::sent_table, and SIZEOF.
Referenced by jpeg_add_quant_table(), and jpeg_copy_critical_parameters().
void jpeg_destroy (j_common_ptr cinfo)
Definition at line 69 of file jcomapi.c.
Referenced by jpeg_destroy_compress(), and jpeg_destroy_decompress().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1