OpenMAXBellagio: jdapistd.c File Reference
jdapistd.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Macros
#define JPEG_INTERNALS
Functions
boolean jpeg_start_decompress (j_decompress_ptr cinfo)
JDIMENSION jpeg_read_scanlines (j_decompress_ptr cinfo, JSAMPARRAY scanlines, JDIMENSION max_lines)
JDIMENSION jpeg_read_raw_data (j_decompress_ptr cinfo, JSAMPIMAGE data, JDIMENSION max_lines)
boolean jpeg_start_output (j_decompress_ptr cinfo, int scan_number)
boolean jpeg_finish_output (j_decompress_ptr cinfo)
Macro Definition Documentation
#define JPEG_INTERNALS
Definition at line 17 of file jdapistd.c.
Function Documentation
boolean jpeg_finish_output (j_decompress_ptr cinfo)
Definition at line 253 of file jdapistd.c.
References DSTATE_BUFIMAGE, DSTATE_BUFPOST, DSTATE_RAW_OK, DSTATE_SCANNING, ERREXIT1, FALSE, JERR_BAD_STATE, JPEG_SUSPENDED, and TRUE.
JDIMENSION jpeg_read_raw_data (j_decompress_ptr cinfo, JSAMPIMAGE data, JDIMENSION max_lines)
Definition at line 185 of file jdapistd.c.
References DSTATE_RAW_OK, ERREXIT, ERREXIT1, JERR_BAD_STATE, JERR_BUFFER_SIZE, JWRN_TOO_MUCH_DATA, and WARNMS.
JDIMENSION jpeg_read_scanlines (j_decompress_ptr cinfo, JSAMPARRAY scanlines, JDIMENSION max_lines)
Definition at line 152 of file jdapistd.c.
References DSTATE_SCANNING, ERREXIT1, JERR_BAD_STATE, JWRN_TOO_MUCH_DATA, and WARNMS.
Referenced by main(), omx_jpegdec_component_BufferMgmtCallback(), and omx_jpegdec_component_BufferMgmtFunction().
boolean jpeg_start_decompress (j_decompress_ptr cinfo)
Definition at line 38 of file jdapistd.c.
References DSTATE_BUFIMAGE, DSTATE_PRELOAD, DSTATE_PRESCAN, DSTATE_READY, ERREXIT, ERREXIT1, FALSE, JERR_BAD_STATE, JERR_NOT_COMPILED, jinit_master_decompress(), JPEG_REACHED_EOI, JPEG_REACHED_SOS, JPEG_ROW_COMPLETED, JPEG_SUSPENDED, and TRUE.
Referenced by main(), omx_jpegdec_component_BufferMgmtCallback(), and omx_jpegdec_component_BufferMgmtFunction().
boolean jpeg_start_output (j_decompress_ptr cinfo, int scan_number)
Definition at line 228 of file jdapistd.c.
References DSTATE_BUFIMAGE, DSTATE_PRESCAN, ERREXIT1, and JERR_BAD_STATE.
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1