OpenMAXBellagio: jerror.c File Reference
jerror.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
#include "jversion.h"
#include "jerror.h"
Macros
#define EXIT_FAILURE 1
#define JMESSAGE(code, string) string ,
Functions
struct jpeg_error_mgr * jpeg_std_error (struct jpeg_error_mgr *err)
Variables
const char *const jpeg_std_message_table []
Macro Definition Documentation
#define EXIT_FAILURE 1
Definition at line 32 of file jerror.c.
#define JMESSAGE (code, string) string ,
Definition at line 48 of file jerror.c.
Function Documentation
struct jpeg_error_mgr* jpeg_std_error (struct jpeg_error_mgr * err)
Definition at line 231 of file jerror.c.
References jpeg_error_mgr::emit_message, err, jpeg_error_mgr::error_exit, jpeg_error_mgr::format_message, JMSG_LASTMSGCODE, jpeg_std_message_table, jpeg_error_mgr::output_message, and jpeg_error_mgr::reset_error_mgr.
Referenced by main(), omx_jpegdec_component_Init(), and omx_jpegenc_component_Init().
Variable Documentation
const char* const jpeg_std_message_table[]
Definition at line 50 of file jerror.c.
Referenced by jpeg_std_error().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1