OpenMAXBellagio: omx_jpegdec_component.h File Reference
omx_jpegdec_component.h File Reference
#include <OMX_Types.h>
#include <OMX_Component.h>
#include <OMX_Core.h>
#include <OMX_Image.h>
#include <pthread.h>
#include <stdlib.h>
#include <string.h>
#include <omx_base_filter.h>
#include "libjpeg-6c/cdjpeg.h"
Macros
#define _CDJPEG_H_
#define BUFFER_ALLOCATED (1 << 0)
#define MAX_BUFFERS 2
#define DEFAULT_FRAME_WIDTH 640
#define DEFAULT_FRAME_HEIGHT 480
#define IN_BUFFER_SIZE 4096
#define OUT_BUFFER_SIZE DEFAULT_FRAME_WIDTH*DEFAULT_FRAME_HEIGHT*3 +54 /* 640 x 480 x 2bytes x(3/2) +54bytes header*/
#define IMAGE_DEC_BASE_NAME "OMX.st.image_decoder"
#define IMAGE_DEC_JPEG_NAME "OMX.st.image_decoder.jpeg"
#define IMAGE_DEC_JPEG_ROLE "image_decoder.jpeg"
#define omx_jpegdec_component_PrivateType_FIELDS
Functions
OMX_ERRORTYPE omx_jpegdec_component_Constructor (OMX_COMPONENTTYPE *openmaxStandComp, OMX_STRING cComponentName)
OMX_ERRORTYPE omx_jpegdec_component_Destructor (OMX_COMPONENTTYPE *openmaxStandComp)
OMX_ERRORTYPE omx_jpegdec_component_Init (OMX_COMPONENTTYPE *openmaxStandComp)
OMX_ERRORTYPE omx_jpegdec_component_Deinit (OMX_COMPONENTTYPE *openmaxStandComp)
OMX_ERRORTYPE omx_jpegdec_decoder_MessageHandler (OMX_COMPONENTTYPE *, internalRequestMessageType *)
void * omx_jpegdec_component_BufferMgmtFunction (void *param)
void omx_jpegdec_component_BufferMgmtCallback (OMX_COMPONENTTYPE *openmaxStandComp, OMX_BUFFERHEADERTYPE *inputbuffer, OMX_BUFFERHEADERTYPE *outputbuffer)
OMX_ERRORTYPE omx_jpegdec_component_GetParameter (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nParamIndex, OMX_INOUT OMX_PTR ComponentParameterStructure)
OMX_ERRORTYPE omx_jpegdec_component_SetParameter (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nParamIndex, OMX_IN OMX_PTR ComponentParameterStructure)
void jpeg_data_src (j_decompress_ptr cinfo, omx_jpegdec_component_PrivateType *omx_jpegdec_component_Private)
Detailed Description
This component implements an JPEG decoder based on Tom Lane's jpeg library (http://www.ijg.org/files/)
Copyright (C) 2007-2008 STMicroelectronics Copyright (C) 2007-2008 Nokia Corporation and/or its subsidiary(-ies).
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Date:
2008-09-15 07:27:22 +0200 (Mon, 15 Sep 2008)
Revision
Rev:
619
Author
Author:
pankaj_sen
Definition in file omx_jpegdec_component.h.
Macro Definition Documentation
#define _CDJPEG_H_
Definition at line 48 of file omx_jpegdec_component.h.
#define BUFFER_ALLOCATED (1 << 0)
Port private definition. Contains component allocated buffer descriptions. Only MAX_BUFFERS buffers can be allocated by the component Buffers have an allocated state: The user has requested a buffer/has not
Definition at line 57 of file omx_jpegdec_component.h.
#define DEFAULT_FRAME_HEIGHT 480
Definition at line 60 of file omx_jpegdec_component.h.
#define DEFAULT_FRAME_WIDTH 640
Definition at line 59 of file omx_jpegdec_component.h.
#define IMAGE_DEC_BASE_NAME "OMX.st.image_decoder"
Definition at line 65 of file omx_jpegdec_component.h.
#define IMAGE_DEC_JPEG_NAME "OMX.st.image_decoder.jpeg"
Definition at line 66 of file omx_jpegdec_component.h.
#define IMAGE_DEC_JPEG_ROLE "image_decoder.jpeg"
Definition at line 67 of file omx_jpegdec_component.h.
Referenced by omx_jpegdec_component_GetParameter(), and omx_jpegdec_component_SetParameter().
#define IN_BUFFER_SIZE 4096
Definition at line 61 of file omx_jpegdec_component.h.
#define MAX_BUFFERS 2
Definition at line 58 of file omx_jpegdec_component.h.
#define omx_jpegdec_component_PrivateType_FIELDS
Value:
omx_base_filter_PrivateType_FIELDS \
  struct jpeg_decompress_struct cinfo; \
  struct jpeg_error_mgr jerr; \
  struct jpeg_source_mgr jsrc; \
  djpeg_dest_ptr dest_mgr; \ \
  OMX_U32 image_coding_type;   \ \
  OMX_BOOL jpegdecReady;  \ \
  OMX_S32 isFirstBuffer;\ \
  OMX_S32 isNewBuffer; \\
  tsem_t* jpegdecSyncSem; \
  tsem_t* jpegdecSyncSem1; \
  OMX_BUFFERHEADERTYPE* pInBuffer; \
  OMX_COMPONENTTYPE* hMarkTargetComponent; \
  OMX_PTR            pMarkData; \
  OMX_U32            nFlags;
Jpeg Decoder component private structure.
Definition at line 72 of file omx_jpegdec_component.h.
#define OUT_BUFFER_SIZE DEFAULT_FRAME_WIDTH*DEFAULT_FRAME_HEIGHT*3 +54 /* 640 x 480 x 2bytes x(3/2) +54bytes header*/
Definition at line 62 of file omx_jpegdec_component.h.
Referenced by omx_jpegdec_component_Constructor().
Function Documentation
void jpeg_data_src (j_decompress_ptr cinfo, omx_jpegdec_component_PrivateType * omx_jpegdec_component_Private)
Definition at line 992 of file omx_jpegdec_component.c.
References jpeg_memory_mgr::alloc_small, my_source_mgr::buffer, jpeg_source_mgr::bytes_in_buffer, jpeg_source_mgr::fill_input_buffer, jpeg_source_mgr::init_source, INPUT_BUF_SIZE, jpeg_resync_to_restart(), JPOOL_PERMANENT, jpeg_decompress_struct::mem, jpeg_source_mgr::next_input_byte, my_source_mgr::omx_jpegdec_component_Private, my_source_mgr::pub, jpeg_source_mgr::resync_to_restart, jpeg_source_mgr::skip_input_data, jpeg_decompress_struct::src, and jpeg_source_mgr::term_source.
Referenced by omx_jpegdec_component_BufferMgmtCallback(), and omx_jpegdec_component_BufferMgmtFunction().
void omx_jpegdec_component_BufferMgmtCallback (OMX_COMPONENTTYPE * openmaxStandComp, OMX_BUFFERHEADERTYPE * inputbuffer, OMX_BUFFERHEADERTYPE * outputbuffer)
Definition at line 469 of file omx_jpegdec_component.c.
References DEB_LEV_ERR, DEB_LEV_FULL_SEQ, DEBUG, FALSE, finish_output_bmp_buf(), OMX_PARAM_PORTDEFINITIONTYPE::format, OMX_PARAM_PORTDEFINITIONTYPE::image, jinit_write_bmp(), jpeg_data_src(), jpeg_destroy_decompress(), jpeg_finish_decompress(), jpeg_read_header(), jpeg_read_scanlines(), jpeg_start_decompress(), OMX_BUFFERHEADERTYPE::nAllocLen, OMX_PARAM_PORTDEFINITIONTYPE::nBufferSize, OMX_BUFFERHEADERTYPE::nFilledLen, OMX_IMAGE_PORTDEFINITIONTYPE::nFrameHeight, OMX_IMAGE_PORTDEFINITIONTYPE::nFrameWidth, OMX_BASE_FILTER_OUTPUTPORT_INDEX, OMX_EventPortSettingsChanged, OMX_BUFFERHEADERTYPE::pBuffer, OMX_COMPONENTTYPE::pComponentPrivate, omx_base_image_PortType::sPortParam, TRUE, tsem_down(), and tsem_up().
void* omx_jpegdec_component_BufferMgmtFunction (void * param)
Definition at line 565 of file omx_jpegdec_component.c.
References DEB_LEV_ERR, DEB_LEV_FULL_SEQ, DEB_LEV_FUNCTION_NAME, DEBUG, dequeue(), FALSE, finish_output_bmp_buf(), OMX_BUFFERHEADERTYPE::hMarkTargetComponent, jinit_write_bmp(), jpeg_data_src(), jpeg_destroy_decompress(), jpeg_finish_decompress(), jpeg_read_header(), jpeg_read_scanlines(), jpeg_start_decompress(), OMX_BUFFERHEADERTYPE::nAllocLen, queue_t::nelem, OMX_BUFFERHEADERTYPE::nFilledLen, OMX_BUFFERHEADERTYPE::nFlags, OMX_BASE_FILTER_INPUTPORT_INDEX, OMX_BASE_FILTER_OUTPUTPORT_INDEX, OMX_BUFFERFLAG_EOS, OMX_EventBufferFlag, OMX_EventMark, OMX_EventPortSettingsChanged, OMX_FALSE, OMX_StateExecuting, OMX_StateIdle, OMX_StateInvalid, OMX_StateLoaded, OMX_StatePause, OMX_TransStateLoadedToIdle, OMX_TRUE, OMX_BUFFERHEADERTYPE::pBuffer, omx_base_PortType::pBufferSem, OMX_COMPONENTTYPE::pComponentPrivate, OMX_BUFFERHEADERTYPE::pMarkData, PORT_IS_BEING_FLUSHED, omx_base_PortType::ReturnBufferFunction, tsem_t::semval, TRUE, tsem_down(), and tsem_up().
Referenced by omx_jpegdec_component_Constructor().
OMX_ERRORTYPE omx_jpegdec_component_Constructor (OMX_COMPONENTTYPE * openmaxStandComp, OMX_STRING cComponentName)
The Constructor
Parameters
openmaxStandComp the component handle to be constructed
cComponentName name of the component to be constructed
we could create our own port structures here fixme maybe the base class could use a "port factory" function pointer?
Domain specific section for the ports.
first we set the parameter common to both formats parameters related to input port which does not depend upon input image format
Allocate Ports and call port constructor.
parameters related to input port
parameters related to output port
initialise the semaphore to be used for mad decoder access synchronization
general configuration irrespective of any image formats setting values of other fields of omx_jpegdec_component_Private structure
initialising mad structures
Definition at line 98 of file omx_jpegdec_component.c.
References base_image_port_Constructor(), OMX_IMAGE_PORTDEFINITIONTYPE::cMIMEType, DEB_LEV_FUNCTION_NAME, DEB_LEV_SIMPLE_SEQ, DEBUG, DEFAULT_IN_BUFFER_SIZE, OMX_IMAGE_PORTDEFINITIONTYPE::eCompressionFormat, OMX_IMAGE_PARAM_PORTFORMATTYPE::eCompressionFormat, err, OMX_PARAM_PORTDEFINITIONTYPE::format, OMX_COMPONENTTYPE::GetParameter, OMX_PARAM_PORTDEFINITIONTYPE::image, MAX_COMPONENT_JPEGDEC, OMX_PARAM_PORTDEFINITIONTYPE::nBufferCountActual, OMX_PARAM_PORTDEFINITIONTYPE::nBufferCountMin, OMX_PARAM_PORTDEFINITIONTYPE::nBufferSize, OMX_IMAGE_PORTDEFINITIONTYPE::nFrameHeight, OMX_IMAGE_PORTDEFINITIONTYPE::nFrameWidth, omx_base_filter_Constructor(), OMX_BASE_FILTER_INPUTPORT_INDEX, OMX_BASE_FILTER_OUTPUTPORT_INDEX, OMX_ErrorInsufficientResources, OMX_ErrorNone, OMX_FALSE, OMX_IMAGE_CodingJPEG, OMX_IMAGE_CodingUnused, omx_jpegdec_component_BufferMgmtFunction(), omx_jpegdec_component_Destructor(), omx_jpegdec_component_GetParameter(), omx_jpegdec_component_SetParameter(), omx_jpegdec_decoder_MessageHandler(), OMX_PortDomainImage, OMX_TRUE, OUT_BUFFER_SIZE, OMX_COMPONENTTYPE::pComponentPrivate, OMX_COMPONENTTYPE::SetParameter, omx_base_image_PortType::sImageParam, omx_base_image_PortType::sPortParam, and tsem_init().
Referenced by omx_component_library_Setup().
OMX_ERRORTYPE omx_jpegdec_component_Deinit (OMX_COMPONENTTYPE * openmaxStandComp)
The Deinitialization function
Definition at line 280 of file omx_jpegdec_component.c.
References err, and OMX_ErrorNone.
Referenced by omx_jpegdec_decoder_MessageHandler().
OMX_ERRORTYPE omx_jpegdec_component_Destructor (OMX_COMPONENTTYPE * openmaxStandComp)
The destructor
Definition at line 208 of file omx_jpegdec_component.c.
References DEB_LEV_FUNCTION_NAME, DEBUG, free(), omx_base_filter_Destructor(), OMX_ErrorNone, OMX_PortDomainImage, OMX_COMPONENTTYPE::pComponentPrivate, and tsem_deinit().
Referenced by omx_jpegdec_component_Constructor().
OMX_ERRORTYPE omx_jpegdec_component_GetParameter (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nParamIndex, OMX_INOUT OMX_PTR ComponentParameterStructure)
this function gets the parameters regarding image formats and index
Definition at line 344 of file omx_jpegdec_component.c.
References checkHeader(), OMX_PARAM_COMPONENTROLETYPE::cRole, DEB_LEV_SIMPLE_SEQ, DEBUG, err, IMAGE_DEC_JPEG_ROLE, OMX_IMAGE_PARAM_PORTFORMATTYPE::nPortIndex, omx_base_component_GetParameter(), OMX_ErrorBadParameter, OMX_ErrorBadPortIndex, OMX_ErrorNone, OMX_IMAGE_CodingJPEG, OMX_IndexParamImageInit, OMX_IndexParamImagePortFormat, OMX_IndexParamStandardComponentRole, OMX_PortDomainImage, OMX_COMPONENTTYPE::pComponentPrivate, and omx_base_image_PortType::sImageParam.
Referenced by omx_jpegdec_component_Constructor().
OMX_ERRORTYPE omx_jpegdec_component_Init (OMX_COMPONENTTYPE * openmaxStandComp)
The Initialization function
Definition at line 246 of file omx_jpegdec_component.c.
References DEB_LEV_FUNCTION_NAME, DEBUG, err, FMT_BMP, JMSG_FIRSTADDONCODE, JMSG_LASTADDONCODE, JPEG_APP0, JPEG_COM, jpeg_create_decompress, jpeg_set_marker_processor(), jpeg_std_error(), OMX_ErrorNone, and OMX_COMPONENTTYPE::pComponentPrivate.
Referenced by omx_jpegdec_decoder_MessageHandler().
OMX_ERRORTYPE omx_jpegdec_component_SetParameter (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nParamIndex, OMX_IN OMX_PTR ComponentParameterStructure)
this function sets the parameter values regarding image format & index
Definition at line 289 of file omx_jpegdec_component.c.
References OMX_PARAM_COMPONENTROLETYPE::cRole, DEB_LEV_ERR, DEB_LEV_SIMPLE_SEQ, DEBUG, err, IMAGE_DEC_JPEG_ROLE, OMX_IMAGE_PARAM_PORTFORMATTYPE::nPortIndex, omx_base_component_ParameterSanityCheck(), omx_base_component_SetParameter(), OMX_ErrorBadParameter, OMX_ErrorBadPortIndex, OMX_ErrorNone, OMX_IMAGE_CodingJPEG, OMX_IndexParamImagePortFormat, OMX_IndexParamStandardComponentRole, OMX_COMPONENTTYPE::pComponentPrivate, and omx_base_image_PortType::sImageParam.
Referenced by omx_jpegdec_component_Constructor().
OMX_ERRORTYPE omx_jpegdec_decoder_MessageHandler (OMX_COMPONENTTYPE * , internalRequestMessageType *)
Execute the base message handling
Definition at line 1022 of file omx_jpegdec_component.c.
References DEB_LEV_ERR, DEB_LEV_SIMPLE_SEQ, DEBUG, err, internalRequestMessageType::messageParam, internalRequestMessageType::messageType, omx_base_component_MessageHandler(), OMX_CommandStateSet, OMX_ErrorNone, omx_jpegdec_component_Deinit(), omx_jpegdec_component_Init(), OMX_StateIdle, OMX_StateLoaded, and OMX_COMPONENTTYPE::pComponentPrivate.
Referenced by omx_jpegdec_component_Constructor().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1