OpenMAXBellagio: omx_create_loaders_linux.c File Reference
omx_create_loaders_linux.c File Reference
#include <stdlib.h>
#include <dlfcn.h>
#include <string.h>
#include "component_loader.h"
#include "omx_create_loaders.h"
#include "omxcore.h"
#include "st_static_component_loader.h"
Macros
#define _GNU_SOURCE
Functions
int createComponentLoaders ()
Detailed Description
In this file is implemented the entry point for the construction of every component loader in linux. In the curent implementation only the st static loader is called.
Copyright (C) 2008 Nokia Corporation and/or its subsidiary(-ies).
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Date:
2008-07-08 10:30:56 +0200 (Tue, 08 Jul 2008)
Revision
Rev:
566
Author
Author:
bfouet
Definition in file omx_create_loaders_linux.c.
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 31 of file omx_create_loaders_linux.c.
Function Documentation
int createComponentLoaders (void)
Definition at line 41 of file omx_create_loaders_linux.c.
References BOSA_AddComponentLoader(), DEB_LEV_ERR, DEB_LEV_FUNCTION_NAME, DEBUG, free(), handle, st_static_InitComponentLoader(), and st_static_loader.
Referenced by OMX_Init().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1