OpenMAXBellagio: omx_base_video_port.h File Reference
omx_base_video_port.h File Reference
#include "omx_classmagic.h"
#include "omx_base_port.h"
Data Structures
struct omx_base_video_PortType
Macros
#define MAX_VIDEO_OUTPUT_BUF_SIZE 460800
#define MIN_VIDEO_OUTPUT_BUF_SIZE 176*144*3
#define omx_base_video_PortType_FIELDS
Typedefs
typedef struct
omx_base_video_PortType omx_base_video_PortType
the base video domain structure that describes each port.
Functions
OMX_ERRORTYPE base_video_port_Constructor (OMX_COMPONENTTYPE *openmaxStandComp, omx_base_PortType **openmaxStandPort, OMX_U32 nPortIndex, OMX_BOOL isInput)
The base contructor for the generic OpenMAX ST Video port.
OMX_ERRORTYPE base_video_port_Destructor (omx_base_PortType *openmaxStandPort)
The base video port destructor for the generic OpenMAX ST Video port.
Detailed Description
Base Video Port class for OpenMAX ports to be used in derived components.
Copyright (C) 2007-2008 STMicroelectronics Copyright (C) 2007-2008 Nokia Corporation and/or its subsidiary(-ies).
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Date:
2008-07-07 14:30:38 +0200 (Mon, 07 Jul 2008)
Revision
Rev:
562
Author
Author:
gsent
Definition in file omx_base_video_port.h.
Macro Definition Documentation
#define MAX_VIDEO_OUTPUT_BUF_SIZE 460800
define the max output buffer size
Definition at line 37 of file omx_base_video_port.h.
Referenced by base_video_port_Constructor().
#define MIN_VIDEO_OUTPUT_BUF_SIZE 176*144*3
Definition at line 38 of file omx_base_video_port.h.
#define omx_base_video_PortType_FIELDS
Value:
omx_base_PortType_FIELDS \ \
  OMX_VIDEO_PARAM_PORTFORMATTYPE sVideoParam;
Definition at line 48 of file omx_base_video_port.h.
Typedef Documentation
typedef struct omx_base_video_PortType omx_base_video_PortType
the base video domain structure that describes each port.
The data structure is derived from base port class and contain video domain specific parameters. Other elements can be added in the derived components structures.
Definition at line 47 of file omx_base_video_port.h.
Function Documentation
OMX_ERRORTYPE base_video_port_Constructor (OMX_COMPONENTTYPE * openmaxStandComp, omx_base_PortType ** openmaxStandPort, OMX_U32 nPortIndex, OMX_BOOL isInput)
The base contructor for the generic OpenMAX ST Video port.
This function is executed by the component that uses a port. The parameter contains the info about the component. It takes care of constructing the instance of the port and every object needed by the base port.
Parameters
openmaxStandComp pointer to the Handle of the component
openmaxStandPort the ST port to be initialized
nPortIndex Index of the port to be constructed
isInput specifices if the port is an input or an output
Returns
OMX_ErrorInsufficientResources if a memory allocation fails
Definition at line 54 of file omx_base_video_port.c.
References base_port_Constructor(), base_video_port_Destructor(), OMX_VIDEO_PORTDEFINITIONTYPE::bFlagErrorConcealment, OMX_VIDEO_PORTDEFINITIONTYPE::cMIMEType, DEFAULT_IN_BUFFER_SIZE, DEFAULT_MIME_STRING_LENGTH, OMX_VIDEO_PORTDEFINITIONTYPE::eColorFormat, OMX_VIDEO_PARAM_PORTFORMATTYPE::eColorFormat, OMX_VIDEO_PORTDEFINITIONTYPE::eCompressionFormat, OMX_VIDEO_PARAM_PORTFORMATTYPE::eCompressionFormat, OMX_PARAM_PORTDEFINITIONTYPE::eDomain, OMX_PARAM_PORTDEFINITIONTYPE::format, malloc(), MAX_VIDEO_OUTPUT_BUF_SIZE, OMX_VIDEO_PORTDEFINITIONTYPE::nBitrate, OMX_PARAM_PORTDEFINITIONTYPE::nBufferSize, OMX_VIDEO_PORTDEFINITIONTYPE::nFrameHeight, OMX_VIDEO_PORTDEFINITIONTYPE::nFrameWidth, OMX_VIDEO_PARAM_PORTFORMATTYPE::nIndex, OMX_VIDEO_PARAM_PORTFORMATTYPE::nPortIndex, OMX_VIDEO_PORTDEFINITIONTYPE::nSliceHeight, OMX_VIDEO_PORTDEFINITIONTYPE::nStride, OMX_COLOR_FormatUnused, OMX_ErrorInsufficientResources, OMX_ErrorNone, OMX_FALSE, OMX_PortDomainVideo, OMX_TRUE, OMX_VIDEO_CodingUnused, OMX_VIDEO_PORTDEFINITIONTYPE::pNativeRender, OMX_VIDEO_PORTDEFINITIONTYPE::pNativeWindow, omx_base_video_PortType::PortDestructor, setHeader(), omx_base_video_PortType::sPortParam, omx_base_video_PortType::sVideoParam, OMX_PARAM_PORTDEFINITIONTYPE::video, OMX_VIDEO_PORTDEFINITIONTYPE::xFramerate, and OMX_VIDEO_PARAM_PORTFORMATTYPE::xFramerate.
Referenced by omx_camera_source_component_Constructor(), omx_fbdev_sink_component_Constructor(), omx_ffmpeg_colorconv_component_Constructor(), omx_parser3gp_component_Constructor(), omx_videodec_component_Constructor(), omx_videoenc_component_Constructor(), and omx_videosrc_component_Constructor().
OMX_ERRORTYPE base_video_port_Destructor (omx_base_PortType * openmaxStandPort)
The base video port destructor for the generic OpenMAX ST Video port.
This function is executed by the component that uses a port. The parameter contains the info about the port. It takes care of destructing the instance of the port
Parameters
openmaxStandPort the ST port to be destructed
Returns
OMX_ErrorNone
Definition at line 113 of file omx_base_video_port.c.
References base_port_Destructor(), OMX_VIDEO_PORTDEFINITIONTYPE::cMIMEType, OMX_PARAM_PORTDEFINITIONTYPE::format, free(), OMX_ErrorNone, omx_base_PortType::sPortParam, and OMX_PARAM_PORTDEFINITIONTYPE::video.
Referenced by base_video_port_Constructor().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1