OpenMAXBellagio: omx_symbian_output_stream_wrapper.h File Reference
omx_symbian_output_stream_wrapper.h File Reference
Functions
int create_output_stream (void **output)
int open_output_stream (void *output, int sampleRate, int channels)
int close_output_stream (void *output)
int write_audio_data (void *output, unsigned char *buffer, int length)
Detailed Description
Copyright (C) 2008 Nokia Corporation and/or its subsidiary(-ies).
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Definition in file omx_symbian_output_stream_wrapper.h.
Function Documentation
int close_output_stream (void * output)
Referenced by omx_symbianoutputstreamsink_component_Destructor().
int create_output_stream (void ** output)
Referenced by omx_symbianoutputstreamsink_component_Constructor().
int open_output_stream (void * output, int sampleRate, int channels)
Referenced by omx_symbianoutputstreamsink_component_BufferMgmtCallback().
int write_audio_data (void * output, unsigned char * buffer, int length)
Referenced by omx_symbianoutputstreamsink_component_BufferMgmtCallback().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1