OpenMAXBellagio: omxclocksrctest.c File Reference
omxclocksrctest.c File Reference
#include "omxclocksrctest.h"
Macros
#define CLOCK_SRC "OMX.st.clocksrc"
#define MAX_CLOCK_PORTS 8
Functions
int main (int argc, char **argv)
OMX_ERRORTYPE clocksrcEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
OMX_ERRORTYPE clocksrcFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
Variables
OMX_CALLBACKTYPE clocksrccallbacks
appPrivateType * appPriv
OMX_ERRORTYPE err
OMX_HANDLETYPE handle
OMX_BUFFERHEADERTYPE * outBuffer [8]
Detailed Description
This simple application test clock component.
Copyright (C) 2007-2008 STMicroelectronics Copyright (C) 2007-2008 Nokia Corporation and/or its subsidiary(-ies).
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Date:
2008-06-27 11:40:05 +0200 (Fri, 27 Jun 2008)
Revision
Rev:
1417
Author
Author:
mmathur
Definition in file omxclocksrctest.c.
Macro Definition Documentation
#define CLOCK_SRC "OMX.st.clocksrc"
Definition at line 31 of file omxclocksrctest.c.
Referenced by main().
#define MAX_CLOCK_PORTS 8
Definition at line 32 of file omxclocksrctest.c.
Function Documentation
OMX_ERRORTYPE clocksrcEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
Definition at line 238 of file omxclocksrctest.c.
OMX_ERRORTYPE clocksrcFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
Definition at line 299 of file omxclocksrctest.c.
int main (int argc, char ** argv)
now set the Clock Component component to idle and executing state
Definition at line 59 of file omxclocksrctest.c.
References CLOCK_SRC, appPrivateType::clockEventSem, DEB_LEV_ERR, DEBUG, DEFAULT_MESSAGES, OMX_TIME_CONFIG_ACTIVEREFCLOCKTYPE::eClock, appPrivateType::eofSem, err, OMX_TIME_CONFIG_CLOCKSTATETYPE::eState, appPrivateType::eventSem, free(), handle, malloc(), OMX_PARAM_PORTDEFINITIONTYPE::nBufferSize, OMX_PARAM_PORTDEFINITIONTYPE::nPortIndex, OMX_TIME_CONFIG_TIMESTAMPTYPE::nPortIndex, OMX_TIME_CONFIG_CLOCKSTATETYPE::nWaitMask, OMX_AllocateBuffer, OMX_CommandPortDisable, OMX_CommandStateSet, OMX_ErrorNone, OMX_FillThisBuffer, OMX_FreeBuffer, OMX_FreeHandle(), OMX_GetConfig, OMX_GetHandle(), OMX_GetParameter, OMX_IndexConfigTimeActiveRefClock, OMX_IndexConfigTimeClientStartTime, OMX_IndexConfigTimeClockState, OMX_IndexConfigTimeCurrentWallTime, OMX_IndexParamPortDefinition, OMX_Init(), OMX_SendCommand, OMX_SetConfig, OMX_StateExecuting, OMX_StateIdle, OMX_StateLoaded, OMX_TIME_ClockStateStopped, OMX_TIME_ClockStateWaitingForStartTime, OMX_TIME_RefClockAudio, OMX_TRUE, setHeader(), tsem_down(), and tsem_init().
Variable Documentation
appPrivateType* appPriv
Definition at line 53 of file omxclocksrctest.c.
OMX_CALLBACKTYPE clocksrccallbacks
Initial value:
= {
  .EventHandler    = clocksrcEventHandler,
  .EmptyBufferDone = NULL,
  .FillBufferDone  = clocksrcFillBufferDone
}
Definition at line 46 of file omxclocksrctest.c.
OMX_ERRORTYPE err
Definition at line 54 of file omxclocksrctest.c.
Referenced by clocksrcFillBufferDone(), and main().
OMX_HANDLETYPE handle
Definition at line 55 of file omxclocksrctest.c.
Referenced by clocksrcFillBufferDone(), and main().
OMX_BUFFERHEADERTYPE* outBuffer[8]
Definition at line 56 of file omxclocksrctest.c.
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1