OpenMAXBellagio: omxjpegenctest.c File Reference
omxjpegenctest.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <sys/ipc.h>
#include <sys/sem.h>
#include <sys/types.h>
#include <sys/mman.h>
#include <fcntl.h>
#include <string.h>
#include <OMX_Core.h>
#include <user_debug_levels.h>
#include "omxjpegenctest.h"
#include "tsemaphore.h"
Macros
#define _DEBUG
Functions
void display_help ()
int main (int argc, char **argv)
OMX_ERRORTYPE jpegEncEventHandler (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_PTR pAppData, OMX_IN OMX_EVENTTYPE eEvent, OMX_IN OMX_U32 nData1, OMX_IN OMX_U32 nData2, OMX_IN OMX_PTR pEventData)
OMX_ERRORTYPE jpegEncEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
OMX_ERRORTYPE jpegEncFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
void setHeader (OMX_PTR header, OMX_U32 size)
Simply fills the first two fields in any OMX structure with the size and the version.
Variables
appPrivateType * appPriv
OMX_U32 filesize
OMX_U32 size = 4096
OMX_S32 nextBuffer = 0
int flagIsOutputExpected
int flagIsInputExpected
int flagOutputReceived
int flagInputReceived
OMX_S32 fd
FILE * infile
FILE * outfile
char * input_file
Macro Definition Documentation
#define _DEBUG
Definition at line 50 of file omxjpegenctest.c.
Function Documentation
void display_help ()
function prototype declaration display general help
help display
Definition at line 52 of file omxjpegenctest.c.
Referenced by main().
OMX_ERRORTYPE jpegEncEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
Definition at line 323 of file omxjpegenctest.c.
References DEB_LEV_ERR, DEBUG, err, and OMX_ErrorNone.
Referenced by main().
OMX_ERRORTYPE jpegEncEventHandler (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_PTR pAppData, OMX_IN OMX_EVENTTYPE eEvent, OMX_IN OMX_U32 nData1, OMX_IN OMX_U32 nData2, OMX_IN OMX_PTR pEventData)
Definition at line 285 of file omxjpegenctest.c.
References DEB_LEV_PARAMS, DEB_LEV_SIMPLE_SEQ, DEBUG, err, OMX_PARAM_PORTDEFINITIONTYPE::format, appPrivateType::frame_height, appPrivateType::frame_width, OMX_PARAM_PORTDEFINITIONTYPE::nBufferSize, OMX_VIDEO_PORTDEFINITIONTYPE::nFrameHeight, OMX_VIDEO_PORTDEFINITIONTYPE::nFrameWidth, OMX_PARAM_PORTDEFINITIONTYPE::nPortIndex, OMX_ErrorNone, OMX_EventCmdComplete, OMX_EventPortSettingsChanged, OMX_GetConfig, OMX_GetParameter, OMX_IndexParamPortDefinition, appPrivateType::outframe_buffer_size, setHeader(), appPrivateType::stateSem, tsem_up(), and OMX_PARAM_PORTDEFINITIONTYPE::video.
Referenced by main().
OMX_ERRORTYPE jpegEncFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
Definition at line 361 of file omxjpegenctest.c.
References DEB_ALL_MESS, DEBUG, appPrivateType::eosSem, OMX_ErrorNone, outfile, appPrivateType::output_file, and tsem_up().
Referenced by main().
int main (int argc, char ** argv)
Ask the core for a handle to the mpeg2 component
Definition at line 79 of file omxjpegenctest.c.
References callbacks, DEB_LEV_ERR, DEB_LEV_PARAMS, DEB_LEV_SIMPLE_SEQ, DEBUG, DEFAULT_MESSAGES, display_help(), err, OMX_CALLBACKTYPE::EventHandler, fd, filesize, flagInputReceived, flagIsInputExpected, flagIsOutputExpected, flagOutputReceived, free(), INPUT_BUFFER_SIZE, input_file, jpegEncEmptyBufferDone(), jpegEncEventHandler(), jpegEncFillBufferDone(), malloc(), OMX_VERSIONTYPE::nRevision, OMX_VERSIONTYPE::nStep, OMX_VERSIONTYPE::nVersionMajor, OMX_VERSIONTYPE::nVersionMinor, OMX_AllocateBuffer, OMX_CommandStateSet, OMX_Deinit(), OMX_EmptyThisBuffer, OMX_FillThisBuffer, OMX_FreeBuffer, OMX_FreeHandle(), OMX_GetComponentVersion, OMX_GetHandle(), OMX_Init(), OMX_SendCommand, OMX_StateExecuting, OMX_StateIdle, OMX_StateLoaded, OMX_UseBuffer, OUTPUT_BUFFER_SIZE, OMX_VERSIONTYPE::s, tsem_deinit(), tsem_down(), and tsem_init().
void setHeader (OMX_PTR header, OMX_U32 size)
Simply fills the first two fields in any OMX structure with the size and the version.
Parameters
header pointer to the structure to be filled
size size of the structure. It can be obtained with a call to sizeof of the structure type
Definition at line 384 of file omxjpegenctest.c.
References OMX_VERSIONTYPE::nRevision, OMX_VERSIONTYPE::nStep, OMX_VERSIONTYPE::nVersionMajor, OMX_VERSIONTYPE::nVersionMinor, OMX_VERSIONTYPE::s, size, SPECREVISION, SPECSTEP, SPECVERSIONMAJOR, SPECVERSIONMINOR, VERSIONMAJOR, VERSIONMINOR, VERSIONREVISION, and VERSIONSTEP.
Referenced by jpegEncEventHandler().
Variable Documentation
appPrivateType* appPriv
Definition at line 64 of file omxjpegenctest.c.
OMX_S32 fd
Definition at line 74 of file omxjpegenctest.c.
Referenced by main().
OMX_U32 filesize
Definition at line 66 of file omxjpegenctest.c.
Referenced by main().
int flagInputReceived
Definition at line 72 of file omxjpegenctest.c.
Referenced by main().
int flagIsInputExpected
Definition at line 70 of file omxjpegenctest.c.
Referenced by main().
int flagIsOutputExpected
Definition at line 69 of file omxjpegenctest.c.
Referenced by main().
int flagOutputReceived
Definition at line 71 of file omxjpegenctest.c.
Referenced by main().
FILE* infile
Definition at line 75 of file omxjpegenctest.c.
char* input_file
Definition at line 76 of file omxjpegenctest.c.
Referenced by main().
OMX_S32 nextBuffer = 0
Definition at line 67 of file omxjpegenctest.c.
FILE * outfile
Definition at line 75 of file omxjpegenctest.c.
Referenced by jpegEncFillBufferDone().
OMX_U32 size = 4096
Definition at line 66 of file omxjpegenctest.c.
Referenced by setHeader().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1