OpenMAXBellagio: jpeg_error_mgr Struct Reference
jpeg_error_mgr Struct Reference
#include <jpeglib.h>
Data Fields
void(* error_exit)()
void(* emit_message)()
void(* output_message)()
void(* format_message)()
void(* reset_error_mgr)()
int msg_code
union {
int i [8]
char s [80]
} msg_parm
int trace_level
long num_warnings
const char *const * jpeg_message_table
int last_jpeg_message
const char *const * addon_message_table
int first_addon_message
int last_addon_message
Detailed Description
Definition at line 662 of file jpeglib.h.
Field Documentation
const char* const* jpeg_error_mgr::addon_message_table
Definition at line 712 of file jpeglib.h.
Referenced by main().
void(* jpeg_error_mgr::emit_message)()
Definition at line 666 of file jpeglib.h.
Referenced by jpeg_std_error().
void(* jpeg_error_mgr::error_exit)()
Definition at line 664 of file jpeglib.h.
Referenced by jpeg_std_error().
int jpeg_error_mgr::first_addon_message
Definition at line 713 of file jpeglib.h.
Referenced by main().
void(* jpeg_error_mgr::format_message)()
Definition at line 670 of file jpeglib.h.
Referenced by jpeg_std_error().
int jpeg_error_mgr::i[8]
Definition at line 681 of file jpeglib.h.
Referenced by jpeg_CreateCompress(), jpeg_CreateDecompress(), and jpeg_suppress_tables().
const char* const* jpeg_error_mgr::jpeg_message_table
Definition at line 707 of file jpeglib.h.
int jpeg_error_mgr::last_addon_message
Definition at line 714 of file jpeglib.h.
Referenced by main().
int jpeg_error_mgr::last_jpeg_message
Definition at line 708 of file jpeglib.h.
int jpeg_error_mgr::msg_code
Definition at line 678 of file jpeglib.h.
union { ... } jpeg_error_mgr::msg_parm
long jpeg_error_mgr::num_warnings
Definition at line 695 of file jpeglib.h.
Referenced by main().
void(* jpeg_error_mgr::output_message)()
Definition at line 668 of file jpeglib.h.
Referenced by jpeg_std_error().
void(* jpeg_error_mgr::reset_error_mgr)()
Definition at line 673 of file jpeglib.h.
Referenced by jpeg_std_error().
char jpeg_error_mgr::s[80]
Definition at line 682 of file jpeglib.h.
int jpeg_error_mgr::trace_level
Definition at line 687 of file jpeglib.h.
Referenced by main().
The documentation for this struct was generated from the following file:
jpeglib.h
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1