OpenMAXBellagio: audio_use_case_tunnel.c File Reference
audio_use_case_tunnel.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <dirent.h>
#include <errno.h>
#include "omxaudiodectest.h"
Macros
#define COMPONENT_NAME_BASE "OMX.st.audio_decoder"
#define VORBIS_ROLE "audio_decoder.ogg"
#define MP3_ROLE "audio_decoder.mp3"
#define AAC_ROLE "audio_decoder.aac"
#define SINK_NAME "OMX.st.alsa.alsasink"
#define FILE_READER "OMX.st.audio_filereader"
#define AUDIO_EFFECT "OMX.st.volume.component"
#define extradata_size 1024
Functions
void display_help ()
int main (int argc, char **argv)
OMX_ERRORTYPE filereaderEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
OMX_ERRORTYPE audiodecEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
OMX_ERRORTYPE volumeEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
OMX_ERRORTYPE audiosinkEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
Variables
OMX_CALLBACKTYPE audiodeccallbacks
OMX_CALLBACKTYPE audiosinkcallbacks
OMX_CALLBACKTYPE filereadercallbacks
OMX_CALLBACKTYPE volumecallbacks
appPrivateType * appPriv
char * input_file =NULL
int flagSetupTunnel
int flagPlaybackOn
int flagUsingFFMpeg
int flagIsGain
Detailed Description
Test application that uses four OpenMAX components, a file reader,an audio decoder , an audio effect and an alsa sink. The application receives an compressed audio stream on input port from a file, decodes it and sends it to the alsa sink, or to a file or standard output.
This test application goes through a directory and plays all mp3,ogg and aac files in a loop
Copyright (C) 2007-2008 STMicroelectronics Copyright (C) 2007-2008 Nokia Corporation and/or its subsidiary(-ies).
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Date:
2008-09-11 13:48:00 +0200 (Thu, 11 Sep 2008)
Revision
Rev:
1485
Author
Author:
pankaj_sen
Definition in file audio_use_case_tunnel.c.
Macro Definition Documentation
#define AAC_ROLE "audio_decoder.aac"
Definition at line 44 of file audio_use_case_tunnel.c.
Referenced by main().
#define AUDIO_EFFECT "OMX.st.volume.component"
Definition at line 47 of file audio_use_case_tunnel.c.
Referenced by main().
#define COMPONENT_NAME_BASE "OMX.st.audio_decoder"
Definition at line 41 of file audio_use_case_tunnel.c.
Referenced by main().
#define extradata_size 1024
Definition at line 48 of file audio_use_case_tunnel.c.
Referenced by filereaderEventHandler().
#define FILE_READER "OMX.st.audio_filereader"
Definition at line 46 of file audio_use_case_tunnel.c.
Referenced by main().
#define MP3_ROLE "audio_decoder.mp3"
Definition at line 43 of file audio_use_case_tunnel.c.
Referenced by main().
#define SINK_NAME "OMX.st.alsa.alsasink"
Definition at line 45 of file audio_use_case_tunnel.c.
Referenced by main().
#define VORBIS_ROLE "audio_decoder.ogg"
Definition at line 42 of file audio_use_case_tunnel.c.
Referenced by main().
Function Documentation
OMX_ERRORTYPE audiodecEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
callback prototypes for audio Decoder
Definition at line 742 of file audio_use_case_tunnel.c.
References appPrivateType::audiodechandle, appPrivateType::audiosinkhandle, DEB_LEV_ERR, DEB_LEV_SIMPLE_SEQ, DEBUG, appPrivateType::decoderEventSem, DEFAULT_MESSAGES, err, flagPlaybackOn, flagSetupTunnel, OMX_PARAM_PORTDEFINITIONTYPE::nPortIndex, OMX_AUDIO_PARAM_PCMMODETYPE::nPortIndex, OMX_BUFFERFLAG_EOS, OMX_CommandPortDisable, OMX_CommandPortEnable, OMX_CommandStateSet, OMX_ErrorNone, OMX_EventBufferFlag, OMX_EventCmdComplete, OMX_EventPortSettingsChanged, OMX_GetParameter, OMX_IndexParamAudioPcm, OMX_IndexParamPortDefinition, OMX_SendCommand, OMX_SetParameter, OMX_StateExecuting, OMX_StateIdle, OMX_StateInvalid, OMX_StateLoaded, OMX_StatePause, OMX_StateWaitForResources, OMX_TRUE, setHeader(), appPrivateType::sinkEventSem, tsem_down(), tsem_up(), appPrivateType::volumeEventSem, and appPrivateType::volumehandle.
OMX_ERRORTYPE audiosinkEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
callback prototypes for audio sink
Definition at line 917 of file audio_use_case_tunnel.c.
References DEB_LEV_SIMPLE_SEQ, DEBUG, DEFAULT_MESSAGES, appPrivateType::eofSem, OMX_BUFFERFLAG_EOS, OMX_CommandPortDisable, OMX_CommandPortEnable, OMX_CommandStateSet, OMX_ErrorNone, OMX_EventBufferFlag, OMX_EventCmdComplete, OMX_StateExecuting, OMX_StateIdle, OMX_StateInvalid, OMX_StateLoaded, OMX_StatePause, OMX_StateWaitForResources, OMX_TRUE, appPrivateType::sinkEventSem, and tsem_up().
void display_help ()
function prototype declaration display general help
Definition at line 89 of file audio_use_case_tunnel.c.
Referenced by main().
OMX_ERRORTYPE filereaderEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
Definition at line 656 of file audio_use_case_tunnel.c.
References appPrivateType::audiodechandle, DEB_LEV_ERR, DEB_LEV_SIMPLE_SEQ, DEBUG, DEFAULT_MESSAGES, err, extradata_size, appPrivateType::filereaderEventSem, appPrivateType::filereaderhandle, flagUsingFFMpeg, free(), malloc(), OMX_BUFFERFLAG_EOS, OMX_CommandPortDisable, OMX_CommandPortEnable, OMX_CommandStateSet, OMX_ErrorNone, OMX_EventBufferFlag, OMX_EventCmdComplete, OMX_EventPortFormatDetected, OMX_EventPortSettingsChanged, OMX_GetConfig, OMX_GetExtensionIndex, OMX_SetConfig, OMX_StateExecuting, OMX_StateIdle, OMX_StateInvalid, OMX_StateLoaded, OMX_StatePause, OMX_StateWaitForResources, OMX_TRUE, and tsem_up().
int main (int argc, char ** argv)
initializing appPriv structure
initialising openmax
file reader component name – gethandle
getting the handle of audio decoder
now set the filereader component to idle and executing state
setting the input audio format in file reader
freeing all handles and deinit omx
Definition at line 108 of file audio_use_case_tunnel.c.
References AAC_ROLE, AUDIO_EFFECT, appPrivateType::audiodechandle, appPrivateType::audiosinkhandle, COMPONENT_NAME_BASE, OMX_PARAM_COMPONENTROLETYPE::cRole, DEB_LEV_ERR, DEB_LEV_SIMPLE_SEQ, DEBUG, appPrivateType::decoderEventSem, DEFAULT_MESSAGES, display_help(), appPrivateType::eofSem, err, FILE_READER, appPrivateType::filereaderEventSem, appPrivateType::filereaderhandle, flagIsGain, flagPlaybackOn, flagSetupTunnel, flagUsingFFMpeg, free(), input_file, malloc(), MP3_ROLE, OMX_TIME_CONFIG_TIMESTAMPTYPE::nPortIndex, OMX_TIME_CONFIG_TIMESTAMPTYPE::nTimestamp, OMX_BS32::nValue, OMX_CommandPortDisable, OMX_CommandPortEnable, OMX_CommandStateSet, OMX_Deinit(), OMX_ErrorNone, OMX_FALSE, OMX_FreeHandle(), OMX_GetConfig, OMX_GetExtensionIndex, OMX_GetHandle(), OMX_IndexConfigAudioVolume, OMX_IndexConfigTimePosition, OMX_IndexParamStandardComponentRole, OMX_Init(), OMX_SendCommand, OMX_SetConfig, OMX_SetParameter, OMX_SetupTunnel(), OMX_StateExecuting, OMX_StateIdle, OMX_StateLoaded, OMX_StatePause, tsem_t::semval, setHeader(), SINK_NAME, appPrivateType::sinkEventSem, OMX_AUDIO_CONFIG_VOLUMETYPE::sVolume, tsem_down(), tsem_init(), tsem_reset(), appPrivateType::volumeEventSem, appPrivateType::volumehandle, and VORBIS_ROLE.
OMX_ERRORTYPE volumeEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
callback prototypes for color converter
Definition at line 862 of file audio_use_case_tunnel.c.
References DEB_LEV_SIMPLE_SEQ, DEBUG, DEFAULT_MESSAGES, OMX_BUFFERFLAG_EOS, OMX_CommandPortDisable, OMX_CommandPortEnable, OMX_CommandStateSet, OMX_ErrorNone, OMX_EventBufferFlag, OMX_EventCmdComplete, OMX_StateExecuting, OMX_StateIdle, OMX_StateInvalid, OMX_StateLoaded, OMX_StatePause, OMX_StateWaitForResources, OMX_TRUE, tsem_up(), and appPrivateType::volumeEventSem.
Variable Documentation
appPrivateType* appPriv
Definition at line 75 of file audio_use_case_tunnel.c.
OMX_CALLBACKTYPE audiodeccallbacks
Initial value:
= {
  .EventHandler    = audiodecEventHandler,
  .EmptyBufferDone = NULL,
  .FillBufferDone  = NULL
}
Definition at line 50 of file audio_use_case_tunnel.c.
OMX_CALLBACKTYPE audiosinkcallbacks
Initial value:
= {
  .EventHandler    = audiosinkEventHandler,
  .EmptyBufferDone = NULL,
  .FillBufferDone  = NULL
}
Definition at line 56 of file audio_use_case_tunnel.c.
OMX_CALLBACKTYPE filereadercallbacks
Initial value:
= {
  .EventHandler    = filereaderEventHandler,
  .EmptyBufferDone = NULL,
  .FillBufferDone  = NULL
}
Definition at line 62 of file audio_use_case_tunnel.c.
int flagIsGain
Definition at line 105 of file audio_use_case_tunnel.c.
Referenced by main().
int flagPlaybackOn
Definition at line 103 of file audio_use_case_tunnel.c.
Referenced by audiodecEventHandler(), and main().
int flagSetupTunnel
Definition at line 102 of file audio_use_case_tunnel.c.
Referenced by audiodecEventHandler(), and main().
int flagUsingFFMpeg
Definition at line 104 of file audio_use_case_tunnel.c.
Referenced by filereaderEventHandler(), and main().
char* input_file =NULL
Definition at line 76 of file audio_use_case_tunnel.c.
Referenced by main().
OMX_CALLBACKTYPE volumecallbacks
Initial value:
= {
  .EventHandler    = volumeEventHandler,
  .EmptyBufferDone = NULL,
  .FillBufferDone  = NULL
}
Definition at line 68 of file audio_use_case_tunnel.c.
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1