OpenMAXBellagio: audio_use_case.c File Reference
audio_use_case.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <pthread.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <string.h>
#include <dlfcn.h>
#include <dirent.h>
#include <errno.h>
#include "omxaudiodectest.h"
Macros
#define MP3_TYPE_SEL 1
#define VORBIS_TYPE_SEL 2
#define AAC_TYPE_SEL 3
#define COMPONENT_NAME_BASE "OMX.st.audio_decoder"
#define VORBIS_ROLE "audio_decoder.ogg"
#define MP3_ROLE "audio_decoder.mp3"
#define AAC_ROLE "audio_decoder.aac"
#define COMPONENT_NAME_BASE_LEN 20
#define SINK_NAME "OMX.st.alsa.alsasink"
#define FILE_READER "OMX.st.audio_filereader"
#define AUDIO_EFFECT "OMX.st.volume.component"
#define extradata_size 1024
Functions
OMX_ERRORTYPE test_OMX_ComponentNameEnum ()
OMX_ERRORTYPE test_OMX_RoleEnum (OMX_STRING component_name)
OMX_ERRORTYPE test_OMX_ComponentEnumByRole (OMX_STRING role_name)
OMX_ERRORTYPE test_OpenClose (OMX_STRING component_name)
void display_help ()
int main (int argc, char **argv)
OMX_ERRORTYPE filereaderEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
OMX_ERRORTYPE filereaderFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
OMX_ERRORTYPE audiodecEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
OMX_ERRORTYPE audiodecEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
OMX_ERRORTYPE audiodecFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
OMX_ERRORTYPE volumeEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
OMX_ERRORTYPE volumeEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
OMX_ERRORTYPE volumeFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
OMX_ERRORTYPE audiosinkEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
OMX_ERRORTYPE audiosinkEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
Variables
appPrivateType * appPriv
OMX_BUFFERHEADERTYPE * outBufferFileRead [2]
OMX_BUFFERHEADERTYPE * inBufferAudioDec [2]
OMX_BUFFERHEADERTYPE * outBufferAudioDec [2]
OMX_BUFFERHEADERTYPE * inBufferVolume [2]
OMX_BUFFERHEADERTYPE * outBufferVolume [2]
OMX_BUFFERHEADERTYPE * inBufferSink [2]
int buffer_in_size = 4096
int buffer_out_size = 4*8192
OMX_PARAM_PORTDEFINITIONTYPE paramPort
OMX_PARAM_PORTDEFINITIONTYPE decparamPort
OMX_PARAM_COMPONENTROLETYPE paramRole
OMX_AUDIO_PARAM_MP3TYPE paramMp3
OMX_AUDIO_PARAM_VORBISTYPE paramOgg
OMX_AUDIO_PARAM_PCMMODETYPE paramAudioPCM
OMX_CALLBACKTYPE audiodeccallbacks
OMX_CALLBACKTYPE audiosinkcallbacks
OMX_CALLBACKTYPE filereadercallbacks
OMX_CALLBACKTYPE volumecallbacks
FILE * fd
char * input_file =NULL
char * output_file =NULL
int selectedType = 0
FILE * outfile
int flagIsOutputExpected
int flagSetupTunnel
int flagPlaybackOn
int flagOutputReceived
int flagInputReceived
int flagIsMadRequested
int flagIsMadUsingFileReader
int flagDirect
int flagSingleOGGSelected
int flagUsingFFMpeg
int flagIsGain
Detailed Description
Test application that uses three OpenMAX components, a file reader,an audio decoder and an alsa sink. The application receives an compressed audio stream on input port from a file, decodes it and sends it to the alsa sink, or to a file or standard output. The audio formats supported are: mp3 (ffmpeg)
Copyright (C) 2007-2008 STMicroelectronics Copyright (C) 2007-2008 Nokia Corporation and/or its subsidiary(-ies).
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Date:
2008-09-11 13:48:00 +0200 (Thu, 11 Sep 2008)
Revision
Rev:
1485
Author
Author:
pankaj_sen
Definition in file audio_use_case.c.
Macro Definition Documentation
#define AAC_ROLE "audio_decoder.aac"
Definition at line 54 of file audio_use_case.c.
Referenced by main().
#define AAC_TYPE_SEL 3
Definition at line 50 of file audio_use_case.c.
#define AUDIO_EFFECT "OMX.st.volume.component"
Definition at line 58 of file audio_use_case.c.
Referenced by main().
#define COMPONENT_NAME_BASE "OMX.st.audio_decoder"
Definition at line 51 of file audio_use_case.c.
Referenced by main().
#define COMPONENT_NAME_BASE_LEN 20
Definition at line 55 of file audio_use_case.c.
#define extradata_size 1024
Definition at line 59 of file audio_use_case.c.
Referenced by filereaderEventHandler().
#define FILE_READER "OMX.st.audio_filereader"
Definition at line 57 of file audio_use_case.c.
Referenced by main().
#define MP3_ROLE "audio_decoder.mp3"
Definition at line 53 of file audio_use_case.c.
Referenced by main().
#define MP3_TYPE_SEL 1
Definition at line 48 of file audio_use_case.c.
Referenced by main().
#define SINK_NAME "OMX.st.alsa.alsasink"
Definition at line 56 of file audio_use_case.c.
Referenced by main().
#define VORBIS_ROLE "audio_decoder.ogg"
Definition at line 52 of file audio_use_case.c.
Referenced by main().
#define VORBIS_TYPE_SEL 2
Definition at line 49 of file audio_use_case.c.
Function Documentation
OMX_ERRORTYPE audiodecEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
Definition at line 1418 of file audio_use_case.c.
OMX_ERRORTYPE audiodecEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
callback prototypes for audio Decoder
Definition at line 1257 of file audio_use_case.c.
OMX_ERRORTYPE audiodecFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
Definition at line 1485 of file audio_use_case.c.
OMX_ERRORTYPE audiosinkEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
Definition at line 1742 of file audio_use_case.c.
OMX_ERRORTYPE audiosinkEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
callback prototypes for audio sink
Definition at line 1687 of file audio_use_case.c.
void display_help ()
function prototype declaration display general help
Definition at line 266 of file audio_use_case.c.
Referenced by main().
OMX_ERRORTYPE filereaderEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
Definition at line 1137 of file audio_use_case.c.
OMX_ERRORTYPE filereaderFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
Definition at line 1223 of file audio_use_case.c.
int main (int argc, char ** argv)
initializing appPriv structure
initialising openmax
file reader component name – gethandle
getting the handle of audio decoder
now set the filereader component to idle and executing state
allocation of file reader component's output buffers these two will be used as input buffers of the audio decoder component
the output buffers of file reader component will be used in the audio decoder component as input buffers
setting the input audio format in file reader
freeing all handles and deinit omx
Definition at line 296 of file audio_use_case.c.
References AAC_ROLE, AUDIO_EFFECT, appPrivateType::audiodechandle, appPrivateType::audiosinkhandle, buffer_in_size, buffer_out_size, COMPONENT_NAME_BASE, OMX_PARAM_COMPONENTROLETYPE::cRole, DEB_LEV_ERR, DEB_LEV_PARAMS, DEB_LEV_SIMPLE_SEQ, DEBUG, appPrivateType::decoderEventSem, DEFAULT_MESSAGES, display_help(), appPrivateType::eofSem, err, fd, FILE_READER, appPrivateType::filereaderEventSem, appPrivateType::filereaderhandle, flagDirect, flagInputReceived, flagIsGain, flagIsMadRequested, flagIsMadUsingFileReader, flagIsOutputExpected, flagOutputReceived, flagPlaybackOn, flagSetupTunnel, flagSingleOGGSelected, flagUsingFFMpeg, free(), input_file, malloc(), MP3_ROLE, MP3_TYPE_SEL, OMX_BUFFERHEADERTYPE::nFilledLen, OMX_BUFFERHEADERTYPE::nOffset, OMX_TIME_CONFIG_TIMESTAMPTYPE::nPortIndex, OMX_TIME_CONFIG_TIMESTAMPTYPE::nTimestamp, OMX_BS32::nValue, OMX_AllocateBuffer, OMX_CommandPortDisable, OMX_CommandPortEnable, OMX_CommandStateSet, OMX_Deinit(), OMX_EmptyThisBuffer, OMX_ErrorNone, OMX_FALSE, OMX_FillThisBuffer, OMX_FreeBuffer, OMX_FreeHandle(), OMX_GetConfig, OMX_GetExtensionIndex, OMX_GetHandle(), OMX_IndexConfigAudioVolume, OMX_IndexConfigTimePosition, OMX_IndexParamStandardComponentRole, OMX_Init(), OMX_MAX_STRINGNAME_SIZE, OMX_SendCommand, OMX_SetConfig, OMX_SetParameter, OMX_SetupTunnel(), OMX_StateExecuting, OMX_StateIdle, OMX_StateLoaded, OMX_StatePause, OMX_UseBuffer, outfile, output_file, OMX_BUFFERHEADERTYPE::pBuffer, selectedType, tsem_t::semval, setHeader(), SINK_NAME, appPrivateType::sinkEventSem, OMX_AUDIO_CONFIG_VOLUMETYPE::sVolume, test_OMX_ComponentEnumByRole(), test_OMX_ComponentNameEnum(), test_OMX_RoleEnum(), test_OpenClose(), tsem_down(), tsem_init(), tsem_reset(), appPrivateType::volumeEventSem, appPrivateType::volumehandle, and VORBIS_ROLE.
OMX_ERRORTYPE test_OMX_ComponentEnumByRole (OMX_STRING role_name)
Definition at line 189 of file audio_use_case.c.
References DEB_LEV_ERR, DEBUG, DEFAULT_MESSAGES, err, free(), malloc(), OMX_ErrorNone, and OMX_GetComponentsOfRole().
Referenced by main().
OMX_ERRORTYPE test_OMX_ComponentNameEnum ()
Definition at line 120 of file audio_use_case.c.
References DEBUG, DEFAULT_MESSAGES, err, free(), malloc(), OMX_ComponentNameEnum(), and OMX_ErrorNone.
Referenced by main().
OMX_ERRORTYPE test_OMX_RoleEnum (OMX_STRING component_name)
Definition at line 143 of file audio_use_case.c.
References DEB_LEV_ERR, DEB_LEV_SIMPLE_SEQ, DEBUG, DEFAULT_MESSAGES, err, free(), malloc(), OMX_ErrorInvalidComponentName, OMX_ErrorNone, and OMX_GetRolesOfComponent().
Referenced by main().
OMX_ERRORTYPE test_OpenClose (OMX_STRING component_name)
Definition at line 249 of file audio_use_case.c.
References appPrivateType::audiodechandle, DEB_LEV_ERR, DEBUG, DEFAULT_MESSAGES, err, OMX_ErrorNone, OMX_FreeHandle(), and OMX_GetHandle().
Referenced by main().
OMX_ERRORTYPE volumeEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
Definition at line 1590 of file audio_use_case.c.
OMX_ERRORTYPE volumeEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
callback prototypes for color converter
Definition at line 1535 of file audio_use_case.c.
OMX_ERRORTYPE volumeFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
Definition at line 1628 of file audio_use_case.c.
Variable Documentation
appPrivateType * appPriv
Definition at line 61 of file audio_use_case.c.
OMX_CALLBACKTYPE audiodeccallbacks
Initial value:
= {
  .EventHandler    = audiodecEventHandler,
  .EmptyBufferDone = audiodecEmptyBufferDone,
  .FillBufferDone  = audiodecFillBufferDone
}
Definition at line 78 of file audio_use_case.c.
OMX_CALLBACKTYPE audiosinkcallbacks
Initial value:
= {
  .EventHandler    = audiosinkEventHandler,
  .EmptyBufferDone = audiosinkEmptyBufferDone,
  .FillBufferDone  = NULL
}
Definition at line 84 of file audio_use_case.c.
Referenced by main().
int buffer_in_size = 4096
Definition at line 68 of file audio_use_case.c.
Referenced by audiodecEmptyBufferDone(), and main().
int buffer_out_size = 4*8192
Definition at line 69 of file audio_use_case.c.
Referenced by audiodecEventHandler(), and main().
OMX_PARAM_PORTDEFINITIONTYPE decparamPort
Definition at line 72 of file audio_use_case.c.
FILE* fd
Definition at line 102 of file audio_use_case.c.
Referenced by audiodecEmptyBufferDone(), main(), omx_alsasink_component_ClockPortHandleFunction(), omx_alsasink_component_Constructor(), omx_alsasink_component_Destructor(), omx_clocksrc_component_Constructor(), omx_clocksrc_component_Destructor(), omx_clocksrc_component_SetConfig(), omx_fbdev_sink_component_ClockPortHandleFunction(), omx_fbdev_sink_component_Constructor(), and omx_fbdev_sink_component_Destructor().
OMX_CALLBACKTYPE filereadercallbacks
Initial value:
= {
  .EventHandler    = filereaderEventHandler,
  .EmptyBufferDone = NULL,
  .FillBufferDone  = filereaderFillBufferDone
}
Definition at line 90 of file audio_use_case.c.
int flagDirect
Definition at line 286 of file audio_use_case.c.
Referenced by audiodecFillBufferDone(), main(), and volumeFillBufferDone().
int flagInputReceived
Definition at line 283 of file audio_use_case.c.
Referenced by main().
int flagIsGain
Definition at line 289 of file audio_use_case.c.
Referenced by main().
int flagIsMadRequested
Definition at line 284 of file audio_use_case.c.
Referenced by main().
int flagIsMadUsingFileReader
Definition at line 285 of file audio_use_case.c.
Referenced by audiodecEmptyBufferDone(), and main().
int flagIsOutputExpected
Definition at line 279 of file audio_use_case.c.
Referenced by main().
int flagOutputReceived
Definition at line 282 of file audio_use_case.c.
Referenced by audiodecFillBufferDone(), main(), and volumeFillBufferDone().
int flagPlaybackOn
Definition at line 281 of file audio_use_case.c.
Referenced by audiodecEventHandler(), audiodecFillBufferDone(), main(), and volumeFillBufferDone().
int flagSetupTunnel
Definition at line 280 of file audio_use_case.c.
Referenced by audiodecEventHandler(), audiodecFillBufferDone(), main(), and volumeFillBufferDone().
int flagSingleOGGSelected
Definition at line 287 of file audio_use_case.c.
Referenced by main().
int flagUsingFFMpeg
Definition at line 288 of file audio_use_case.c.
Referenced by audiodecEmptyBufferDone(), filereaderEventHandler(), and main().
OMX_BUFFERHEADERTYPE* inBufferAudioDec[2]
Definition at line 64 of file audio_use_case.c.
OMX_BUFFERHEADERTYPE* inBufferSink[2]
Definition at line 66 of file audio_use_case.c.
OMX_BUFFERHEADERTYPE* inBufferVolume[2]
Definition at line 65 of file audio_use_case.c.
char* input_file =NULL
Definition at line 105 of file audio_use_case.c.
Referenced by main(), and read_stdin().
OMX_BUFFERHEADERTYPE * outBufferAudioDec[2]
Definition at line 64 of file audio_use_case.c.
OMX_BUFFERHEADERTYPE* outBufferFileRead[2]
Definition at line 63 of file audio_use_case.c.
OMX_BUFFERHEADERTYPE * outBufferVolume[2]
Definition at line 65 of file audio_use_case.c.
FILE* outfile
Definition at line 108 of file audio_use_case.c.
Referenced by audiodecFillBufferDone(), main(), and volumeFillBufferDone().
char * output_file =NULL
Definition at line 105 of file audio_use_case.c.
Referenced by main(), and write_stdout().
OMX_AUDIO_PARAM_PCMMODETYPE paramAudioPCM
Definition at line 76 of file audio_use_case.c.
OMX_AUDIO_PARAM_MP3TYPE paramMp3
Definition at line 74 of file audio_use_case.c.
OMX_AUDIO_PARAM_VORBISTYPE paramOgg
Definition at line 75 of file audio_use_case.c.
OMX_PARAM_PORTDEFINITIONTYPE paramPort
Definition at line 72 of file audio_use_case.c.
OMX_PARAM_COMPONENTROLETYPE paramRole
Definition at line 73 of file audio_use_case.c.
int selectedType = 0
Definition at line 107 of file audio_use_case.c.
Referenced by main().
OMX_CALLBACKTYPE volumecallbacks
Initial value:
= {
  .EventHandler    = volumeEventHandler,
  .EmptyBufferDone = volumeEmptyBufferDone,
  .FillBufferDone  = volumeFillBufferDone
}
Definition at line 96 of file audio_use_case.c.
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1