OpenMAXBellagio: cdjpeg.h File Reference
cdjpeg.h File Reference
#include "jinclude.h"
#include "jpeglib.h"
#include "jerror.h"
#include "cderror.h"
Data Structures
struct cjpeg_source_struct
struct djpeg_dest_struct
struct cdjpeg_progress_mgr
Macros
#define JPEG_CJPEG_DJPEG /* define proper options in jconfig.h */
#define JPEG_INTERNAL_OPTIONS /* cjpeg.c,djpeg.c need to see xxx_SUPPORTED */
#define READ_BINARY "rb"
#define WRITE_BINARY "wb"
#define EXIT_FAILURE 1
#define EXIT_SUCCESS 0
#define EXIT_WARNING 2
Typedefs
typedef struct
cjpeg_source_struct * cjpeg_source_ptr
typedef struct djpeg_dest_struct * djpeg_dest_ptr
typedef struct
cdjpeg_progress_mgr * cd_progress_ptr
Functions
cjpeg_source_ptr jinit_read_bmp (j_compress_ptr cinfo)
djpeg_dest_ptr jinit_write_bmp (j_decompress_ptr cinfo, boolean is_os2)
cjpeg_source_ptr jinit_read_gif (j_compress_ptr cinfo)
djpeg_dest_ptr jinit_write_gif (j_decompress_ptr cinfo)
cjpeg_source_ptr jinit_read_ppm (j_compress_ptr cinfo)
djpeg_dest_ptr jinit_write_ppm (j_decompress_ptr cinfo)
cjpeg_source_ptr jinit_read_rle (j_compress_ptr cinfo)
djpeg_dest_ptr jinit_write_rle (j_decompress_ptr cinfo)
cjpeg_source_ptr jinit_read_targa (j_compress_ptr cinfo)
djpeg_dest_ptr jinit_write_targa (j_decompress_ptr cinfo)
boolean read_quant_tables (j_compress_ptr cinfo, char *filename, boolean force_baseline)
boolean read_scan_script (j_compress_ptr cinfo, char *filename)
boolean set_quality_ratings (j_compress_ptr cinfo, char *arg, boolean force_baseline)
boolean set_quant_slots (j_compress_ptr cinfo, char *arg)
boolean set_sample_factors (j_compress_ptr cinfo, char *arg)
void read_color_map (j_decompress_ptr cinfo, FILE *infile)
void enable_signal_catcher (j_common_ptr cinfo)
void start_progress_monitor (j_common_ptr cinfo, cd_progress_ptr progress)
void end_progress_monitor (j_common_ptr cinfo)
boolean keymatch (char *arg, const char *keyword, int minchars)
FILE * read_stdin (void)
FILE * write_stdout (void)
Macro Definition Documentation
#define EXIT_FAILURE 1
Definition at line 172 of file cdjpeg.h.
Referenced by jinit_read_gif(), main(), read_stdin(), and write_stdout().
#define EXIT_SUCCESS 0
Definition at line 178 of file cdjpeg.h.
Referenced by main().
#define EXIT_WARNING 2
Definition at line 185 of file cdjpeg.h.
Referenced by main().
#define JPEG_CJPEG_DJPEG /* define proper options in jconfig.h */
Definition at line 12 of file cdjpeg.h.
#define JPEG_INTERNAL_OPTIONS /* cjpeg.c,djpeg.c need to see xxx_SUPPORTED */
Definition at line 13 of file cdjpeg.h.
#define READ_BINARY "rb"
Definition at line 166 of file cdjpeg.h.
Referenced by main(), and read_stdin().
#define WRITE_BINARY "wb"
Definition at line 167 of file cdjpeg.h.
Referenced by main(), and write_stdout().
Typedef Documentation
typedef struct cdjpeg_progress_mgr* cd_progress_ptr
Definition at line 89 of file cdjpeg.h.
typedef struct cjpeg_source_struct* cjpeg_source_ptr
Definition at line 24 of file cdjpeg.h.
typedef struct djpeg_dest_struct* djpeg_dest_ptr
Definition at line 45 of file cdjpeg.h.
Function Documentation
void enable_signal_catcher (j_common_ptr cinfo)
Referenced by main(), and omx_jpegenc_component_Init().
void end_progress_monitor (j_common_ptr cinfo)
Referenced by main().
cjpeg_source_ptr jinit_read_bmp (j_compress_ptr cinfo)
Definition at line 423 of file libjpeg-6c/rdbmp.c.
References _bmp_source_struct::cinfo, cjpeg_source_struct::finish_input, _bmp_source_struct::pub, SIZEOF, and cjpeg_source_struct::start_input.
cjpeg_source_ptr jinit_read_gif (j_compress_ptr cinfo)
Definition at line 31 of file rdgif.c.
References EXIT_FAILURE.
cjpeg_source_ptr jinit_read_ppm (j_compress_ptr cinfo)
Definition at line 443 of file rdppm.c.
References cjpeg_source_struct::finish_input, JPOOL_IMAGE, ppm_source_struct::pub, SIZEOF, and cjpeg_source_struct::start_input.
cjpeg_source_ptr jinit_read_rle (j_compress_ptr cinfo)
cjpeg_source_ptr jinit_read_targa (j_compress_ptr cinfo)
Definition at line 484 of file rdtarga.c.
References _tga_source_struct::cinfo, cjpeg_source_struct::finish_input, _tga_source_struct::pub, SIZEOF, and cjpeg_source_struct::start_input.
djpeg_dest_ptr jinit_write_bmp (j_decompress_ptr cinfo, boolean is_os2)
Definition at line 390 of file libjpeg-6c/wrbmp.c.
References djpeg_dest_struct::buffer, djpeg_dest_struct::buffer_height, bmp_dest_struct::cur_output_row, bmp_dest_struct::data_width, ERREXIT, FALSE, djpeg_dest_struct::finish_output, bmp_dest_struct::is_os2, JCS_GRAYSCALE, JCS_RGB, jpeg_calc_output_dimensions(), JPOOL_IMAGE, bmp_dest_struct::pad_bytes, bmp_dest_struct::pub, djpeg_dest_struct::put_pixel_rows, bmp_dest_struct::row_width, SIZEOF, djpeg_dest_struct::start_output, cdjpeg_progress_mgr::total_extra_passes, and bmp_dest_struct::whole_image.
Referenced by main(), omx_jpegdec_component_BufferMgmtCallback(), and omx_jpegdec_component_BufferMgmtFunction().
djpeg_dest_ptr jinit_write_gif (j_decompress_ptr cinfo)
Definition at line 360 of file wrgif.c.
References djpeg_dest_struct::buffer, djpeg_dest_struct::buffer_height, gif_dest_struct::cinfo, ERREXIT, djpeg_dest_struct::finish_output, JCS_GRAYSCALE, JCS_RGB, jpeg_calc_output_dimensions(), JPOOL_IMAGE, gif_dest_struct::pub, djpeg_dest_struct::put_pixel_rows, SIZEOF, djpeg_dest_struct::start_output, and TRUE.
Referenced by main().
djpeg_dest_ptr jinit_write_ppm (j_decompress_ptr cinfo)
Definition at line 219 of file wrppm.c.
References BITS_IN_JSAMPLE, djpeg_dest_struct::buffer, djpeg_dest_struct::buffer_height, ppm_dest_struct::buffer_width, BYTESPERSAMPLE, djpeg_dest_struct::finish_output, ppm_dest_struct::iobuffer, JCS_GRAYSCALE, jpeg_calc_output_dimensions(), JPOOL_IMAGE, ppm_dest_struct::pixrow, ppm_dest_struct::pub, djpeg_dest_struct::put_pixel_rows, ppm_dest_struct::samples_per_row, SIZEOF, and djpeg_dest_struct::start_output.
Referenced by main().
djpeg_dest_ptr jinit_write_rle (j_decompress_ptr cinfo)
Referenced by main().
djpeg_dest_ptr jinit_write_targa (j_decompress_ptr cinfo)
Definition at line 225 of file wrtarga.c.
References djpeg_dest_struct::buffer, djpeg_dest_struct::buffer_height, tga_dest_struct::buffer_width, djpeg_dest_struct::finish_output, tga_dest_struct::iobuffer, jpeg_calc_output_dimensions(), JPOOL_IMAGE, tga_dest_struct::pub, SIZEOF, and djpeg_dest_struct::start_output.
Referenced by main().
boolean keymatch (char * arg, const char * keyword, int minchars)
Definition at line 122 of file cdjpeg.c.
References FALSE, and TRUE.
Referenced by main().
void read_color_map (j_decompress_ptr cinfo, FILE * infile)
Definition at line 231 of file rdcolmap.c.
References ERREXIT, JERR_BAD_CMAP_FILE, and JPOOL_IMAGE.
boolean read_quant_tables (j_compress_ptr cinfo, char * filename, boolean force_baseline)
Definition at line 74 of file rdswitch.c.
References DCTSIZE2, FALSE, jpeg_add_quant_table(), NUM_QUANT_TBLS, and TRUE.
boolean read_scan_script (j_compress_ptr cinfo, char * filename)
Definition at line 159 of file rdswitch.c.
References jpeg_scan_info::Ah, jpeg_scan_info::Al, jpeg_scan_info::component_index, jpeg_scan_info::comps_in_scan, DCTSIZE2, FALSE, JPOOL_IMAGE, MAX_COMPS_IN_SCAN, MAX_SCANS, MEMCOPY, jpeg_scan_info::Se, SIZEOF, jpeg_scan_info::Ss, and TRUE.
FILE* read_stdin (void)
Definition at line 149 of file cdjpeg.c.
References EXIT_FAILURE, input_file, and READ_BINARY.
Referenced by main().
boolean set_quality_ratings (j_compress_ptr cinfo, char * arg, boolean force_baseline)
Definition at line 267 of file rdswitch.c.
References FALSE, jpeg_default_qtables(), jpeg_quality_scaling(), NUM_QUANT_TBLS, and TRUE.
boolean set_quant_slots (j_compress_ptr cinfo, char * arg)
Definition at line 299 of file rdswitch.c.
References FALSE, MAX_COMPONENTS, NUM_QUANT_TBLS, and TRUE.
boolean set_sample_factors (j_compress_ptr cinfo, char * arg)
Definition at line 334 of file rdswitch.c.
References FALSE, MAX_COMPONENTS, and TRUE.
void start_progress_monitor (j_common_ptr cinfo, cd_progress_ptr progress)
Referenced by main().
FILE* write_stdout (void)
Definition at line 167 of file cdjpeg.c.
References EXIT_FAILURE, output_file, and WRITE_BINARY.
Referenced by main().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1