OpenMAXBellagio: cdjpeg.c File Reference
cdjpeg.c File Reference
#include "cdjpeg.h"
#include <ctype.h>
Functions
boolean keymatch (char *arg, const char *keyword, int minchars)
FILE * read_stdin (void)
FILE * write_stdout (void)
Function Documentation
boolean keymatch (char * arg, const char * keyword, int minchars)
Definition at line 122 of file cdjpeg.c.
References FALSE, and TRUE.
Referenced by main().
FILE* read_stdin (void)
Definition at line 149 of file cdjpeg.c.
References EXIT_FAILURE, input_file, and READ_BINARY.
Referenced by main().
FILE* write_stdout (void)
Definition at line 167 of file cdjpeg.c.
References EXIT_FAILURE, output_file, and WRITE_BINARY.
Referenced by main().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1