OpenMAXBellagio: common.h File Reference
common.h File Reference
Data Structures
struct nameList
Typedefs
typedef struct nameList nameList
Functions
char * registryGetFilename (void)
Get registry filename.
Detailed Description
OpenMAX Integration Layer Core. This library implements the OpenMAX core responsible for environment setup, component tunneling and communication.
Copyright (C) 2007, 2008 STMicroelectronics Copyright (C) 2007-2008 Nokia Corporation and/or its subsidiary(-ies).
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Date:
2008-09-11 15:28:59 +0200 (Thu, 11 Sep 2008)
Revision
Rev:
614
Author
Author:
gsent
Definition in file common.h.
Typedef Documentation
typedef struct nameList nameList
Function Documentation
char* registryGetFilename (void)
Get registry filename.
Definition at line 44 of file common.c.
References DATA_HOME_DIR, malloc(), REGISTRY_DIR, and REGISTRY_FILENAME.
Referenced by BOSA_ST_InitComponentLoader(), and main().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1