OpenMAXBellagio: omxaudiomixertest.c File Reference
components_symbian/symbianaudiomixer/src/omxaudiomixertest.c File Reference
#include "omxaudiomixertest.h"
#include "ctype.h"
Macros
#define SINK_NAME "OMX.nokia.outputstream.component"
#define BUFFER_COUNT_ACTUAL 2
#define FRAME_SIZE 1152*2*2
Functions
int main (int argc, char **argv)
OMX_ERRORTYPE audiomixerEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_IN OMX_PTR pEventData)
OMX_ERRORTYPE audiomixerEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
OMX_ERRORTYPE audiomixerFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
OMX_ERRORTYPE audiosinkEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
OMX_ERRORTYPE audiosinkEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
Variables
appPrivateType * appPriv
int fd = 0
int fd1 =0
unsigned int filesize
unsigned int filesize1
int flagIsGain [4]
int flagPlaybackOn
int flagSetupTunnel
int flagSampleRate
int flagChannel
char * input_file [2]
char * output_file
OMX_BUFFERHEADERTYPE * inBuffer [4]
OMX_BUFFERHEADERTYPE * outBuffer [2]
OMX_BUFFERHEADERTYPE * inBufferSink [2]
Macro Definition Documentation
#define BUFFER_COUNT_ACTUAL 2
Definition at line 31 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
Referenced by main().
#define FRAME_SIZE 1152*2*2
Definition at line 32 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
Referenced by audiomixerEmptyBufferDone(), and main().
#define SINK_NAME "OMX.nokia.outputstream.component"
Definition at line 30 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
Referenced by main().
Function Documentation
OMX_ERRORTYPE audiomixerEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
Definition at line 411 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
References DEB_LEV_FULL_SEQ, DEB_LEV_SIMPLE_SEQ, DEBUG, appPrivateType::eofSem, err, fd, fd1, filesize, filesize1, FRAME_SIZE, OMX_BUFFERFLAG_EOS, OMX_EmptyThisBuffer, OMX_ErrorNone, OMX_FALSE, OMX_TRUE, and tsem_up().
Referenced by main().
OMX_ERRORTYPE audiomixerEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_IN OMX_PTR pEventData)
Definition at line 361 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
References DEB_LEV_SIMPLE_SEQ, DEBUG, appPrivateType::eofSem, appPrivateType::eventSem, OMX_BUFFERFLAG_EOS, OMX_CommandPortDisable, OMX_CommandPortEnable, OMX_CommandStateSet, OMX_ErrorNone, OMX_EventBufferFlag, OMX_EventCmdComplete, OMX_StateExecuting, OMX_StateIdle, OMX_StateInvalid, OMX_StateLoaded, OMX_StatePause, OMX_StateWaitForResources, and tsem_up().
Referenced by main().
OMX_ERRORTYPE audiomixerFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
Definition at line 492 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
References appPrivateType::audiosinkhandle, DEB_LEV_ERR, DEB_LEV_FULL_SEQ, DEBUG, err, flagPlaybackOn, OMX_BUFFERHEADERTYPE::nFilledLen, OMX_EmptyThisBuffer, OMX_ErrorNone, OMX_FillThisBuffer, and OMX_BUFFERHEADERTYPE::pBuffer.
Referenced by main().
OMX_ERRORTYPE audiosinkEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
Definition at line 583 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
References DEB_LEV_ERR, DEB_LEV_FULL_SEQ, DEB_LEV_PARAMS, DEBUG, DEFAULT_MESSAGES, appPrivateType::eofSem, err, appPrivateType::handle, OMX_BUFFERHEADERTYPE::nFilledLen, OMX_ErrorNone, OMX_FillThisBuffer, OMX_BUFFERHEADERTYPE::pBuffer, and tsem_up().
Referenced by main().
OMX_ERRORTYPE audiosinkEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
Callbacks implementation of the audio source component
Definition at line 538 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
References DEB_LEV_SIMPLE_SEQ, DEBUG, OMX_CommandPortDisable, OMX_CommandPortEnable, OMX_CommandStateSet, OMX_ErrorNone, OMX_StateExecuting, OMX_StateIdle, OMX_StateInvalid, OMX_StateLoaded, OMX_StatePause, OMX_StateWaitForResources, appPrivateType::sinkEventSem, and tsem_up().
Referenced by main().
int main (int argc, char ** argv)
Ask the core for a handle to the audio mixer component
Get the number of ports
Definition at line 60 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
References audiomixerEmptyBufferDone(), audiomixerEventHandler(), audiomixerFillBufferDone(), audiosinkcallbacks, audiosinkEmptyBufferDone(), audiosinkEventHandler(), appPrivateType::audiosinkhandle, BUFFER_COUNT_ACTUAL, BUFFER_IN_SIZE, callbacks, appPrivateType::condition, DEB_LEV_ERR, DEB_LEV_PARAMS, DEB_LEV_SIMPLE_SEQ, DEBUG, DEFAULT_MESSAGES, OMX_CALLBACKTYPE::EmptyBufferDone, appPrivateType::eofSem, err, OMX_CALLBACKTYPE::EventHandler, appPrivateType::eventSem, fd, fd1, filesize, filesize1, OMX_CALLBACKTYPE::FillBufferDone, flagIsGain, flagPlaybackOn, flagSetupTunnel, FRAME_SIZE, free(), appPrivateType::handle, input_file, malloc(), appPrivateType::mutex, OMX_PARAM_PORTDEFINITIONTYPE::nBufferCountActual, OMX_AUDIO_PARAM_PCMMODETYPE::nChannels, OMX_BUFFERHEADERTYPE::nFilledLen, OMX_PARAM_PORTDEFINITIONTYPE::nPortIndex, OMX_AUDIO_PARAM_PCMMODETYPE::nPortIndex, OMX_AUDIO_CONFIG_VOLUMETYPE::nPortIndex, OMX_PORT_PARAM_TYPE::nPorts, OMX_AUDIO_PARAM_PCMMODETYPE::nSamplingRate, OMX_BS32::nValue, OMX_AllocateBuffer, OMX_CommandPortDisable, OMX_CommandStateSet, OMX_EmptyThisBuffer, OMX_ErrorNone, OMX_FALSE, OMX_FreeBuffer, OMX_FreeHandle(), OMX_GetConfig, OMX_GetHandle(), OMX_GetParameter, OMX_IndexConfigAudioVolume, OMX_IndexParamAudioInit, OMX_IndexParamAudioPcm, OMX_IndexParamPortDefinition, OMX_Init(), OMX_SendCommand, OMX_SetConfig, OMX_SetParameter, OMX_SetupTunnel(), OMX_StateExecuting, OMX_StateIdle, OMX_StateLoaded, OMX_TRUE, setHeader(), SINK_NAME, appPrivateType::sinkEventSem, OMX_AUDIO_CONFIG_VOLUMETYPE::sVolume, tsem_down(), and tsem_init().
Variable Documentation
appPrivateType* appPriv
Definition at line 45 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
int fd = 0
Definition at line 46 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
Referenced by audiomixerEmptyBufferDone(), and main().
int fd1 =0
Definition at line 46 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
Referenced by audiomixerEmptyBufferDone(), and main().
unsigned int filesize
Definition at line 47 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
Referenced by audiomixerEmptyBufferDone(), and main().
unsigned int filesize1
Definition at line 47 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
Referenced by audiomixerEmptyBufferDone(), and main().
int flagChannel
Definition at line 52 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
int flagIsGain[4]
Definition at line 48 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
Referenced by main().
int flagPlaybackOn
Definition at line 49 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
Referenced by audiomixerFillBufferDone(), and main().
int flagSampleRate
Definition at line 51 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
int flagSetupTunnel
Definition at line 50 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
Referenced by main().
OMX_BUFFERHEADERTYPE* inBuffer[4]
Definition at line 56 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
OMX_BUFFERHEADERTYPE * inBufferSink[2]
Definition at line 56 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
char* input_file[2]
Definition at line 53 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
Referenced by main().
OMX_BUFFERHEADERTYPE * outBuffer[2]
Definition at line 56 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
char * output_file
Definition at line 53 of file components_symbian/symbianaudiomixer/src/omxaudiomixertest.c.
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1