OpenMAXBellagio: djpeg.c File Reference
djpeg.c File Reference
#include "cdjpeg.h"
#include "jversion.h"
#include <ctype.h>
#include "cderror.h"
Macros
#define JMESSAGE(code, string) string ,
#define DEFAULT_FMT FMT_PPM
Enumerations
enum IMAGE_FORMATS {
FMT_BMP, FMT_GIF, FMT_OS2, FMT_PPM,
FMT_RLE, FMT_TARGA, FMT_TIFF, FMT_BMP,
FMT_GIF, FMT_OS2, FMT_PPM, FMT_RLE,
FMT_TARGA, FMT_TIFF, FMT_BMP, FMT_GIF,
FMT_OS2, FMT_PPM, FMT_RLE, FMT_TARGA,
FMT_TIFF
}
Functions
int main (int argc, char **argv)
Macro Definition Documentation
#define DEFAULT_FMT FMT_PPM
Definition at line 70 of file djpeg.c.
#define JMESSAGE (code, string) string ,
Definition at line 44 of file djpeg.c.
Enumeration Type Documentation
enum IMAGE_FORMATS
Enumerator
FMT_BMP
FMT_GIF
FMT_OS2
FMT_PPM
FMT_RLE
FMT_TARGA
FMT_TIFF
FMT_BMP
FMT_GIF
FMT_OS2
FMT_PPM
FMT_RLE
FMT_TARGA
FMT_TIFF
FMT_BMP
FMT_GIF
FMT_OS2
FMT_PPM
FMT_RLE
FMT_TARGA
FMT_TIFF
Definition at line 59 of file djpeg.c.
Function Documentation
int main (int argc, char ** argv)
Definition at line 424 of file djpeg.c.
References jpeg_error_mgr::addon_message_table, djpeg_dest_struct::buffer, djpeg_dest_struct::buffer_height, jpeg_progress_mgr::completed_passes, enable_signal_catcher(), end_progress_monitor(), jpeg_decompress_struct::err, ERREXIT, EXIT_FAILURE, EXIT_SUCCESS, EXIT_WARNING, FALSE, djpeg_dest_struct::finish_output, jpeg_error_mgr::first_addon_message, FMT_BMP, FMT_GIF, FMT_OS2, FMT_PPM, FMT_RLE, FMT_TARGA, input_file, JERR_UNSUPPORTED_FORMAT, jinit_write_bmp(), jinit_write_gif(), jinit_write_ppm(), jinit_write_rle(), jinit_write_targa(), JMSG_FIRSTADDONCODE, JMSG_LASTADDONCODE, JPEG_APP0, JPEG_COM, jpeg_create_decompress, jpeg_destroy_decompress(), jpeg_finish_decompress(), jpeg_read_header(), jpeg_read_scanlines(), jpeg_set_marker_processor(), jpeg_start_decompress(), jpeg_std_error(), jpeg_stdio_src(), jpeg_error_mgr::last_addon_message, jpeg_error_mgr::num_warnings, djpeg_dest_struct::output_file, output_file, cdjpeg_progress_mgr::pub, djpeg_dest_struct::put_pixel_rows, READ_BINARY, read_stdin(), djpeg_dest_struct::start_output, start_progress_monitor(), jpeg_progress_mgr::total_passes, TRUE, WRITE_BINARY, and write_stdout().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1