OpenMAXBellagio: jcparam.c File Reference
jcparam.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Macros
#define JPEG_INTERNALS
#define SET_COMP(index, id, hsamp, vsamp, quant, dctbl, actbl)
Functions
void jpeg_add_quant_table (j_compress_ptr cinfo, int which_tbl, const unsigned int *basic_table, int scale_factor, boolean force_baseline)
void jpeg_default_qtables (j_compress_ptr cinfo, boolean force_baseline)
void jpeg_set_linear_quality (j_compress_ptr cinfo, int scale_factor, boolean force_baseline)
int jpeg_quality_scaling (int quality)
void jpeg_set_quality (j_compress_ptr cinfo, int quality, boolean force_baseline)
void jpeg_set_defaults (j_compress_ptr cinfo)
void jpeg_default_colorspace (j_compress_ptr cinfo)
void jpeg_set_colorspace (j_compress_ptr cinfo, J_COLOR_SPACE colorspace)
void jpeg_simple_progression (j_compress_ptr cinfo)
Macro Definition Documentation
#define JPEG_INTERNALS
Definition at line 13 of file jcparam.c.
#define SET_COMP (index, id, hsamp, vsamp, quant, dctbl, actbl)
Value:
(compptr = &cinfo->comp_info[index], \
   compptr->component_id = (id), \
   compptr->h_samp_factor = (hsamp), \
   compptr->v_samp_factor = (vsamp), \
   compptr->quant_tbl_no = (quant), \
   compptr->dc_tbl_no = (dctbl), \
   compptr->ac_tbl_no = (actbl) )
Referenced by jpeg_set_colorspace().
Function Documentation
void jpeg_add_quant_table (j_compress_ptr cinfo, int which_tbl, const unsigned int * basic_table, int scale_factor, boolean force_baseline)
Definition at line 23 of file jcparam.c.
References CSTATE_START, DCTSIZE2, ERREXIT1, FALSE, JERR_BAD_STATE, JERR_DQT_INDEX, jpeg_alloc_quant_table(), and NUM_QUANT_TBLS.
Referenced by jpeg_default_qtables(), jpeg_set_linear_quality(), and read_quant_tables().
void jpeg_default_colorspace (j_compress_ptr cinfo)
Definition at line 377 of file jcparam.c.
References ERREXIT, JCS_CMYK, JCS_GRAYSCALE, JCS_RGB, JCS_UNKNOWN, JCS_YCbCr, JCS_YCCK, JERR_BAD_IN_COLORSPACE, and jpeg_set_colorspace().
Referenced by jpeg_set_defaults(), main(), and omx_jpegenc_component_BufferMgmtFunction().
void jpeg_default_qtables (j_compress_ptr cinfo, boolean force_baseline)
Definition at line 90 of file jcparam.c.
References jpeg_add_quant_table().
Referenced by set_quality_ratings().
int jpeg_quality_scaling (int quality)
Definition at line 122 of file jcparam.c.
Referenced by jpeg_set_quality(), and set_quality_ratings().
void jpeg_set_colorspace (j_compress_ptr cinfo, J_COLOR_SPACE colorspace)
Definition at line 409 of file jcparam.c.
References compptr, CSTATE_START, ERREXIT, ERREXIT1, ERREXIT2, FALSE, JCS_CMYK, JCS_GRAYSCALE, JCS_RGB, JCS_UNKNOWN, JCS_YCbCr, JCS_YCCK, JERR_BAD_J_COLORSPACE, JERR_BAD_STATE, JERR_COMPONENT_COUNT, MAX_COMPONENTS, SET_COMP, and TRUE.
Referenced by jpeg_copy_critical_parameters(), and jpeg_default_colorspace().
void jpeg_set_defaults (j_compress_ptr cinfo)
Definition at line 284 of file jcparam.c.
References BITS_IN_JSAMPLE, CSTATE_START, ERREXIT1, FALSE, JDCT_DEFAULT, JERR_BAD_STATE, jpeg_default_colorspace(), jpeg_set_quality(), JPOOL_PERMANENT, MAX_COMPONENTS, NUM_ARITH_TBLS, SIZEOF, and TRUE.
Referenced by jpeg_copy_critical_parameters(), main(), and omx_jpegenc_component_Init().
void jpeg_set_linear_quality (j_compress_ptr cinfo, int scale_factor, boolean force_baseline)
Definition at line 105 of file jcparam.c.
References jpeg_add_quant_table().
Referenced by jpeg_set_quality().
void jpeg_set_quality (j_compress_ptr cinfo, int quality, boolean force_baseline)
Definition at line 148 of file jcparam.c.
References jpeg_quality_scaling(), and jpeg_set_linear_quality().
Referenced by jpeg_set_defaults().
void jpeg_simple_progression (j_compress_ptr cinfo)
Definition at line 555 of file jcparam.c.
References CSTATE_START, ERREXIT1, JCS_YCbCr, JERR_BAD_STATE, JPOOL_PERMANENT, MAX, MAX_COMPS_IN_SCAN, and SIZEOF.
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1