OpenMAXBellagio: jctrans.c File Reference
jctrans.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Data Structures
struct my_coef_controller
Macros
#define JPEG_INTERNALS
Typedefs
typedef my_coef_controller * my_coef_ptr
Functions
void jpeg_write_coefficients (j_compress_ptr cinfo, jvirt_barray_ptr *coef_arrays)
void jpeg_copy_critical_parameters (j_decompress_ptr srcinfo, j_compress_ptr dstinfo)
Macro Definition Documentation
#define JPEG_INTERNALS
Definition at line 13 of file jctrans.c.
Typedef Documentation
typedef my_coef_controller* my_coef_ptr
Definition at line 216 of file jctrans.c.
Function Documentation
void jpeg_copy_critical_parameters (j_decompress_ptr srcinfo, j_compress_ptr dstinfo)
Definition at line 63 of file jctrans.c.
References jpeg_component_info::component_id, CSTATE_START, DCTSIZE2, ERREXIT1, ERREXIT2, FALSE, jpeg_component_info::h_samp_factor, JERR_BAD_STATE, JERR_COMPONENT_COUNT, JERR_MISMATCHED_QUANT_TABLE, JERR_NO_QUANT_TABLE, jpeg_alloc_quant_table(), jpeg_set_colorspace(), jpeg_set_defaults(), MAX_COMPONENTS, MEMCOPY, NUM_QUANT_TBLS, jpeg_component_info::quant_table, jpeg_component_info::quant_tbl_no, JQUANT_TBL::quantval, SIZEOF, and jpeg_component_info::v_samp_factor.
Referenced by main().
void jpeg_write_coefficients (j_compress_ptr cinfo, jvirt_barray_ptr * coef_arrays)
Definition at line 38 of file jctrans.c.
References CSTATE_START, CSTATE_WRCOEFS, ERREXIT1, FALSE, JERR_BAD_STATE, and jpeg_suppress_tables().
Referenced by main().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1