OpenMAXBellagio: jdapimin.c File Reference
jdapimin.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Macros
#define JPEG_INTERNALS
Functions
void jpeg_CreateDecompress (j_decompress_ptr cinfo, int version, size_t structsize)
void jpeg_destroy_decompress (j_decompress_ptr cinfo)
void jpeg_abort_decompress (j_decompress_ptr cinfo)
int jpeg_read_header (j_decompress_ptr cinfo, boolean require_image)
int jpeg_consume_input (j_decompress_ptr cinfo)
boolean jpeg_input_complete (j_decompress_ptr cinfo)
boolean jpeg_has_multiple_scans (j_decompress_ptr cinfo)
boolean jpeg_finish_decompress (j_decompress_ptr cinfo)
Macro Definition Documentation
#define JPEG_INTERNALS
Definition at line 19 of file jdapimin.c.
Function Documentation
void jpeg_abort_decompress (j_decompress_ptr cinfo)
Definition at line 103 of file jdapimin.c.
References jpeg_abort().
int jpeg_consume_input (j_decompress_ptr cinfo)
Definition at line 287 of file jdapimin.c.
References DSTATE_BUFIMAGE, DSTATE_BUFPOST, DSTATE_INHEADER, DSTATE_PRELOAD, DSTATE_PRESCAN, DSTATE_RAW_OK, DSTATE_READY, DSTATE_SCANNING, DSTATE_START, DSTATE_STOPPING, ERREXIT1, JERR_BAD_STATE, JPEG_REACHED_SOS, and JPEG_SUSPENDED.
Referenced by jpeg_read_header().
void jpeg_CreateDecompress (j_decompress_ptr cinfo, int version, size_t structsize)
Definition at line 30 of file jdapimin.c.
References DSTATE_START, err, ERREXIT2, jpeg_common_struct::global_state, jpeg_error_mgr::i, JERR_BAD_LIB_VERSION, JERR_BAD_STRUCT_SIZE, jinit_input_controller(), jinit_marker_reader(), jinit_memory_mgr(), JPEG_LIB_VERSION, MEMZERO, NUM_HUFF_TBLS, NUM_QUANT_TBLS, jpeg_common_struct::progress, SIZEOF, and TRUE.
void jpeg_destroy_decompress (j_decompress_ptr cinfo)
Definition at line 91 of file jdapimin.c.
References jpeg_destroy().
Referenced by main(), omx_jpegdec_component_BufferMgmtCallback(), and omx_jpegdec_component_BufferMgmtFunction().
boolean jpeg_finish_decompress (j_decompress_ptr cinfo)
Definition at line 369 of file jdapimin.c.
References DSTATE_BUFIMAGE, DSTATE_RAW_OK, DSTATE_SCANNING, DSTATE_STOPPING, ERREXIT, ERREXIT1, FALSE, JERR_BAD_STATE, JERR_TOO_LITTLE_DATA, jpeg_abort(), JPEG_SUSPENDED, and TRUE.
Referenced by main(), omx_jpegdec_component_BufferMgmtCallback(), and omx_jpegdec_component_BufferMgmtFunction().
boolean jpeg_has_multiple_scans (j_decompress_ptr cinfo)
Definition at line 349 of file jdapimin.c.
References DSTATE_READY, DSTATE_STOPPING, ERREXIT1, and JERR_BAD_STATE.
boolean jpeg_input_complete (j_decompress_ptr cinfo)
Definition at line 334 of file jdapimin.c.
References DSTATE_START, DSTATE_STOPPING, ERREXIT1, and JERR_BAD_STATE.
int jpeg_read_header (j_decompress_ptr cinfo, boolean require_image)
Definition at line 241 of file jdapimin.c.
References DSTATE_INHEADER, DSTATE_START, ERREXIT, ERREXIT1, JERR_BAD_STATE, JERR_NO_IMAGE, jpeg_abort(), jpeg_consume_input(), JPEG_HEADER_OK, JPEG_HEADER_TABLES_ONLY, JPEG_REACHED_EOI, JPEG_REACHED_SOS, and JPEG_SUSPENDED.
Referenced by main(), omx_jpegdec_component_BufferMgmtCallback(), and omx_jpegdec_component_BufferMgmtFunction().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1