OpenMAXBellagio: jdmaster.c File Reference
jdmaster.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
Data Structures
struct my_decomp_master
Macros
#define JPEG_INTERNALS
Typedefs
typedef my_decomp_master * my_master_ptr
Functions
void jpeg_calc_output_dimensions (j_decompress_ptr cinfo)
void jpeg_new_colormap (j_decompress_ptr cinfo)
void jinit_master_decompress (j_decompress_ptr cinfo)
Macro Definition Documentation
#define JPEG_INTERNALS
Definition at line 14 of file jdmaster.c.
Typedef Documentation
typedef my_decomp_master* my_master_ptr
Definition at line 35 of file jdmaster.c.
Function Documentation
void jinit_master_decompress (j_decompress_ptr cinfo)
Definition at line 646 of file jdmaster.c.
References FALSE, JPOOL_IMAGE, my_comp_master::pub, and SIZEOF.
Referenced by jpeg_start_decompress().
void jpeg_calc_output_dimensions (j_decompress_ptr cinfo)
Definition at line 87 of file jdmaster.c.
References compptr, jpeg_component_info::DCT_h_scaled_size, jpeg_component_info::DCT_v_scaled_size, DCTSIZE, jpeg_component_info::downsampled_height, jpeg_component_info::downsampled_width, DSTATE_READY, ERREXIT1, jpeg_component_info::h_samp_factor, JCS_CMYK, JCS_GRAYSCALE, JCS_RGB, JCS_YCbCr, JCS_YCCK, jdiv_round_up(), JERR_BAD_STATE, and jpeg_component_info::v_samp_factor.
Referenced by jinit_write_bmp(), jinit_write_gif(), jinit_write_ppm(), and jinit_write_targa().
void jpeg_new_colormap (j_decompress_ptr cinfo)
Definition at line 618 of file jdmaster.c.
References DSTATE_BUFIMAGE, ERREXIT, ERREXIT1, FALSE, JERR_BAD_STATE, JERR_MODE_CHANGE, and my_comp_master::pub.
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1