OpenMAXBellagio: jmemmgr.c File Reference
jmemmgr.c File Reference
#include "jinclude.h"
#include "jpeglib.h"
#include "jmemsys.h"
Data Structures
union small_pool_struct
union large_pool_struct
struct my_memory_mgr
struct jvirt_sarray_control
struct jvirt_barray_control
Macros
#define JPEG_INTERNALS
#define AM_MEMORY_MANAGER /* we define jvirt_Xarray_control structs */
#define ALIGN_TYPE double
#define MIN_SLOP 50 /* greater than 0 to avoid futile looping */
Typedefs
typedef union small_pool_struct * small_pool_ptr
typedef union small_pool_struct small_pool_hdr
typedef union large_pool_struct * large_pool_ptr
typedef union large_pool_struct large_pool_hdr
typedef my_memory_mgr * my_mem_ptr
Functions
void jinit_memory_mgr (j_common_ptr cinfo)
Macro Definition Documentation
#define ALIGN_TYPE double
Definition at line 73 of file jmemmgr.c.
Referenced by jinit_memory_mgr().
#define AM_MEMORY_MANAGER /* we define jvirt_Xarray_control structs */
Definition at line 28 of file jmemmgr.c.
#define JPEG_INTERNALS
Definition at line 27 of file jmemmgr.c.
#define MIN_SLOP 50 /* greater than 0 to avoid futile looping */
Definition at line 253 of file jmemmgr.c.
Typedef Documentation
typedef union large_pool_struct large_pool_hdr
typedef union large_pool_struct* large_pool_ptr
Definition at line 100 of file jmemmgr.c.
typedef my_memory_mgr* my_mem_ptr
Definition at line 140 of file jmemmgr.c.
typedef union small_pool_struct small_pool_hdr
typedef union small_pool_struct* small_pool_ptr
Definition at line 89 of file jmemmgr.c.
Function Documentation
void jinit_memory_mgr (j_common_ptr cinfo)
Definition at line 1028 of file jmemmgr.c.
References jpeg_memory_mgr::access_virt_barray, jpeg_memory_mgr::access_virt_sarray, ALIGN_TYPE, jpeg_memory_mgr::alloc_barray, jpeg_memory_mgr::alloc_large, jpeg_memory_mgr::alloc_sarray, jpeg_memory_mgr::alloc_small, ERREXIT, ERREXIT1, jpeg_memory_mgr::free_pool, JERR_BAD_ALIGN_TYPE, JERR_BAD_ALLOC_CHUNK, JERR_OUT_OF_MEMORY, jpeg_get_small(), jpeg_mem_init(), jpeg_mem_term(), JPOOL_NUMPOOLS, JPOOL_PERMANENT, my_memory_mgr::large_list, MAX_ALLOC_CHUNK, jpeg_memory_mgr::max_alloc_chunk, jpeg_memory_mgr::max_memory_to_use, my_memory_mgr::pub, jpeg_memory_mgr::realize_virt_arrays, jpeg_memory_mgr::request_virt_barray, jpeg_memory_mgr::request_virt_sarray, jpeg_memory_mgr::self_destruct, SIZEOF, my_memory_mgr::small_list, my_memory_mgr::total_space_allocated, my_memory_mgr::virt_barray_list, and my_memory_mgr::virt_sarray_list.
Referenced by jpeg_CreateCompress(), and jpeg_CreateDecompress().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1