OpenMAXBellagio: jpeglib.h File Reference
jpeglib.h File Reference
#include "jmorecfg.h"
#include "jconfig.h"
Data Structures
struct JQUANT_TBL
struct JHUFF_TBL
struct jpeg_component_info
struct jpeg_scan_info
struct jpeg_marker_struct
struct jpeg_common_struct
struct jpeg_compress_struct
struct jpeg_decompress_struct
struct jpeg_error_mgr
struct jpeg_progress_mgr
struct jpeg_destination_mgr
struct jpeg_source_mgr
struct jpeg_memory_mgr
Macros
#define JPEG_LIB_VERSION 62 /* Version 6b */
#define DCTSIZE 8 /* The basic DCT block is 8x8 samples */
#define DCTSIZE2 64 /* DCTSIZE squared; # of elements in a block */
#define NUM_QUANT_TBLS 4 /* Quantization tables are numbered 0..3 */
#define NUM_HUFF_TBLS 4 /* Huffman tables are numbered 0..3 */
#define NUM_ARITH_TBLS 16 /* Arith-coding tables are numbered 0..15 */
#define MAX_COMPS_IN_SCAN 4 /* JPEG limit on # of components in one scan */
#define MAX_SAMP_FACTOR 4 /* JPEG limit on sampling factors */
#define C_MAX_BLOCKS_IN_MCU 10 /* compressor's limit on blocks per MCU */
#define D_MAX_BLOCKS_IN_MCU 10 /* decompressor's limit on blocks per MCU */
#define JDCT_DEFAULT JDCT_ISLOW
#define JDCT_FASTEST JDCT_IFAST
#define jpeg_common_fields
#define JMSG_LENGTH_MAX 200 /* recommended size of format_message buffer */
#define JMSG_STR_PARM_MAX 80
#define JPOOL_PERMANENT 0 /* lasts until master record is destroyed */
#define JPOOL_IMAGE 1 /* lasts until done with image/datastream */
#define JPOOL_NUMPOOLS 2
#define JPP(arglist) arglist
#define jpeg_create_compress(cinfo)
#define jpeg_create_decompress(cinfo)
#define JPEG_SUSPENDED 0 /* Suspended due to lack of input data */
#define JPEG_HEADER_OK 1 /* Found valid image datastream */
#define JPEG_HEADER_TABLES_ONLY 2 /* Found valid table-specs-only datastream */
#define JPEG_REACHED_SOS 1 /* Reached start of new scan */
#define JPEG_REACHED_EOI 2 /* Reached end of image */
#define JPEG_ROW_COMPLETED 3 /* Completed one iMCU row */
#define JPEG_SCAN_COMPLETED 4 /* Completed last iMCU row of a scan */
#define JPEG_RST0 0xD0 /* RST0 marker code */
#define JPEG_EOI 0xD9 /* EOI marker code */
#define JPEG_APP0 0xE0 /* APP0 marker code */
#define JPEG_COM 0xFE /* COM marker code */
Typedefs
typedef JSAMPLE * JSAMPROW
typedef JSAMPROW * JSAMPARRAY
typedef JSAMPARRAY * JSAMPIMAGE
typedef JCOEF JBLOCK [64]
typedef JBLOCK * JBLOCKROW
typedef JBLOCKROW * JBLOCKARRAY
typedef JBLOCKARRAY * JBLOCKIMAGE
typedef JCOEF * JCOEFPTR
typedef struct jpeg_marker_struct * jpeg_saved_marker_ptr
typedef struct jpeg_common_struct * j_common_ptr
typedef struct
jpeg_compress_struct * j_compress_ptr
typedef struct
jpeg_decompress_struct * j_decompress_ptr
typedef struct
jvirt_sarray_control * jvirt_sarray_ptr
typedef struct
jvirt_barray_control * jvirt_barray_ptr
typedef boolean(* jpeg_marker_parser_method)()
Enumerations
enum J_COLOR_SPACE {
JCS_UNKNOWN, JCS_GRAYSCALE, JCS_RGB, JCS_YCbCr,
JCS_CMYK, JCS_YCCK
}
enum J_DCT_METHOD { JDCT_ISLOW, JDCT_IFAST, JDCT_FLOAT }
enum J_DITHER_MODE { JDITHER_NONE, JDITHER_ORDERED, JDITHER_FS }
Functions
struct jpeg_error_mgr * jpeg_std_error (struct jpeg_error_mgr *err)
void jpeg_CreateCompress (j_compress_ptr cinfo, int version, size_t structsize)
void jpeg_CreateDecompress (j_decompress_ptr cinfo, int version, size_t structsize)
void jpeg_destroy_compress (j_compress_ptr cinfo)
void jpeg_destroy_decompress (j_decompress_ptr cinfo)
void jpeg_stdio_dest (j_compress_ptr cinfo, FILE *outfile)
void jpeg_stdio_src (j_decompress_ptr cinfo, FILE *infile)
void jpeg_set_defaults (j_compress_ptr cinfo)
void jpeg_set_colorspace (j_compress_ptr cinfo, J_COLOR_SPACE colorspace)
void jpeg_default_colorspace (j_compress_ptr cinfo)
void jpeg_set_quality (j_compress_ptr cinfo, int quality, boolean force_baseline)
void jpeg_set_linear_quality (j_compress_ptr cinfo, int scale_factor, boolean force_baseline)
void jpeg_default_qtables (j_compress_ptr cinfo, boolean force_baseline)
void jpeg_add_quant_table (j_compress_ptr cinfo, int which_tbl, const unsigned int *basic_table, int scale_factor, boolean force_baseline)
int jpeg_quality_scaling (int quality)
void jpeg_simple_progression (j_compress_ptr cinfo)
void jpeg_suppress_tables (j_compress_ptr cinfo, boolean suppress)
JQUANT_TBL * jpeg_alloc_quant_table (j_common_ptr cinfo)
JHUFF_TBL * jpeg_alloc_huff_table (j_common_ptr cinfo)
void jpeg_start_compress (j_compress_ptr cinfo, boolean write_all_tables)
JDIMENSION jpeg_write_scanlines (j_compress_ptr cinfo, JSAMPARRAY scanlines, JDIMENSION num_lines)
void jpeg_finish_compress (j_compress_ptr cinfo)
void jpeg_calc_jpeg_dimensions (j_compress_ptr cinfo)
JDIMENSION jpeg_write_raw_data (j_compress_ptr cinfo, JSAMPIMAGE data, JDIMENSION num_lines)
void jpeg_write_marker (j_compress_ptr cinfo, int marker, const JOCTET *dataptr, unsigned int datalen)
void jpeg_write_m_header (j_compress_ptr cinfo, int marker, unsigned int datalen)
void jpeg_write_m_byte (j_compress_ptr cinfo, int val)
void jpeg_write_tables (j_compress_ptr cinfo)
int jpeg_read_header (j_decompress_ptr cinfo, boolean require_image)
boolean jpeg_start_decompress (j_decompress_ptr cinfo)
JDIMENSION jpeg_read_scanlines (j_decompress_ptr cinfo, JSAMPARRAY scanlines, JDIMENSION max_lines)
boolean jpeg_finish_decompress (j_decompress_ptr cinfo)
JDIMENSION jpeg_read_raw_data (j_decompress_ptr cinfo, JSAMPIMAGE data, JDIMENSION max_lines)
boolean jpeg_has_multiple_scans (j_decompress_ptr cinfo)
boolean jpeg_start_output (j_decompress_ptr cinfo, int scan_number)
boolean jpeg_finish_output (j_decompress_ptr cinfo)
boolean jpeg_input_complete (j_decompress_ptr cinfo)
void jpeg_new_colormap (j_decompress_ptr cinfo)
int jpeg_consume_input (j_decompress_ptr cinfo)
void jpeg_calc_output_dimensions (j_decompress_ptr cinfo)
void jpeg_save_markers (j_decompress_ptr cinfo, int marker_code, unsigned int length_limit)
void jpeg_set_marker_processor (j_decompress_ptr cinfo, int marker_code, jpeg_marker_parser_method routine)
jvirt_barray_ptr * jpeg_read_coefficients (j_decompress_ptr cinfo)
void jpeg_write_coefficients (j_compress_ptr cinfo, jvirt_barray_ptr *coef_arrays)
void jpeg_copy_critical_parameters (j_decompress_ptr srcinfo, j_compress_ptr dstinfo)
void jpeg_abort_compress (j_compress_ptr cinfo)
void jpeg_abort_decompress (j_decompress_ptr cinfo)
void jpeg_abort (j_common_ptr cinfo)
void jpeg_destroy (j_common_ptr cinfo)
boolean jpeg_resync_to_restart (j_decompress_ptr cinfo, int desired)
Macro Definition Documentation
#define C_MAX_BLOCKS_IN_MCU 10 /* compressor's limit on blocks per MCU */
Definition at line 55 of file jpeglib.h.
Referenced by jinit_c_coef_controller().
#define D_MAX_BLOCKS_IN_MCU 10 /* decompressor's limit on blocks per MCU */
Definition at line 57 of file jpeglib.h.
Referenced by jinit_d_coef_controller().
#define DCTSIZE 8 /* The basic DCT block is 8x8 samples */
Definition at line 41 of file jpeglib.h.
Referenced by jinit_c_main_controller(), jpeg_calc_jpeg_dimensions(), jpeg_calc_output_dimensions(), jpeg_fdct_10x10(), jpeg_fdct_10x5(), jpeg_fdct_11x11(), jpeg_fdct_12x12(), jpeg_fdct_12x6(), jpeg_fdct_13x13(), jpeg_fdct_14x14(), jpeg_fdct_14x7(), jpeg_fdct_15x15(), jpeg_fdct_16x16(), jpeg_fdct_16x8(), jpeg_fdct_1x2(), jpeg_fdct_2x2(), jpeg_fdct_2x4(), jpeg_fdct_3x3(), jpeg_fdct_3x6(), jpeg_fdct_4x2(), jpeg_fdct_4x4(), jpeg_fdct_4x8(), jpeg_fdct_5x10(), jpeg_fdct_5x5(), jpeg_fdct_6x12(), jpeg_fdct_6x3(), jpeg_fdct_6x6(), jpeg_fdct_7x14(), jpeg_fdct_7x7(), jpeg_fdct_8x16(), jpeg_fdct_8x4(), jpeg_fdct_9x9(), jpeg_fdct_float(), jpeg_fdct_ifast(), jpeg_fdct_islow(), jpeg_idct_10x10(), jpeg_idct_10x5(), jpeg_idct_11x11(), jpeg_idct_12x12(), jpeg_idct_12x6(), jpeg_idct_13x13(), jpeg_idct_14x14(), jpeg_idct_14x7(), jpeg_idct_15x15(), jpeg_idct_16x16(), jpeg_idct_16x8(), jpeg_idct_1x2(), jpeg_idct_2x2(), jpeg_idct_2x4(), jpeg_idct_3x3(), jpeg_idct_3x6(), jpeg_idct_4x2(), jpeg_idct_4x4(), jpeg_idct_4x8(), jpeg_idct_5x10(), jpeg_idct_5x5(), jpeg_idct_6x12(), jpeg_idct_6x3(), jpeg_idct_6x6(), jpeg_idct_7x14(), jpeg_idct_7x7(), jpeg_idct_8x16(), jpeg_idct_8x4(), jpeg_idct_9x9(), jpeg_idct_float(), jpeg_idct_ifast(), jpeg_idct_islow(), jpeg_write_raw_data(), and main().
#define DCTSIZE2 64 /* DCTSIZE squared; # of elements in a block */
Definition at line 42 of file jpeglib.h.
Referenced by jcopy_block_row(), jinit_arith_decoder(), jinit_huff_decoder(), jpeg_add_quant_table(), jpeg_copy_critical_parameters(), jpeg_fdct_16x16(), jpeg_fdct_1x1(), jpeg_fdct_1x2(), jpeg_fdct_2x1(), jpeg_fdct_2x2(), jpeg_fdct_2x4(), jpeg_fdct_3x3(), jpeg_fdct_3x6(), jpeg_fdct_4x2(), jpeg_fdct_4x4(), jpeg_fdct_4x8(), jpeg_fdct_5x10(), jpeg_fdct_5x5(), jpeg_fdct_6x12(), jpeg_fdct_6x3(), jpeg_fdct_6x6(), jpeg_fdct_7x14(), jpeg_fdct_7x7(), jpeg_fdct_8x16(), jpeg_idct_float(), jpeg_idct_ifast(), jpeg_idct_islow(), read_quant_tables(), and read_scan_script().
#define JDCT_DEFAULT JDCT_ISLOW
Definition at line 225 of file jpeglib.h.
Referenced by jpeg_set_defaults().
#define JDCT_FASTEST JDCT_IFAST
Definition at line 228 of file jpeglib.h.
#define JMSG_LENGTH_MAX 200 /* recommended size of format_message buffer */
Definition at line 671 of file jpeglib.h.
#define JMSG_STR_PARM_MAX 80
Definition at line 679 of file jpeglib.h.
#define JPEG_APP0 0xE0 /* APP0 marker code */
Definition at line 1073 of file jpeglib.h.
Referenced by jcopy_markers_execute(), jcopy_markers_setup(), main(), and omx_jpegdec_component_Init().
#define JPEG_COM 0xFE /* COM marker code */
Definition at line 1074 of file jpeglib.h.
Referenced by jcopy_markers_setup(), main(), and omx_jpegdec_component_Init().
#define jpeg_common_fields
Value:
struct jpeg_error_mgr * err;    /* Error handler module */\
  struct jpeg_memory_mgr * mem; /* Memory manager module */\
  struct jpeg_progress_mgr * progress; /* Progress monitor, or NULL if none */\
  void * client_data;       /* Available for use by application */\
  boolean is_decompressor;  /* So common code can tell which is which */\
  int global_state      /* For checking call sequence validity */
Definition at line 242 of file jpeglib.h.
#define jpeg_create_compress (cinfo)
Value:
jpeg_CreateCompress((cinfo), JPEG_LIB_VERSION, \
            (size_t) sizeof(struct jpeg_compress_struct))
Definition at line 915 of file jpeglib.h.
Referenced by main(), and omx_jpegenc_component_Init().
#define jpeg_create_decompress (cinfo)
Value:
jpeg_CreateDecompress((cinfo), JPEG_LIB_VERSION, \
              (size_t) sizeof(struct jpeg_decompress_struct))
Definition at line 918 of file jpeglib.h.
Referenced by main(), and omx_jpegdec_component_Init().
#define JPEG_EOI 0xD9 /* EOI marker code */
Definition at line 1072 of file jpeglib.h.
#define JPEG_HEADER_OK 1 /* Found valid image datastream */
Definition at line 992 of file jpeglib.h.
Referenced by jpeg_read_header().
#define JPEG_HEADER_TABLES_ONLY 2 /* Found valid table-specs-only datastream */
Definition at line 993 of file jpeglib.h.
Referenced by jpeg_read_header().
#define JPEG_LIB_VERSION 62 /* Version 6b */
Definition at line 33 of file jpeglib.h.
Referenced by jpeg_CreateCompress(), and jpeg_CreateDecompress().
#define JPEG_REACHED_EOI 2 /* Reached end of image */
Definition at line 1023 of file jpeglib.h.
Referenced by jpeg_read_coefficients(), jpeg_read_header(), and jpeg_start_decompress().
#define JPEG_REACHED_SOS 1 /* Reached start of new scan */
Definition at line 1022 of file jpeglib.h.
Referenced by jpeg_consume_input(), jpeg_read_coefficients(), jpeg_read_header(), and jpeg_start_decompress().
#define JPEG_ROW_COMPLETED 3 /* Completed one iMCU row */
Definition at line 1024 of file jpeglib.h.
Referenced by jpeg_read_coefficients(), and jpeg_start_decompress().
#define JPEG_RST0 0xD0 /* RST0 marker code */
Definition at line 1071 of file jpeglib.h.
#define JPEG_SCAN_COMPLETED 4 /* Completed last iMCU row of a scan */
Definition at line 1025 of file jpeglib.h.
#define JPEG_SUSPENDED 0 /* Suspended due to lack of input data */
Definition at line 991 of file jpeglib.h.
Referenced by jpeg_consume_input(), jpeg_finish_decompress(), jpeg_finish_output(), jpeg_read_coefficients(), jpeg_read_header(), and jpeg_start_decompress().
#define JPOOL_IMAGE 1 /* lasts until done with image/datastream */
Definition at line 768 of file jpeglib.h.
Referenced by jinit_2pass_quantizer(), jinit_arith_decoder(), jinit_arith_encoder(), jinit_c_coef_controller(), jinit_c_main_controller(), jinit_c_master_control(), jinit_c_prep_controller(), jinit_color_converter(), jinit_color_deconverter(), jinit_d_coef_controller(), jinit_d_main_controller(), jinit_d_post_controller(), jinit_downsampler(), jinit_forward_dct(), jinit_huff_decoder(), jinit_huff_encoder(), jinit_inverse_dct(), jinit_marker_writer(), jinit_master_decompress(), jinit_merged_upsampler(), jinit_read_ppm(), jinit_upsampler(), jinit_write_bmp(), jinit_write_gif(), jinit_write_ppm(), jinit_write_targa(), read_color_map(), and read_scan_script().
#define JPOOL_NUMPOOLS 2
Definition at line 769 of file jpeglib.h.
Referenced by jinit_memory_mgr(), and jpeg_abort().
#define JPOOL_PERMANENT 0 /* lasts until master record is destroyed */
Definition at line 767 of file jpeglib.h.
Referenced by jinit_input_controller(), jinit_marker_reader(), jinit_memory_mgr(), jpeg_abort(), jpeg_alloc_huff_table(), jpeg_alloc_quant_table(), jpeg_data_src(), jpeg_set_defaults(), jpeg_simple_progression(), jpeg_stdio_dest(), and jpeg_stdio_src().
#define JPP (arglist) arglist
Definition at line 837 of file jpeglib.h.
#define MAX_COMPS_IN_SCAN 4 /* JPEG limit on # of components in one scan */
Definition at line 46 of file jpeglib.h.
Referenced by jpeg_simple_progression(), and read_scan_script().
#define MAX_SAMP_FACTOR 4 /* JPEG limit on sampling factors */
Definition at line 47 of file jpeglib.h.
#define NUM_ARITH_TBLS 16 /* Arith-coding tables are numbered 0..15 */
Definition at line 45 of file jpeglib.h.
Referenced by jinit_arith_decoder(), jinit_arith_encoder(), and jpeg_set_defaults().
#define NUM_HUFF_TBLS 4 /* Huffman tables are numbered 0..3 */
Definition at line 44 of file jpeglib.h.
Referenced by jinit_huff_decoder(), jinit_huff_encoder(), jpeg_CreateCompress(), jpeg_CreateDecompress(), and jpeg_suppress_tables().
#define NUM_QUANT_TBLS 4 /* Quantization tables are numbered 0..3 */
Definition at line 43 of file jpeglib.h.
Referenced by jinit_forward_dct(), jpeg_add_quant_table(), jpeg_copy_critical_parameters(), jpeg_CreateCompress(), jpeg_CreateDecompress(), jpeg_suppress_tables(), read_quant_tables(), set_quality_ratings(), and set_quant_slots().
Typedef Documentation
typedef struct jpeg_common_struct* j_common_ptr
Definition at line 262 of file jpeglib.h.
typedef struct jpeg_compress_struct* j_compress_ptr
Definition at line 263 of file jpeglib.h.
typedef struct jpeg_decompress_struct* j_decompress_ptr
Definition at line 264 of file jpeglib.h.
typedef JCOEF JBLOCK[64]
Definition at line 70 of file jpeglib.h.
typedef JBLOCKROW* JBLOCKARRAY
Definition at line 72 of file jpeglib.h.
typedef JBLOCKARRAY* JBLOCKIMAGE
Definition at line 73 of file jpeglib.h.
typedef JBLOCK* JBLOCKROW
Definition at line 71 of file jpeglib.h.
typedef JCOEF* JCOEFPTR
Definition at line 75 of file jpeglib.h.
typedef boolean(* jpeg_marker_parser_method)()
Definition at line 828 of file jpeglib.h.
typedef struct jpeg_marker_struct* jpeg_saved_marker_ptr
Definition at line 194 of file jpeglib.h.
typedef JSAMPROW* JSAMPARRAY
Definition at line 67 of file jpeglib.h.
typedef JSAMPARRAY* JSAMPIMAGE
Definition at line 68 of file jpeglib.h.
typedef JSAMPLE* JSAMPROW
Definition at line 66 of file jpeglib.h.
typedef struct jvirt_barray_control* jvirt_barray_ptr
Definition at line 772 of file jpeglib.h.
typedef struct jvirt_sarray_control* jvirt_sarray_ptr
Definition at line 771 of file jpeglib.h.
Enumeration Type Documentation
enum J_COLOR_SPACE
Enumerator
JCS_UNKNOWN
JCS_GRAYSCALE
JCS_RGB
JCS_YCbCr
JCS_CMYK
JCS_YCCK
Definition at line 207 of file jpeglib.h.
enum J_DCT_METHOD
Enumerator
JDCT_ISLOW
JDCT_IFAST
JDCT_FLOAT
Definition at line 218 of file jpeglib.h.
enum J_DITHER_MODE
Enumerator
JDITHER_NONE
JDITHER_ORDERED
JDITHER_FS
Definition at line 233 of file jpeglib.h.
Function Documentation
void jpeg_abort (j_common_ptr cinfo)
Definition at line 29 of file jcomapi.c.
References CSTATE_START, DSTATE_START, JPOOL_NUMPOOLS, and JPOOL_PERMANENT.
Referenced by jpeg_abort_compress(), jpeg_abort_decompress(), jpeg_finish_compress(), jpeg_finish_decompress(), and jpeg_read_header().
void jpeg_abort_compress (j_compress_ptr cinfo)
Definition at line 102 of file jcapimin.c.
References jpeg_abort().
void jpeg_abort_decompress (j_decompress_ptr cinfo)
Definition at line 103 of file jdapimin.c.
References jpeg_abort().
void jpeg_add_quant_table (j_compress_ptr cinfo, int which_tbl, const unsigned int * basic_table, int scale_factor, boolean force_baseline)
Definition at line 23 of file jcparam.c.
References CSTATE_START, DCTSIZE2, ERREXIT1, FALSE, JERR_BAD_STATE, JERR_DQT_INDEX, jpeg_alloc_quant_table(), and NUM_QUANT_TBLS.
Referenced by jpeg_default_qtables(), jpeg_set_linear_quality(), and read_quant_tables().
JHUFF_TBL* jpeg_alloc_huff_table (j_common_ptr cinfo)
Definition at line 98 of file jcomapi.c.
References FALSE, JPOOL_PERMANENT, JHUFF_TBL::sent_table, and SIZEOF.
JQUANT_TBL* jpeg_alloc_quant_table (j_common_ptr cinfo)
Definition at line 86 of file jcomapi.c.
References FALSE, JPOOL_PERMANENT, JQUANT_TBL::sent_table, and SIZEOF.
Referenced by jpeg_add_quant_table(), and jpeg_copy_critical_parameters().
void jpeg_calc_jpeg_dimensions (j_compress_ptr cinfo)
Definition at line 52 of file jcmaster.c.
References DCTSIZE, and jdiv_round_up().
void jpeg_calc_output_dimensions (j_decompress_ptr cinfo)
Definition at line 87 of file jdmaster.c.
References compptr, jpeg_component_info::DCT_h_scaled_size, jpeg_component_info::DCT_v_scaled_size, DCTSIZE, jpeg_component_info::downsampled_height, jpeg_component_info::downsampled_width, DSTATE_READY, ERREXIT1, jpeg_component_info::h_samp_factor, JCS_CMYK, JCS_GRAYSCALE, JCS_RGB, JCS_YCbCr, JCS_YCCK, jdiv_round_up(), JERR_BAD_STATE, and jpeg_component_info::v_samp_factor.
Referenced by jinit_write_bmp(), jinit_write_gif(), jinit_write_ppm(), and jinit_write_targa().
int jpeg_consume_input (j_decompress_ptr cinfo)
Definition at line 287 of file jdapimin.c.
References DSTATE_BUFIMAGE, DSTATE_BUFPOST, DSTATE_INHEADER, DSTATE_PRELOAD, DSTATE_PRESCAN, DSTATE_RAW_OK, DSTATE_READY, DSTATE_SCANNING, DSTATE_START, DSTATE_STOPPING, ERREXIT1, JERR_BAD_STATE, JPEG_REACHED_SOS, and JPEG_SUSPENDED.
Referenced by jpeg_read_header().
void jpeg_copy_critical_parameters (j_decompress_ptr srcinfo, j_compress_ptr dstinfo)
Definition at line 63 of file jctrans.c.
References jpeg_component_info::component_id, CSTATE_START, DCTSIZE2, ERREXIT1, ERREXIT2, FALSE, jpeg_component_info::h_samp_factor, JERR_BAD_STATE, JERR_COMPONENT_COUNT, JERR_MISMATCHED_QUANT_TABLE, JERR_NO_QUANT_TABLE, jpeg_alloc_quant_table(), jpeg_set_colorspace(), jpeg_set_defaults(), MAX_COMPONENTS, MEMCOPY, NUM_QUANT_TBLS, jpeg_component_info::quant_table, jpeg_component_info::quant_tbl_no, JQUANT_TBL::quantval, SIZEOF, and jpeg_component_info::v_samp_factor.
Referenced by main().
void jpeg_CreateCompress (j_compress_ptr cinfo, int version, size_t structsize)
Definition at line 30 of file jcapimin.c.
References CSTATE_START, err, ERREXIT2, FALSE, jpeg_common_struct::global_state, jpeg_error_mgr::i, JERR_BAD_LIB_VERSION, JERR_BAD_STRUCT_SIZE, jinit_memory_mgr(), JPEG_LIB_VERSION, MEMZERO, NUM_HUFF_TBLS, NUM_QUANT_TBLS, jpeg_common_struct::progress, and SIZEOF.
void jpeg_CreateDecompress (j_decompress_ptr cinfo, int version, size_t structsize)
Definition at line 30 of file jdapimin.c.
References DSTATE_START, err, ERREXIT2, jpeg_common_struct::global_state, jpeg_error_mgr::i, JERR_BAD_LIB_VERSION, JERR_BAD_STRUCT_SIZE, jinit_input_controller(), jinit_marker_reader(), jinit_memory_mgr(), JPEG_LIB_VERSION, MEMZERO, NUM_HUFF_TBLS, NUM_QUANT_TBLS, jpeg_common_struct::progress, SIZEOF, and TRUE.
void jpeg_default_colorspace (j_compress_ptr cinfo)
Definition at line 377 of file jcparam.c.
References ERREXIT, JCS_CMYK, JCS_GRAYSCALE, JCS_RGB, JCS_UNKNOWN, JCS_YCbCr, JCS_YCCK, JERR_BAD_IN_COLORSPACE, and jpeg_set_colorspace().
Referenced by jpeg_set_defaults(), main(), and omx_jpegenc_component_BufferMgmtFunction().
void jpeg_default_qtables (j_compress_ptr cinfo, boolean force_baseline)
Definition at line 90 of file jcparam.c.
References jpeg_add_quant_table().
Referenced by set_quality_ratings().
void jpeg_destroy (j_common_ptr cinfo)
Definition at line 69 of file jcomapi.c.
Referenced by jpeg_destroy_compress(), and jpeg_destroy_decompress().
void jpeg_destroy_compress (j_compress_ptr cinfo)
Definition at line 90 of file jcapimin.c.
References jpeg_destroy().
Referenced by main(), and omx_jpegenc_component_BufferMgmtFunction().
void jpeg_destroy_decompress (j_decompress_ptr cinfo)
Definition at line 91 of file jdapimin.c.
References jpeg_destroy().
Referenced by main(), omx_jpegdec_component_BufferMgmtCallback(), and omx_jpegdec_component_BufferMgmtFunction().
void jpeg_finish_compress (j_compress_ptr cinfo)
Definition at line 149 of file jcapimin.c.
References CSTATE_RAW_OK, CSTATE_SCANNING, CSTATE_WRCOEFS, ERREXIT, ERREXIT1, JERR_BAD_STATE, JERR_CANT_SUSPEND, JERR_TOO_LITTLE_DATA, and jpeg_abort().
Referenced by main(), and omx_jpegenc_component_BufferMgmtFunction().
boolean jpeg_finish_decompress (j_decompress_ptr cinfo)
Definition at line 369 of file jdapimin.c.
References DSTATE_BUFIMAGE, DSTATE_RAW_OK, DSTATE_SCANNING, DSTATE_STOPPING, ERREXIT, ERREXIT1, FALSE, JERR_BAD_STATE, JERR_TOO_LITTLE_DATA, jpeg_abort(), JPEG_SUSPENDED, and TRUE.
Referenced by main(), omx_jpegdec_component_BufferMgmtCallback(), and omx_jpegdec_component_BufferMgmtFunction().
boolean jpeg_finish_output (j_decompress_ptr cinfo)
Definition at line 253 of file jdapistd.c.
References DSTATE_BUFIMAGE, DSTATE_BUFPOST, DSTATE_RAW_OK, DSTATE_SCANNING, ERREXIT1, FALSE, JERR_BAD_STATE, JPEG_SUSPENDED, and TRUE.
boolean jpeg_has_multiple_scans (j_decompress_ptr cinfo)
Definition at line 349 of file jdapimin.c.
References DSTATE_READY, DSTATE_STOPPING, ERREXIT1, and JERR_BAD_STATE.
boolean jpeg_input_complete (j_decompress_ptr cinfo)
Definition at line 334 of file jdapimin.c.
References DSTATE_START, DSTATE_STOPPING, ERREXIT1, and JERR_BAD_STATE.
void jpeg_new_colormap (j_decompress_ptr cinfo)
Definition at line 618 of file jdmaster.c.
References DSTATE_BUFIMAGE, ERREXIT, ERREXIT1, FALSE, JERR_BAD_STATE, JERR_MODE_CHANGE, and my_comp_master::pub.
int jpeg_quality_scaling (int quality)
Definition at line 122 of file jcparam.c.
Referenced by jpeg_set_quality(), and set_quality_ratings().
jvirt_barray_ptr* jpeg_read_coefficients (j_decompress_ptr cinfo)
Definition at line 45 of file jdtrans.c.
References DSTATE_BUFIMAGE, DSTATE_RDCOEFS, DSTATE_READY, DSTATE_STOPPING, ERREXIT1, JERR_BAD_STATE, JPEG_REACHED_EOI, JPEG_REACHED_SOS, JPEG_ROW_COMPLETED, and JPEG_SUSPENDED.
Referenced by main().
int jpeg_read_header (j_decompress_ptr cinfo, boolean require_image)
Definition at line 241 of file jdapimin.c.
References DSTATE_INHEADER, DSTATE_START, ERREXIT, ERREXIT1, JERR_BAD_STATE, JERR_NO_IMAGE, jpeg_abort(), jpeg_consume_input(), JPEG_HEADER_OK, JPEG_HEADER_TABLES_ONLY, JPEG_REACHED_EOI, JPEG_REACHED_SOS, and JPEG_SUSPENDED.
Referenced by main(), omx_jpegdec_component_BufferMgmtCallback(), and omx_jpegdec_component_BufferMgmtFunction().
JDIMENSION jpeg_read_raw_data (j_decompress_ptr cinfo, JSAMPIMAGE data, JDIMENSION max_lines)
Definition at line 185 of file jdapistd.c.
References DSTATE_RAW_OK, ERREXIT, ERREXIT1, JERR_BAD_STATE, JERR_BUFFER_SIZE, JWRN_TOO_MUCH_DATA, and WARNMS.
JDIMENSION jpeg_read_scanlines (j_decompress_ptr cinfo, JSAMPARRAY scanlines, JDIMENSION max_lines)
Definition at line 152 of file jdapistd.c.
References DSTATE_SCANNING, ERREXIT1, JERR_BAD_STATE, JWRN_TOO_MUCH_DATA, and WARNMS.
Referenced by main(), omx_jpegdec_component_BufferMgmtCallback(), and omx_jpegdec_component_BufferMgmtFunction().
boolean jpeg_resync_to_restart (j_decompress_ptr cinfo, int desired)
Definition at line 1192 of file jdmarker.c.
References FALSE, JTRC_RECOVERY_ACTION, JWRN_MUST_RESYNC, M_RST0, M_RST7, M_SOF0, TRACEMS2, TRUE, and WARNMS2.
Referenced by jpeg_data_src(), and jpeg_stdio_src().
void jpeg_save_markers (j_decompress_ptr cinfo, int marker_code, unsigned int length_limit)
Definition at line 1300 of file jdmarker.c.
References APP0_DATA_LEN, APP14_DATA_LEN, ERREXIT1, JERR_UNKNOWN_MARKER, M_APP14, M_APP15, M_COM, and SIZEOF.
Referenced by jcopy_markers_setup().
void jpeg_set_colorspace (j_compress_ptr cinfo, J_COLOR_SPACE colorspace)
Definition at line 409 of file jcparam.c.
References compptr, CSTATE_START, ERREXIT, ERREXIT1, ERREXIT2, FALSE, JCS_CMYK, JCS_GRAYSCALE, JCS_RGB, JCS_UNKNOWN, JCS_YCbCr, JCS_YCCK, JERR_BAD_J_COLORSPACE, JERR_BAD_STATE, JERR_COMPONENT_COUNT, MAX_COMPONENTS, SET_COMP, and TRUE.
Referenced by jpeg_copy_critical_parameters(), and jpeg_default_colorspace().
void jpeg_set_defaults (j_compress_ptr cinfo)
Definition at line 284 of file jcparam.c.
References BITS_IN_JSAMPLE, CSTATE_START, ERREXIT1, FALSE, JDCT_DEFAULT, JERR_BAD_STATE, jpeg_default_colorspace(), jpeg_set_quality(), JPOOL_PERMANENT, MAX_COMPONENTS, NUM_ARITH_TBLS, SIZEOF, and TRUE.
Referenced by jpeg_copy_critical_parameters(), main(), and omx_jpegenc_component_Init().
void jpeg_set_linear_quality (j_compress_ptr cinfo, int scale_factor, boolean force_baseline)
Definition at line 105 of file jcparam.c.
References jpeg_add_quant_table().
Referenced by jpeg_set_quality().
void jpeg_set_marker_processor (j_decompress_ptr cinfo, int marker_code, jpeg_marker_parser_method routine)
Definition at line 1349 of file jdmarker.c.
References ERREXIT1, JERR_UNKNOWN_MARKER, M_APP15, and M_COM.
Referenced by main(), and omx_jpegdec_component_Init().
void jpeg_set_quality (j_compress_ptr cinfo, int quality, boolean force_baseline)
Definition at line 148 of file jcparam.c.
References jpeg_quality_scaling(), and jpeg_set_linear_quality().
Referenced by jpeg_set_defaults().
void jpeg_simple_progression (j_compress_ptr cinfo)
Definition at line 555 of file jcparam.c.
References CSTATE_START, ERREXIT1, JCS_YCbCr, JERR_BAD_STATE, JPOOL_PERMANENT, MAX, MAX_COMPS_IN_SCAN, and SIZEOF.
void jpeg_start_compress (j_compress_ptr cinfo, boolean write_all_tables)
Definition at line 38 of file jcapistd.c.
References CSTATE_RAW_OK, CSTATE_SCANNING, CSTATE_START, ERREXIT1, FALSE, JERR_BAD_STATE, jinit_compress_master(), and jpeg_suppress_tables().
Referenced by main(), and omx_jpegenc_component_BufferMgmtFunction().
boolean jpeg_start_decompress (j_decompress_ptr cinfo)
Definition at line 38 of file jdapistd.c.
References DSTATE_BUFIMAGE, DSTATE_PRELOAD, DSTATE_PRESCAN, DSTATE_READY, ERREXIT, ERREXIT1, FALSE, JERR_BAD_STATE, JERR_NOT_COMPILED, jinit_master_decompress(), JPEG_REACHED_EOI, JPEG_REACHED_SOS, JPEG_ROW_COMPLETED, JPEG_SUSPENDED, and TRUE.
Referenced by main(), omx_jpegdec_component_BufferMgmtCallback(), and omx_jpegdec_component_BufferMgmtFunction().
boolean jpeg_start_output (j_decompress_ptr cinfo, int scan_number)
Definition at line 228 of file jdapistd.c.
References DSTATE_BUFIMAGE, DSTATE_PRESCAN, ERREXIT1, and JERR_BAD_STATE.
struct jpeg_error_mgr* jpeg_std_error (struct jpeg_error_mgr * err)
Definition at line 231 of file jerror.c.
References jpeg_error_mgr::emit_message, err, jpeg_error_mgr::error_exit, jpeg_error_mgr::format_message, JMSG_LASTMSGCODE, jpeg_std_message_table, jpeg_error_mgr::output_message, and jpeg_error_mgr::reset_error_mgr.
Referenced by main(), omx_jpegdec_component_Init(), and omx_jpegenc_component_Init().
void jpeg_stdio_dest (j_compress_ptr cinfo, FILE * outfile)
Definition at line 130 of file jdatadst.c.
References jpeg_destination_mgr::empty_output_buffer, jpeg_destination_mgr::init_destination, JPOOL_PERMANENT, my_destination_mgr::outfile, my_destination_mgr::pub, SIZEOF, and jpeg_destination_mgr::term_destination.
Referenced by main().
void jpeg_stdio_src (j_decompress_ptr cinfo, FILE * infile)
Definition at line 182 of file jdatasrc.c.
References my_source_mgr::buffer, jpeg_source_mgr::bytes_in_buffer, jpeg_source_mgr::fill_input_buffer, my_source_mgr::infile, jpeg_source_mgr::init_source, INPUT_BUF_SIZE, jpeg_resync_to_restart(), JPOOL_PERMANENT, jpeg_source_mgr::next_input_byte, my_source_mgr::pub, jpeg_source_mgr::resync_to_restart, SIZEOF, jpeg_source_mgr::skip_input_data, and jpeg_source_mgr::term_source.
Referenced by main().
void jpeg_suppress_tables (j_compress_ptr cinfo, boolean suppress)
Definition at line 121 of file jcapimin.c.
References jpeg_error_mgr::i, NUM_HUFF_TBLS, NUM_QUANT_TBLS, JQUANT_TBL::sent_table, and JHUFF_TBL::sent_table.
Referenced by jpeg_start_compress(), and jpeg_write_coefficients().
void jpeg_write_coefficients (j_compress_ptr cinfo, jvirt_barray_ptr * coef_arrays)
Definition at line 38 of file jctrans.c.
References CSTATE_START, CSTATE_WRCOEFS, ERREXIT1, FALSE, JERR_BAD_STATE, and jpeg_suppress_tables().
Referenced by main().
void jpeg_write_m_byte (j_compress_ptr cinfo, int val)
Definition at line 228 of file jcapimin.c.
Referenced by jcopy_markers_execute().
void jpeg_write_m_header (j_compress_ptr cinfo, int marker, unsigned int datalen)
Definition at line 216 of file jcapimin.c.
References CSTATE_RAW_OK, CSTATE_SCANNING, CSTATE_WRCOEFS, ERREXIT1, and JERR_BAD_STATE.
Referenced by jcopy_markers_execute().
void jpeg_write_marker (j_compress_ptr cinfo, int marker, const JOCTET * dataptr, unsigned int datalen)
Definition at line 194 of file jcapimin.c.
References CSTATE_RAW_OK, CSTATE_SCANNING, CSTATE_WRCOEFS, ERREXIT1, info, JERR_BAD_STATE, and JMETHOD.
Referenced by jcopy_markers_execute().
JDIMENSION jpeg_write_raw_data (j_compress_ptr cinfo, JSAMPIMAGE data, JDIMENSION num_lines)
Definition at line 120 of file jcapistd.c.
References CSTATE_RAW_OK, DCTSIZE, ERREXIT, ERREXIT1, JERR_BAD_STATE, JERR_BUFFER_SIZE, JWRN_TOO_MUCH_DATA, and WARNMS.
JDIMENSION jpeg_write_scanlines (j_compress_ptr cinfo, JSAMPARRAY scanlines, JDIMENSION num_lines)
Definition at line 77 of file jcapistd.c.
References CSTATE_SCANNING, ERREXIT1, JERR_BAD_STATE, JWRN_TOO_MUCH_DATA, and WARNMS.
Referenced by main(), and omx_jpegenc_component_BufferMgmtFunction().
void jpeg_write_tables (j_compress_ptr cinfo)
Definition at line 256 of file jcapimin.c.
References CSTATE_START, ERREXIT1, JERR_BAD_STATE, and jinit_marker_writer().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1