OpenMAXBellagio: jpegtran.c File Reference
jpegtran.c File Reference
#include "cdjpeg.h"
#include "transupp.h"
#include "jversion.h"
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 357 of file jpegtran.c.
References DCTSIZE, enable_signal_catcher(), end_progress_monitor(), jpeg_compress_struct::err, jpeg_decompress_struct::err, EXIT_FAILURE, EXIT_SUCCESS, EXIT_WARNING, FALSE, jcopy_markers_execute(), jcopy_markers_setup(), jpeg_copy_critical_parameters(), jpeg_create_compress, jpeg_create_decompress, jpeg_destroy_compress(), jpeg_destroy_decompress(), jpeg_finish_compress(), jpeg_finish_decompress(), jpeg_read_coefficients(), jpeg_read_header(), jpeg_std_error(), jpeg_stdio_dest(), jpeg_stdio_src(), jpeg_write_coefficients(), jpeg_memory_mgr::max_memory_to_use, jpeg_common_struct::mem, jpeg_compress_struct::mem, jpeg_error_mgr::num_warnings, jpeg_transform_info::perfect, READ_BINARY, read_stdin(), start_progress_monitor(), jpeg_error_mgr::trace_level, jpeg_transform_info::transform, TRUE, WRITE_BINARY, and write_stdout().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1