OpenMAXBellagio: wrbmp.c File Reference
libjpeg-6c/wrbmp.c File Reference
#include "cdjpeg.h"
Data Structures
struct bmp_dest_struct
Macros
#define PUT_2B(array, offset, value)
#define PUT_4B(array, offset, value)
Typedefs
typedef bmp_dest_struct * bmp_dest_ptr
Functions
djpeg_dest_ptr jinit_write_bmp (j_decompress_ptr cinfo, boolean is_os2)
Macro Definition Documentation
#define PUT_2B (array, offset, value)
Value:
(array[offset] = (char) ((value) & 0xFF), \
     array[offset+1] = (char) (((value) >> 8) & 0xFF))
#define PUT_4B (array, offset, value)
Value:
(array[offset] = (char) ((value) & 0xFF), \
     array[offset+1] = (char) (((value) >> 8) & 0xFF), \
     array[offset+2] = (char) (((value) >> 16) & 0xFF), \
     array[offset+3] = (char) (((value) >> 24) & 0xFF))
Typedef Documentation
typedef bmp_dest_struct* bmp_dest_ptr
Definition at line 56 of file libjpeg-6c/wrbmp.c.
Function Documentation
djpeg_dest_ptr jinit_write_bmp (j_decompress_ptr cinfo, boolean is_os2)
Definition at line 390 of file libjpeg-6c/wrbmp.c.
References djpeg_dest_struct::buffer, djpeg_dest_struct::buffer_height, bmp_dest_struct::cur_output_row, bmp_dest_struct::data_width, ERREXIT, FALSE, djpeg_dest_struct::finish_output, bmp_dest_struct::is_os2, JCS_GRAYSCALE, JCS_RGB, jpeg_calc_output_dimensions(), JPOOL_IMAGE, bmp_dest_struct::pad_bytes, bmp_dest_struct::pub, djpeg_dest_struct::put_pixel_rows, bmp_dest_struct::row_width, SIZEOF, djpeg_dest_struct::start_output, cdjpeg_progress_mgr::total_extra_passes, and bmp_dest_struct::whole_image.
Referenced by main(), omx_jpegdec_component_BufferMgmtCallback(), and omx_jpegdec_component_BufferMgmtFunction().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1