OpenMAXBellagio: omx_symbianoutputstreamsink_component.c File Reference
omx_symbianoutputstreamsink_component.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include "omxcore.h"
#include "omx_symbianoutputstreamsink_component.h"
#include "omx_symbian_output_stream_wrapper.h"
Functions
OMX_ERRORTYPE omx_symbianoutputstreamsink_component_Constructor (OMX_COMPONENTTYPE *openmaxStandComp, OMX_STRING cComponentName)
OMX_ERRORTYPE omx_symbianoutputstreamsink_component_Destructor (OMX_COMPONENTTYPE *openmaxStandComp)
void omx_symbianoutputstreamsink_component_BufferMgmtCallback (OMX_COMPONENTTYPE *openmaxStandComp, OMX_BUFFERHEADERTYPE *inputbuffer)
OMX_ERRORTYPE omx_symbianoutputstreamsink_component_SetConfig (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nIndex, OMX_IN OMX_PTR pComponentConfigStructure)
OMX_ERRORTYPE omx_symbianoutputstreamsink_component_GetConfig (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nIndex, OMX_INOUT OMX_PTR pComponentConfigStructure)
OMX_ERRORTYPE omx_symbianoutputstreamsink_component_SetParameter (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nParamIndex, OMX_IN OMX_PTR ComponentParameterStructure)
OMX_ERRORTYPE omx_symbianoutputstreamsink_component_GetParameter (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nParamIndex, OMX_INOUT OMX_PTR ComponentParameterStructure)
Detailed Description
OpenMAX Symbian output stream sink component. This component is an audio sink that uses Symbian MMF output stream class.
Copyright (C) 2008 Nokia Corporation and/or its subsidiary(-ies).
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Definition in file omx_symbianoutputstreamsink_component.c.
Function Documentation
void omx_symbianoutputstreamsink_component_BufferMgmtCallback (OMX_COMPONENTTYPE * openmaxStandComp, OMX_BUFFERHEADERTYPE * inputbuffer)
This function plays the input buffer. When fully consumed it returns.
Definition at line 172 of file omx_symbianoutputstreamsink_component.c.
References DEB_LEV_FULL_SEQ, DEBUG, OMX_BUFFERHEADERTYPE::nFilledLen, OMX_BASE_SINK_INPUTPORT_INDEX, open_output_stream(), OMX_BUFFERHEADERTYPE::pBuffer, OMX_COMPONENTTYPE::pComponentPrivate, and write_audio_data().
Referenced by omx_symbianoutputstreamsink_component_Constructor().
OMX_ERRORTYPE omx_symbianoutputstreamsink_component_Constructor (OMX_COMPONENTTYPE * openmaxStandComp, OMX_STRING cComponentName)
Domain specific section for the ports.
Definition at line 36 of file omx_symbianoutputstreamsink_component.c.
References base_port_Constructor(), create_output_stream(), DEB_LEV_ERR, DEB_LEV_PARAMS, DEB_LEV_SIMPLE_SEQ, DEBUG, DEFAULT_OUT_BUFFER_SIZE, err, OMX_COMPONENTTYPE::GetConfig, OMX_COMPONENTTYPE::GetParameter, OMX_AUDIO_ChannelNone, OMX_AUDIO_CodingPCM, OMX_AUDIO_PCMModeLinear, omx_base_sink_Constructor(), OMX_BASE_SINK_INPUTPORT_INDEX, OMX_DirInput, OMX_EndianLittle, OMX_ErrorHardware, OMX_ErrorInsufficientResources, OMX_ErrorNone, OMX_FALSE, OMX_IndexParamAudioInit, OMX_IndexParamAudioPcm, OMX_NumericalDataSigned, OMX_PortDomainAudio, omx_symbianoutputstreamsink_component_BufferMgmtCallback(), omx_symbianoutputstreamsink_component_Destructor(), omx_symbianoutputstreamsink_component_GetConfig(), omx_symbianoutputstreamsink_component_GetParameter(), omx_symbianoutputstreamsink_component_SetConfig(), omx_symbianoutputstreamsink_component_SetParameter(), OMX_TRUE, OMX_COMPONENTTYPE::pComponentPrivate, OMX_COMPONENTTYPE::SetConfig, setHeader(), and OMX_COMPONENTTYPE::SetParameter.
OMX_ERRORTYPE omx_symbianoutputstreamsink_component_Destructor (OMX_COMPONENTTYPE * openmaxStandComp)
The Destructor
Definition at line 154 of file omx_symbianoutputstreamsink_component.c.
References close_output_stream(), omx_base_sink_Destructor(), OMX_BASE_SINK_INPUTPORT_INDEX, and OMX_COMPONENTTYPE::pComponentPrivate.
Referenced by omx_symbianoutputstreamsink_component_Constructor().
OMX_ERRORTYPE omx_symbianoutputstreamsink_component_GetConfig (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nIndex, OMX_INOUT OMX_PTR pComponentConfigStructure)
Definition at line 208 of file omx_symbianoutputstreamsink_component.c.
References omx_base_component_GetConfig().
Referenced by omx_symbianoutputstreamsink_component_Constructor().
OMX_ERRORTYPE omx_symbianoutputstreamsink_component_GetParameter (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nParamIndex, OMX_INOUT OMX_PTR ComponentParameterStructure)
Definition at line 302 of file omx_symbianoutputstreamsink_component.c.
References DEB_LEV_SIMPLE_SEQ, DEBUG, OMX_AUDIO_PARAM_PORTFORMATTYPE::nPortIndex, omx_base_component_GetParameter(), OMX_BASE_SINK_INPUTPORT_INDEX, OMX_ErrorBadParameter, OMX_ErrorBadPortIndex, OMX_ErrorNone, OMX_IndexParamAudioInit, OMX_IndexParamAudioPcm, OMX_IndexParamAudioPortFormat, OMX_PortDomainAudio, OMX_COMPONENTTYPE::pComponentPrivate, and setHeader().
Referenced by omx_symbianoutputstreamsink_component_Constructor().
OMX_ERRORTYPE omx_symbianoutputstreamsink_component_SetConfig (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nIndex, OMX_IN OMX_PTR pComponentConfigStructure)
Definition at line 199 of file omx_symbianoutputstreamsink_component.c.
References omx_base_component_SetConfig().
Referenced by omx_symbianoutputstreamsink_component_Constructor().
OMX_ERRORTYPE omx_symbianoutputstreamsink_component_SetParameter (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nParamIndex, OMX_IN OMX_PTR ComponentParameterStructure)
Definition at line 218 of file omx_symbianoutputstreamsink_component.c.
References checkHeader(), DEB_LEV_ERR, DEB_LEV_SIMPLE_SEQ, DEBUG, err, OMX_AUDIO_PARAM_PORTFORMATTYPE::nPortIndex, OMX_AUDIO_PARAM_PCMMODETYPE::nPortIndex, OMX_AUDIO_PARAM_MP3TYPE::nPortIndex, omx_base_component_ParameterSanityCheck(), omx_base_component_SetParameter(), OMX_BASE_SINK_INPUTPORT_INDEX, OMX_ErrorBadParameter, OMX_ErrorBadPortIndex, OMX_ErrorNone, OMX_IndexParamAudioInit, OMX_IndexParamAudioMp3, OMX_IndexParamAudioPcm, OMX_IndexParamAudioPortFormat, OMX_PortDomainAudio, and OMX_COMPONENTTYPE::pComponentPrivate.
Referenced by omx_symbianoutputstreamsink_component_Constructor().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1