OpenMAXBellagio: omx_base_audio_port.h File Reference
omx_base_audio_port.h File Reference
#include "omx_classmagic.h"
#include "omx_base_port.h"
Data Structures
struct omx_base_audio_PortType
Macros
#define omx_base_audio_PortType_FIELDS
Typedefs
typedef struct
omx_base_audio_PortType omx_base_audio_PortType
the base audio domain structure that describes each port.
Functions
OMX_ERRORTYPE base_audio_port_Constructor (OMX_COMPONENTTYPE *openmaxStandComp, omx_base_PortType **openmaxStandPort, OMX_U32 nPortIndex, OMX_BOOL isInput)
the base contructor for the generic OpenMAX ST Audio port
OMX_ERRORTYPE base_audio_port_Destructor (omx_base_PortType *openmaxStandPort)
the base audio port destructor for the generic OpenMAX ST Audio port
Detailed Description
Base Audio Port class for OpenMAX ports to be used in derived components.
Copyright (C) 2007-2008 STMicroelectronics Copyright (C) 2007-2008 Nokia Corporation and/or its subsidiary(-ies).
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Date:
2008-07-07 14:30:38 +0200 (Mon, 07 Jul 2008)
Revision
Rev:
562
Author
Author:
gsent
Definition in file omx_base_audio_port.h.
Macro Definition Documentation
#define omx_base_audio_PortType_FIELDS
Value:
omx_base_PortType_FIELDS \ \
  OMX_AUDIO_PARAM_PORTFORMATTYPE sAudioParam;
Definition at line 45 of file omx_base_audio_port.h.
Typedef Documentation
typedef struct omx_base_audio_PortType omx_base_audio_PortType
the base audio domain structure that describes each port.
The data structure is derived from base port class and contain audio domain specific parameters. Other elements can be added in the derived components structures.
Definition at line 44 of file omx_base_audio_port.h.
Function Documentation
OMX_ERRORTYPE base_audio_port_Constructor (OMX_COMPONENTTYPE * openmaxStandComp, omx_base_PortType ** openmaxStandPort, OMX_U32 nPortIndex, OMX_BOOL isInput)
the base contructor for the generic OpenMAX ST Audio port
This function is executed by the component that uses a port. The parameter contains the info about the component. It takes care of constructing the instance of the port and every object needed by the base port.
Parameters
openmaxStandComp pointer to the Handle of the component
openmaxStandPort the ST port to be initialized
nPortIndex Index of the port to be constructed
isInput specifices if the port is an input or an output
Returns
OMX_ErrorInsufficientResources if a memory allocation fails
the base contructor for the generic OpenMAX ST Audio port
This function is executed by the component that uses a port. The parameter contains the info about the component. It takes care of constructing the instance of the port and every object needed by the base port.
Parameters
openmaxStandComp pointer to the Handle of the component
openmaxStandPort the ST port to be initialized
nPortIndex Index of the port to be constructed
isInput specifices if the port is an input or an output
Returns
OMX_ErrorInsufficientResources if a memory allocation fails
Definition at line 55 of file omx_base_audio_port.c.
References OMX_PARAM_PORTDEFINITIONTYPE::audio, base_audio_port_Destructor(), base_port_Constructor(), OMX_AUDIO_PORTDEFINITIONTYPE::bFlagErrorConcealment, OMX_AUDIO_PORTDEFINITIONTYPE::cMIMEType, DEFAULT_IN_BUFFER_SIZE, DEFAULT_MIME_STRING_LENGTH, DEFAULT_OUT_BUFFER_SIZE, OMX_PARAM_PORTDEFINITIONTYPE::eDomain, OMX_AUDIO_PORTDEFINITIONTYPE::eEncoding, OMX_AUDIO_PARAM_PORTFORMATTYPE::eEncoding, OMX_PARAM_PORTDEFINITIONTYPE::format, malloc(), OMX_PARAM_PORTDEFINITIONTYPE::nBufferSize, OMX_AUDIO_PARAM_PORTFORMATTYPE::nIndex, OMX_AUDIO_PARAM_PORTFORMATTYPE::nPortIndex, OMX_AUDIO_CodingUnused, OMX_ErrorInsufficientResources, OMX_ErrorNone, OMX_FALSE, OMX_PortDomainAudio, OMX_TRUE, OMX_AUDIO_PORTDEFINITIONTYPE::pNativeRender, omx_base_audio_PortType::PortDestructor, omx_base_audio_PortType::sAudioParam, setHeader(), and omx_base_audio_PortType::sPortParam.
Referenced by omx_alsasink_component_Constructor(), omx_alsasrc_component_Constructor(), omx_audio_mixer_component_Constructor(), omx_audiodec_component_Constructor(), omx_filereader_component_Constructor(), omx_maddec_component_Constructor(), omx_parser3gp_component_Constructor(), omx_volume_component_Constructor(), and omx_vorbisdec_component_Constructor().
OMX_ERRORTYPE base_audio_port_Destructor (omx_base_PortType * openmaxStandPort)
the base audio port destructor for the generic OpenMAX ST Audio port
This function is executed by the component that uses a port. The parameter contains the info about the port. It takes care of destructing the instance of the port
Parameters
openmaxStandPort the ST port to be destructed
Returns
OMX_ErrorNone
the base audio port destructor for the generic OpenMAX ST Audio port
This function is executed by the component that uses a port. The parameter contains the info about the port. It takes care of destructing the instance of the port
Parameters
openmaxStandPort the ST port to be destructed
Returns
OMX_ErrorNone
Definition at line 102 of file omx_base_audio_port.c.
References OMX_PARAM_PORTDEFINITIONTYPE::audio, base_port_Destructor(), OMX_AUDIO_PORTDEFINITIONTYPE::cMIMEType, OMX_PARAM_PORTDEFINITIONTYPE::format, free(), OMX_ErrorNone, and omx_base_PortType::sPortParam.
Referenced by base_audio_port_Constructor().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1