OpenMAXBellagio: omx_base_image_port.h File Reference
omx_base_image_port.h File Reference
#include "omx_classmagic.h"
#include "omx_base_port.h"
Data Structures
struct omx_base_image_PortType
Macros
#define omx_base_image_PortType_FIELDS
Typedefs
typedef struct
omx_base_image_PortType omx_base_image_PortType
the base image domain structure that describes each port.
Functions
OMX_ERRORTYPE base_image_port_Constructor (OMX_COMPONENTTYPE *openmaxStandComp, omx_base_PortType **openmaxStandPort, OMX_U32 nPortIndex, OMX_BOOL isInput)
the base contructor for the generic OpenMAX ST Image port
OMX_ERRORTYPE base_image_port_Destructor (omx_base_PortType *openmaxStandPort)
the base image port destructor for the generic OpenMAX ST Image port
Detailed Description
Base Image Port class for OpenMAX ports to be used in derived components.
Copyright (C) 2007-2008 STMicroelectronics Copyright (C) 2007-2008 Nokia Corporation and/or its subsidiary(-ies).
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Date:
2008-08-29 06:15:38 +0200 (Fri, 29 Aug 2008)
Revision
Rev:
585
Author
Author:
pankaj_sen
Definition in file omx_base_image_port.h.
Macro Definition Documentation
#define omx_base_image_PortType_FIELDS
Value:
omx_base_PortType_FIELDS \ \
  OMX_IMAGE_PARAM_PORTFORMATTYPE sImageParam;
Definition at line 45 of file omx_base_image_port.h.
Typedef Documentation
typedef struct omx_base_image_PortType omx_base_image_PortType
the base image domain structure that describes each port.
The data structure is derived from base port class and contain image domain specific parameters. Other elements can be added in the derived components structures.
Definition at line 44 of file omx_base_image_port.h.
Function Documentation
OMX_ERRORTYPE base_image_port_Constructor (OMX_COMPONENTTYPE * openmaxStandComp, omx_base_PortType ** openmaxStandPort, OMX_U32 nPortIndex, OMX_BOOL isInput)
the base contructor for the generic OpenMAX ST Image port
This function is executed by the component that uses a port. The parameter contains the info about the component. It takes care of constructing the instance of the port and every object needed by the base port.
Parameters
openmaxStandComp pointer to the Handle of the component
openmaxStandPort the ST port to be initialized
nPortIndex Index of the port to be constructed
isInput specifices if the port is an input or an output
Returns
OMX_ErrorInsufficientResources if a memory allocation fails
the base contructor for the generic OpenMAX ST Image port
This function is executed by the component that uses a port. The parameter contains the info about the component. It takes care of constructing the instance of the port and every object needed by the base port.
Parameters
openmaxStandComp pointer to the Handle of the component
openmaxStandPort the ST port to be initialized
nPortIndex Index of the port to be constructed
isInput specifices if the port is an input or an output
Returns
OMX_ErrorInsufficientResources if a memory allocation fails
Definition at line 55 of file omx_base_image_port.c.
References base_image_port_Destructor(), base_port_Constructor(), OMX_IMAGE_PORTDEFINITIONTYPE::bFlagErrorConcealment, OMX_IMAGE_PORTDEFINITIONTYPE::cMIMEType, DEFAULT_IN_BUFFER_SIZE, DEFAULT_MIME_STRING_LENGTH, DEFAULT_OUT_BUFFER_SIZE, OMX_IMAGE_PORTDEFINITIONTYPE::eCompressionFormat, OMX_IMAGE_PARAM_PORTFORMATTYPE::eCompressionFormat, OMX_PARAM_PORTDEFINITIONTYPE::eDomain, OMX_PARAM_PORTDEFINITIONTYPE::format, OMX_PARAM_PORTDEFINITIONTYPE::image, malloc(), OMX_PARAM_PORTDEFINITIONTYPE::nBufferSize, OMX_IMAGE_PARAM_PORTFORMATTYPE::nIndex, OMX_IMAGE_PARAM_PORTFORMATTYPE::nPortIndex, OMX_ErrorInsufficientResources, OMX_ErrorNone, OMX_FALSE, OMX_IMAGE_CodingUnused, OMX_PortDomainImage, OMX_TRUE, OMX_IMAGE_PORTDEFINITIONTYPE::pNativeRender, omx_base_image_PortType::PortDestructor, setHeader(), omx_base_image_PortType::sImageParam, and omx_base_image_PortType::sPortParam.
Referenced by omx_jpegdec_component_Constructor(), and omx_jpegenc_component_Constructor().
OMX_ERRORTYPE base_image_port_Destructor (omx_base_PortType * openmaxStandPort)
the base image port destructor for the generic OpenMAX ST Image port
This function is executed by the component that uses a port. The parameter contains the info about the port. It takes care of destructing the instance of the port
Parameters
openmaxStandPort the ST port to be destructed
Returns
OMX_ErrorNone
the base image port destructor for the generic OpenMAX ST Image port
This function is executed by the component that uses a port. The parameter contains the info about the port. It takes care of destructing the instance of the port
Parameters
openmaxStandPort the ST port to be destructed
Returns
OMX_ErrorNone
Definition at line 102 of file omx_base_image_port.c.
References base_port_Destructor(), OMX_IMAGE_PORTDEFINITIONTYPE::cMIMEType, OMX_PARAM_PORTDEFINITIONTYPE::format, free(), OMX_PARAM_PORTDEFINITIONTYPE::image, OMX_ErrorNone, and omx_base_PortType::sPortParam.
Referenced by base_image_port_Constructor().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1