OpenMAXBellagio: omx_filereader_component.c File Reference
omx_filereader_component.c File Reference
#include <omxcore.h>
#include <omx_base_audio_port.h>
#include <omx_filereader_component.h>
Macros
#define MAX_COMPONENT_FILEREADER 1
#define DEFAULT_FILENAME_LENGTH 256
Functions
OMX_ERRORTYPE omx_filereader_component_Constructor (OMX_COMPONENTTYPE *openmaxStandComp, OMX_STRING cComponentName)
OMX_ERRORTYPE omx_filereader_component_Destructor (OMX_COMPONENTTYPE *openmaxStandComp)
OMX_ERRORTYPE omx_filereader_component_Init (OMX_COMPONENTTYPE *openmaxStandComp)
OMX_ERRORTYPE omx_filereader_component_Deinit (OMX_COMPONENTTYPE *openmaxStandComp)
void omx_filereader_component_BufferMgmtCallback (OMX_COMPONENTTYPE *openmaxStandComp, OMX_BUFFERHEADERTYPE *pOutputBuffer)
OMX_ERRORTYPE omx_filereader_component_SetParameter (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nParamIndex, OMX_IN OMX_PTR ComponentParameterStructure)
OMX_ERRORTYPE omx_filereader_component_GetParameter (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nParamIndex, OMX_INOUT OMX_PTR ComponentParameterStructure)
OMX_ERRORTYPE omx_filereader_component_MessageHandler (OMX_COMPONENTTYPE *openmaxStandComp, internalRequestMessageType *message)
OMX_ERRORTYPE omx_filereader_component_SetConfig (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nIndex, OMX_IN OMX_PTR pComponentConfigStructure)
OMX_ERRORTYPE omx_filereader_component_GetConfig (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nIndex, OMX_IN OMX_PTR pComponentConfigStructure)
OMX_ERRORTYPE omx_filereader_component_GetExtensionIndex (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_STRING cParameterName, OMX_OUT OMX_INDEXTYPE *pIndexType)
Detailed Description
OpenMAX file reader component. This component is an file reader that detects the input file format so that client calls the appropriate decoder.
Copyright (C) 2007-2008 STMicroelectronics Copyright (C) 2007-2008 Nokia Corporation and/or its subsidiary(-ies).
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Date:
2008-09-11 15:28:59 +0200 (Thu, 11 Sep 2008)
Revision
Rev:
614
Author
Author:
gsent
Definition in file omx_filereader_component.c.
Macro Definition Documentation
#define DEFAULT_FILENAME_LENGTH 256
Definition at line 40 of file omx_filereader_component.c.
Referenced by omx_filereader_component_Constructor(), and omx_filereader_component_SetParameter().
#define MAX_COMPONENT_FILEREADER 1
Definition at line 35 of file omx_filereader_component.c.
Referenced by omx_filereader_component_Constructor().
Function Documentation
void omx_filereader_component_BufferMgmtCallback (OMX_COMPONENTTYPE * openmaxStandComp, OMX_BUFFERHEADERTYPE * pOutputBuffer)
This function processes the input file and returns packet by packet as an output data this packet is used in audio decoder component for decoding
copying the packetized data in the output buffer that will be decoded in the decoder component
return the current output buffer
Definition at line 267 of file omx_filereader_component.c.
References DEB_LEV_ERR, DEB_LEV_FULL_SEQ, DEB_LEV_FUNCTION_NAME, DEB_LEV_SIMPLE_SEQ, DEBUG, error(), OMX_BUFFERHEADERTYPE::nFilledLen, OMX_BUFFERHEADERTYPE::nFlags, OMX_BUFFERHEADERTYPE::nOffset, OMX_BUFFERHEADERTYPE::nTimeStamp, OMX_BUFFERFLAG_EOS, OMX_FALSE, OMX_StateExecuting, OMX_TRUE, OMX_BUFFERHEADERTYPE::pBuffer, OMX_COMPONENTTYPE::pComponentPrivate, and tsem_down().
Referenced by omx_filereader_component_Constructor().
OMX_ERRORTYPE omx_filereader_component_Constructor (OMX_COMPONENTTYPE * openmaxStandComp, OMX_STRING cComponentName)
The Constructor
Allocate Ports and call port constructor.
for the moment, the file reader works with audio component so the domain is set to audio in future it may be assigned after checking the input file format or there can be seperate file reader of video component
Definition at line 44 of file omx_filereader_component.c.
References base_audio_port_Constructor(), DEB_LEV_FUNCTION_NAME, DEBUG, DEFAULT_FILENAME_LENGTH, DEFAULT_OUT_BUFFER_SIZE, err, OMX_COMPONENTTYPE::GetConfig, OMX_COMPONENTTYPE::GetExtensionIndex, OMX_COMPONENTTYPE::GetParameter, MAX_COMPONENT_FILEREADER, OMX_PARAM_PORTDEFINITIONTYPE::nBufferSize, OMX_AUDIO_CodingMP3, omx_base_source_Constructor(), OMX_BASE_SOURCE_OUTPUTPORT_INDEX, OMX_ErrorInsufficientResources, OMX_ErrorNone, OMX_FALSE, omx_filereader_component_BufferMgmtCallback(), omx_filereader_component_Destructor(), omx_filereader_component_GetConfig(), omx_filereader_component_GetExtensionIndex(), omx_filereader_component_GetParameter(), omx_filereader_component_MessageHandler(), omx_filereader_component_SetConfig(), omx_filereader_component_SetParameter(), OMX_PortDomainAudio, OMX_COMPONENTTYPE::pComponentPrivate, OMX_COMPONENTTYPE::SetConfig, setHeader(), OMX_COMPONENTTYPE::SetParameter, omx_base_audio_PortType::sPortParam, and tsem_init().
Referenced by omx_component_library_Setup().
OMX_ERRORTYPE omx_filereader_component_Deinit (OMX_COMPONENTTYPE * openmaxStandComp)
The DeInitialization function
closing input file
Definition at line 248 of file omx_filereader_component.c.
References DEB_LEV_FUNCTION_NAME, DEBUG, OMX_ErrorNone, OMX_FALSE, OMX_COMPONENTTYPE::pComponentPrivate, and tsem_reset().
Referenced by omx_filereader_component_MessageHandler().
OMX_ERRORTYPE omx_filereader_component_Destructor (OMX_COMPONENTTYPE * openmaxStandComp)
The Destructor
Definition at line 131 of file omx_filereader_component.c.
References DEB_LEV_FUNCTION_NAME, DEBUG, free(), omx_base_source_Destructor(), OMX_PortDomainAudio, OMX_COMPONENTTYPE::pComponentPrivate, and tsem_deinit().
Referenced by omx_filereader_component_Constructor().
OMX_ERRORTYPE omx_filereader_component_GetConfig (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nIndex, OMX_IN OMX_PTR pComponentConfigStructure)
setting configurations
Definition at line 520 of file omx_filereader_component.c.
References OMX_VENDOR_EXTRADATATYPE::nDataSize, OMX_VENDOR_EXTRADATATYPE::nPortIndex, omx_base_component_GetConfig(), OMX_ErrorNone, OMX_IndexVendorAudioExtraData, OMX_COMPONENTTYPE::pComponentPrivate, and OMX_VENDOR_EXTRADATATYPE::pData.
Referenced by omx_filereader_component_Constructor().
OMX_ERRORTYPE omx_filereader_component_GetExtensionIndex (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_STRING cParameterName, OMX_OUT OMX_INDEXTYPE * pIndexType)
Definition at line 542 of file omx_filereader_component.c.
References DEB_LEV_FUNCTION_NAME, DEBUG, OMX_ErrorBadParameter, OMX_ErrorNone, OMX_IndexVendorAudioExtraData, and OMX_IndexVendorFileReadInputFilename.
Referenced by omx_filereader_component_Constructor().
OMX_ERRORTYPE omx_filereader_component_GetParameter (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nParamIndex, OMX_INOUT OMX_PTR ComponentParameterStructure)
Definition at line 404 of file omx_filereader_component.c.
References checkHeader(), DEB_LEV_SIMPLE_SEQ, DEBUG, err, OMX_AUDIO_PARAM_PORTFORMATTYPE::nPortIndex, omx_base_component_GetParameter(), OMX_BASE_SOURCE_OUTPUTPORT_INDEX, OMX_ErrorBadParameter, OMX_ErrorBadPortIndex, OMX_ErrorNone, OMX_IndexParamAudioInit, OMX_IndexParamAudioPortFormat, OMX_IndexVendorFileReadInputFilename, OMX_PortDomainAudio, OMX_COMPONENTTYPE::pComponentPrivate, and omx_base_audio_PortType::sAudioParam.
Referenced by omx_filereader_component_Constructor().
OMX_ERRORTYPE omx_filereader_component_Init (OMX_COMPONENTTYPE * openmaxStandComp)
The Initialization function
initialization of file reader component private data structures
opening the input file whose name is already set via setParameter
initialization for buff mgmt callback function
send callback regarding codec context extradata which will be required to open the codec in the audio decoder component
Definition at line 162 of file omx_filereader_component.c.
References DEB_LEV_ERR, DEB_LEV_FUNCTION_NAME, DEB_LEV_SIMPLE_SEQ, DEBUG, error(), free(), OMX_VENDOR_EXTRADATATYPE::nDataSize, OMX_VENDOR_EXTRADATATYPE::nPortIndex, OMX_AUDIO_CodingAAC, OMX_AUDIO_CodingMP3, OMX_AUDIO_CodingVORBIS, OMX_ErrorBadParameter, OMX_ErrorFormatNotDetected, OMX_ErrorNone, OMX_EventError, OMX_EventPortFormatDetected, OMX_EventPortSettingsChanged, OMX_FALSE, OMX_IndexParamAudioPortFormat, OMX_IndexParamCommonExtraQuantData, OMX_TRUE, OMX_COMPONENTTYPE::pComponentPrivate, OMX_VENDOR_EXTRADATATYPE::pData, and tsem_up().
Referenced by omx_filereader_component_MessageHandler().
OMX_ERRORTYPE omx_filereader_component_MessageHandler (OMX_COMPONENTTYPE * openmaxStandComp, internalRequestMessageType * message)
This function initializes and deinitializes the library related initialization needed for file parsing
Definition at line 451 of file omx_filereader_component.c.
References DEB_LEV_ERR, DEB_LEV_SIMPLE_SEQ, DEBUG, err, internalRequestMessageType::messageParam, internalRequestMessageType::messageType, omx_base_component_MessageHandler(), OMX_CommandStateSet, OMX_ErrorNone, omx_filereader_component_Deinit(), omx_filereader_component_Init(), OMX_StateExecuting, OMX_StateIdle, and OMX_COMPONENTTYPE::pComponentPrivate.
Referenced by omx_filereader_component_Constructor().
OMX_ERRORTYPE omx_filereader_component_SetConfig (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nIndex, OMX_IN OMX_PTR pComponentConfigStructure)
setting configurations
Definition at line 481 of file omx_filereader_component.c.
References checkHeader(), DEB_LEV_ERR, DEBUG, err, OMX_TIME_CONFIG_TIMESTAMPTYPE::nPortIndex, omx_base_component_SetConfig(), OMX_ErrorBadPortIndex, OMX_ErrorNone, OMX_IndexConfigTimePosition, OMX_PortDomainAudio, and OMX_COMPONENTTYPE::pComponentPrivate.
Referenced by omx_filereader_component_Constructor().
OMX_ERRORTYPE omx_filereader_component_SetParameter (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nParamIndex, OMX_IN OMX_PTR ComponentParameterStructure)
determine the audio coding type
now set the port parameters according to selected audio coding type
Definition at line 316 of file omx_filereader_component.c.
References OMX_PARAM_PORTDEFINITIONTYPE::audio, OMX_AUDIO_PORTDEFINITIONTYPE::cMIMEType, DEB_LEV_ERR, DEB_LEV_SIMPLE_SEQ, DEBUG, DEFAULT_FILENAME_LENGTH, OMX_AUDIO_PORTDEFINITIONTYPE::eEncoding, OMX_AUDIO_PARAM_PORTFORMATTYPE::eEncoding, err, OMX_PARAM_PORTDEFINITIONTYPE::format, free(), OMX_AUDIO_PARAM_PORTFORMATTYPE::nPortIndex, OMX_AUDIO_PARAM_MP3TYPE::nPortIndex, OMX_AUDIO_CodingAAC, OMX_AUDIO_CodingMP3, OMX_AUDIO_CodingVORBIS, omx_base_component_ParameterSanityCheck(), omx_base_component_SetParameter(), OMX_BASE_SOURCE_OUTPUTPORT_INDEX, OMX_ErrorBadParameter, OMX_ErrorBadPortIndex, OMX_ErrorNone, OMX_FALSE, OMX_IndexParamAudioMp3, OMX_IndexParamAudioPortFormat, OMX_IndexVendorFileReadInputFilename, OMX_COMPONENTTYPE::pComponentPrivate, omx_base_audio_PortType::sAudioParam, and omx_base_audio_PortType::sPortParam.
Referenced by omx_filereader_component_Constructor().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1