OpenMAXBellagio: omx_base_clock_port.h File Reference
omx_base_clock_port.h File Reference
#include "omx_classmagic.h"
#include "omx_base_port.h"
Data Structures
struct omx_base_clock_PortType
Macros
#define omx_base_clock_PortType_FIELDS
Typedefs
typedef struct
omx_base_clock_PortType omx_base_clock_PortType
the base clock domain structure that describes each port.
Functions
OMX_ERRORTYPE base_clock_port_Constructor (OMX_COMPONENTTYPE *openmaxStandComp, omx_base_PortType **openmaxStandPort, OMX_U32 nPortIndex, OMX_BOOL isInput)
the base contructor for the generic openmax ST clock port
OMX_ERRORTYPE base_clock_port_Destructor (omx_base_PortType *openmaxStandPort)
the base clock port destructor for the generic openmax ST clock port
OMX_ERRORTYPE base_clock_port_SendBufferFunction (omx_base_PortType *openmaxStandPort, OMX_BUFFERHEADERTYPE *pBuffer)
the entry point for sending buffers to the port
Detailed Description
Base Clock Port class for OpenMAX clock ports to be used in derived components.
Copyright (C) 2007-2008 STMicroelectronics Copyright (C) 2007-2008 Nokia Corporation and/or its subsidiary(-ies).
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Date:
2008-07-04 11:48:31 +0200 (Fri, 04 Jul 2008)
Revision
Rev:
560
Author
Author:
gsent
Definition in file omx_base_clock_port.h.
Macro Definition Documentation
#define omx_base_clock_PortType_FIELDS
Value:
omx_base_PortType_FIELDS \
  OMX_TIME_CONFIG_TIMESTAMPTYPE        sTimeStamp;   \
  OMX_TIME_MEDIATIMETYPE               sMediaTime; \
  OMX_TIME_CONFIG_MEDIATIMEREQUESTTYPE sMediaTimeRequest; \
  OMX_OTHER_PARAM_PORTFORMATTYPE       sOtherParam;
Domain specific (other) OpenMAX port parameter
Definition at line 47 of file omx_base_clock_port.h.
Typedef Documentation
typedef struct omx_base_clock_PortType omx_base_clock_PortType
the base clock domain structure that describes each port.
The data structure is derived from base port class and contain clock domain specific parameters. Other elements can be added in the derived components structures.
Parameters
sOtherParam Domain specific (other) OpenMAX port parameter
Definition at line 46 of file omx_base_clock_port.h.
Function Documentation
OMX_ERRORTYPE base_clock_port_Constructor (OMX_COMPONENTTYPE * openmaxStandComp, omx_base_PortType ** openmaxStandPort, OMX_U32 nPortIndex, OMX_BOOL isInput)
the base contructor for the generic openmax ST clock port
This function is executed by the component that uses a port. The parameter contains the info about the component. It takes care of constructing the instance of the port and every object needed by the base port.
Parameters
openmaxStandComp pointer to the Handle of the component
openmaxStandPort the ST port to be initialized
nPortIndex Index of the port to be constructed
isInput specifices if the port is an input or an output
Returns
OMX_ErrorInsufficientResources if a memory allocation fails
the base contructor for the generic openmax ST clock port
This function is executed by the component that uses a port. The parameter contains the info about the component. It takes care of constructing the instance of the port and every object needed by the base port.
Parameters
openmaxStandComp pointer to the Handle of the component
openmaxStandPort the ST port to be initialized
nPortIndex Index of the port to be constructed
isInput specifices if the port is an input or an output
Returns
OMX_ErrorInsufficientResources if a memory allocation fails
Definition at line 54 of file omx_base_clock_port.c.
References base_clock_port_Destructor(), base_clock_port_SendBufferFunction(), base_port_Constructor(), OMX_PARAM_PORTDEFINITIONTYPE::eDomain, OMX_OTHER_PORTDEFINITIONTYPE::eFormat, OMX_OTHER_PARAM_PORTFORMATTYPE::eFormat, OMX_PARAM_PORTDEFINITIONTYPE::format, OMX_PARAM_PORTDEFINITIONTYPE::nBufferCountActual, OMX_PARAM_PORTDEFINITIONTYPE::nBufferCountMin, OMX_PARAM_PORTDEFINITIONTYPE::nBufferSize, OMX_TIME_MEDIATIMETYPE::nClientPrivate, OMX_OTHER_PARAM_PORTFORMATTYPE::nIndex, OMX_TIME_CONFIG_MEDIATIMEREQUESTTYPE::nOffset, OMX_TIME_MEDIATIMETYPE::nOffset, OMX_TIME_CONFIG_TIMESTAMPTYPE::nPortIndex, OMX_TIME_CONFIG_MEDIATIMEREQUESTTYPE::nPortIndex, OMX_OTHER_PARAM_PORTFORMATTYPE::nPortIndex, OMX_TIME_CONFIG_TIMESTAMPTYPE::nTimestamp, OMX_ErrorInsufficientResources, OMX_ErrorNone, OMX_OTHER_FormatTime, OMX_PortDomainOther, OMX_PARAM_PORTDEFINITIONTYPE::other, OMX_TIME_CONFIG_MEDIATIMEREQUESTTYPE::pClientPrivate, omx_base_clock_PortType::Port_SendBufferFunction, omx_base_clock_PortType::PortDestructor, setHeader(), omx_base_clock_PortType::sMediaTime, omx_base_clock_PortType::sMediaTimeRequest, omx_base_clock_PortType::sOtherParam, omx_base_clock_PortType::sPortParam, omx_base_clock_PortType::sTimeStamp, and OMX_TIME_MEDIATIMETYPE::xScale.
Referenced by omx_alsasink_component_Constructor(), omx_clocksrc_component_Constructor(), omx_fbdev_sink_component_Constructor(), and omx_parser3gp_component_Constructor().
OMX_ERRORTYPE base_clock_port_Destructor (omx_base_PortType * openmaxStandPort)
the base clock port destructor for the generic openmax ST clock port
This function is executed by the component that uses a port. The parameter contains the info about the port. It takes care of destructing the instance of the port
Parameters
openmaxStandPort the ST port to be destructed
Returns
OMX_ErrorNone
Definition at line 115 of file omx_base_clock_port.c.
References base_port_Destructor(), and OMX_ErrorNone.
Referenced by base_clock_port_Constructor().
OMX_ERRORTYPE base_clock_port_SendBufferFunction (omx_base_PortType * openmaxStandPort, OMX_BUFFERHEADERTYPE * pBuffer)
the entry point for sending buffers to the port
This function can be called by the EmptyThisBuffer or FillThisBuffer. It depends on the nature of the port, that can be an input or output port.
Definition at line 127 of file omx_base_clock_port.c.
References omx_base_component_PrivateType::bMgmtSem, checkHeader(), DEB_LEV_ERR, DEB_LEV_FULL_SEQ, DEB_LEV_FUNCTION_NAME, DEB_LEV_PARAMS, DEBUG, OMX_PARAM_PORTDEFINITIONTYPE::eDir, err, omx_base_component_PrivateType::name, OMX_PARAM_PORTDEFINITIONTYPE::nBufferCountActual, OMX_BUFFERHEADERTYPE::nInputPortIndex, OMX_BUFFERHEADERTYPE::nOutputPortIndex, OMX_PARAM_PORTDEFINITIONTYPE::nPortIndex, OMX_DirInput, OMX_ErrorBadParameter, OMX_ErrorBadPortIndex, OMX_ErrorIncorrectStateOperation, OMX_ErrorInvalidState, OMX_ErrorNone, OMX_FALSE, OMX_StateExecuting, OMX_StateIdle, OMX_StateInvalid, OMX_StatePause, OMX_TransStateExecutingToIdle, OMX_TRUE, OMX_BUFFERHEADERTYPE::pBuffer, omx_base_PortType::pBufferQueue, omx_base_PortType::pBufferSem, OMX_COMPONENTTYPE::pComponentPrivate, omx_base_PortType::pInternalBufferStorage, PORT_IS_BEING_DISABLED, PORT_IS_BEING_FLUSHED, PORT_IS_BUFFER_SUPPLIER, PORT_IS_ENABLED, PORT_IS_TUNNELED, PORT_IS_TUNNELED_N_BUFFER_SUPPLIER, queue(), omx_base_PortType::ReturnBufferFunction, omx_base_PortType::sPortParam, omx_base_PortType::standCompContainer, omx_base_component_PrivateType::state, omx_base_component_PrivateType::transientState, and tsem_up().
Referenced by base_clock_port_Constructor().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1