OpenMAXBellagio: omx_base_source.h File Reference
omx_base_source.h File Reference
#include <OMX_Types.h>
#include <OMX_Component.h>
#include <OMX_Core.h>
#include <pthread.h>
#include "omx_base_component.h"
#include <stdlib.h>
Data Structures
struct omx_base_source_PrivateType
Macros
#define OMX_BASE_SOURCE_OUTPUTPORT_INDEX 0
#define OMX_BASE_SOURCE_OUTPUTPORT_INDEX_1 1
#define OMX_BASE_SOURCE_ALLPORT_INDEX -1
#define omx_base_source_PrivateType_FIELDS
Typedefs
typedef struct
omx_base_source_PrivateType omx_base_source_PrivateType
Functions
OMX_ERRORTYPE omx_base_source_Constructor (OMX_COMPONENTTYPE *openmaxStandComp, OMX_STRING cComponentName)
OMX_ERRORTYPE omx_base_source_Destructor (OMX_COMPONENTTYPE *openmaxStandComp)
void * omx_base_source_BufferMgmtFunction (void *param)
void * omx_base_source_twoport_BufferMgmtFunction (void *param)
Detailed Description
OpenMAX base source component. This component does not perform any multimedia processing. It derives from base component and contains a single port. It can be used as base class for source components.
Copyright (C) 2007-2008 STMicroelectronics Copyright (C) 2007-2008 Nokia Corporation and/or its subsidiary(-ies).
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Date:
2008-08-28 17:50:08 +0200 (Thu, 28 Aug 2008)
Revision
Rev:
583
Author
Author:
gsent
Definition in file omx_base_source.h.
Macro Definition Documentation
#define OMX_BASE_SOURCE_ALLPORT_INDEX -1
OMX_BASE_SOURCE_ALLPORT_INDEX as the standard specifies, the -1 value for port index is used to point to all the ports
Definition at line 53 of file omx_base_source.h.
#define OMX_BASE_SOURCE_OUTPUTPORT_INDEX 0
OMX_BASE_SOURCE_OUTPUTPORT_INDEX is the index of any output port for the derived components
Definition at line 45 of file omx_base_source.h.
Referenced by omx_alsasrc_component_Constructor(), omx_alsasrc_component_GetParameter(), omx_alsasrc_component_SetParameter(), omx_base_source_BufferMgmtFunction(), omx_base_source_twoport_BufferMgmtFunction(), omx_filereader_component_Constructor(), omx_filereader_component_GetParameter(), omx_filereader_component_SetParameter(), omx_parser3gp_component_GetParameter(), omx_parser3gp_component_SetParameter(), omx_videosrc_component_Constructor(), omx_videosrc_component_GetParameter(), omx_videosrc_component_Init(), and omx_videosrc_component_SetParameter().
#define OMX_BASE_SOURCE_OUTPUTPORT_INDEX_1 1
OMX_BASE_SPLITTER_OUTPUTPORT_INDEX_1 is the index of any output port for the derived components
Definition at line 49 of file omx_base_source.h.
Referenced by omx_base_source_twoport_BufferMgmtFunction(), omx_parser3gp_component_GetParameter(), and omx_parser3gp_component_SetParameter().
#define omx_base_source_PrivateType_FIELDS
Value:
omx_base_component_PrivateType_FIELDS \ \
  void (*BufferMgmtCallback)(OMX_COMPONENTTYPE* openmaxStandComp, OMX_BUFFERHEADERTYPE* outputbuffer);
Definition at line 58 of file omx_base_source.h.
Typedef Documentation
typedef struct omx_base_source_PrivateType omx_base_source_PrivateType
base source component private structure.
Definition at line 57 of file omx_base_source.h.
Function Documentation
void* omx_base_source_BufferMgmtFunction (void * param)
This is the central function for component processing. It is executed in a separate thread, is synchronized with semaphores at each port, those are released each time a new buffer is available on the given port.
Definition at line 71 of file omx_base_source.c.
References omx_base_component_PrivateType::callbackData, omx_base_component_PrivateType::callbacks, DEB_LEV_ERR, DEB_LEV_FULL_SEQ, DEB_LEV_FUNCTION_NAME, DEB_LEV_SIMPLE_SEQ, DEBUG, dequeue(), OMX_CALLBACKTYPE::EventHandler, OMX_BASE_SOURCE_OUTPUTPORT_INDEX, OMX_BUFFERFLAG_EOS, OMX_EventBufferFlag, OMX_EventMark, OMX_FALSE, OMX_StateExecuting, OMX_StateIdle, OMX_StateInvalid, OMX_StateLoaded, OMX_StatePause, OMX_TransStateLoadedToIdle, OMX_TRUE, omx_base_PortType::pBufferQueue, omx_base_PortType::pBufferSem, OMX_COMPONENTTYPE::pComponentPrivate, PORT_IS_BEING_FLUSHED, omx_base_PortType::ReturnBufferFunction, omx_base_component_PrivateType::state, omx_base_component_PrivateType::transientState, tsem_down(), tsem_up(), and tsem_wait().
Referenced by omx_base_source_Constructor().
OMX_ERRORTYPE omx_base_source_Constructor (OMX_COMPONENTTYPE * openmaxStandComp, OMX_STRING cComponentName)
Base source contructor
Definition at line 35 of file omx_base_source.c.
References omx_base_source_PrivateType::BufferMgmtFunction, err, omx_base_component_Constructor(), omx_base_source_BufferMgmtFunction(), OMX_ErrorInsufficientResources, OMX_ErrorNone, and OMX_COMPONENTTYPE::pComponentPrivate.
Referenced by omx_alsasrc_component_Constructor(), omx_camera_source_component_Constructor(), omx_clocksrc_component_Constructor(), omx_filereader_component_Constructor(), omx_parser3gp_component_Constructor(), and omx_videosrc_component_Constructor().
OMX_ERRORTYPE omx_base_source_Destructor (OMX_COMPONENTTYPE * openmaxStandComp)
The base source destructor. It simply calls the base destructor
Definition at line 61 of file omx_base_source.c.
References omx_base_component_Destructor().
Referenced by omx_alsasrc_component_Destructor(), omx_camera_source_component_Destructor(), omx_clocksrc_component_Destructor(), omx_filereader_component_Destructor(), omx_parser3gp_component_Destructor(), and omx_videosrc_component_Destructor().
void* omx_base_source_twoport_BufferMgmtFunction (void * param)
This is the central function for buffer processing of a two port source component. It is executed in a separate thread, is synchronized with semaphores at each port, those are released each time a new buffer is available on the given port.
Definition at line 194 of file omx_base_source.c.
References omx_base_component_PrivateType::bStateSem, DEB_LEV_ERR, DEB_LEV_FULL_SEQ, DEB_LEV_FUNCTION_NAME, DEB_LEV_SIMPLE_SEQ, DEBUG, dequeue(), OMX_BUFFERHEADERTYPE::hMarkTargetComponent, OMX_BUFFERHEADERTYPE::nFilledLen, OMX_BUFFERHEADERTYPE::nFlags, OMX_PORT_PARAM_TYPE::nPorts, OMX_BASE_SOURCE_OUTPUTPORT_INDEX, OMX_BASE_SOURCE_OUTPUTPORT_INDEX_1, OMX_BUFFERFLAG_EOS, OMX_EventBufferFlag, OMX_EventMark, OMX_FALSE, OMX_PortDomainAudio, OMX_PortDomainImage, OMX_PortDomainOther, OMX_PortDomainVideo, OMX_StateExecuting, OMX_StateIdle, OMX_StateInvalid, OMX_StateLoaded, OMX_StatePause, OMX_TransStateLoadedToIdle, OMX_TRUE, omx_base_PortType::pBufferQueue, omx_base_PortType::pBufferSem, OMX_COMPONENTTYPE::pComponentPrivate, OMX_BUFFERHEADERTYPE::pMarkData, PORT_IS_BEING_FLUSHED, omx_base_PortType::ReturnBufferFunction, omx_base_component_PrivateType::sPortTypesParam, tsem_down(), tsem_up(), and tsem_wait().
Referenced by omx_parser3gp_component_Constructor().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1