OpenMAXBellagio: omx_base_sink.h File Reference
omx_base_sink.h File Reference
#include <OMX_Types.h>
#include <OMX_Component.h>
#include <OMX_Core.h>
#include <pthread.h>
#include "omx_base_component.h"
#include <stdlib.h>
Data Structures
struct omx_base_sink_PrivateType
Macros
#define OMX_BASE_SINK_INPUTPORT_INDEX 0 /* The index of the input port for the derived components */
#define OMX_BASE_SINK_CLOCKPORT_INDEX 1 /* The index of the clock port for the dervied components */
#define OMX_BASE_SINK_ALLPORT_INDEX -1
#define omx_base_sink_PrivateType_FIELDS
Typedefs
typedef struct
omx_base_sink_PrivateType omx_base_sink_PrivateType
Functions
OMX_ERRORTYPE omx_base_sink_Constructor (OMX_COMPONENTTYPE *openmaxStandComp, OMX_STRING cComponentName)
OMX_ERRORTYPE omx_base_sink_Destructor (OMX_COMPONENTTYPE *openmaxStandComp)
void * omx_base_sink_BufferMgmtFunction (void *param)
Detailed Description
OpenMAX base sink component. This component does not perform any multimedia processing. It derives from base component and contains a single port. It can be used as base class for sink components.
Copyright (C) 2007-2008 STMicroelectronics Copyright (C) 2007-2008 Nokia Corporation and/or its subsidiary(-ies).
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Date:
2008-08-28 17:50:08 +0200 (Thu, 28 Aug 2008)
Revision
Rev:
583
Author
Author:
gsent
Definition in file omx_base_sink.h.
Macro Definition Documentation
#define OMX_BASE_SINK_ALLPORT_INDEX -1
OMX_BASE_SINK_ALLPORT_INDEX as the standard specifies, the -1 value for port index is used to point to all the ports
Definition at line 48 of file omx_base_sink.h.
#define OMX_BASE_SINK_CLOCKPORT_INDEX 1 /* The index of the clock port for the dervied components */
Definition at line 44 of file omx_base_sink.h.
Referenced by omx_alsasink_component_ClockPortHandleFunction(), omx_alsasink_component_port_FlushProcessingBuffers(), omx_alsasink_component_port_SendBufferFunction(), omx_fbdev_sink_component_ClockPortHandleFunction(), omx_fbdev_sink_component_port_FlushProcessingBuffers(), and omx_fbdev_sink_component_port_SendBufferFunction().
#define OMX_BASE_SINK_INPUTPORT_INDEX 0 /* The index of the input port for the derived components */
Definition at line 43 of file omx_base_sink.h.
Referenced by omx_alsasink_component_ClockPortHandleFunction(), omx_alsasink_component_Constructor(), omx_alsasink_component_GetParameter(), omx_alsasink_component_SetParameter(), omx_base_sink_BufferMgmtFunction(), omx_fbdev_sink_component_BufferMgmtCallback(), omx_fbdev_sink_component_ClockPortHandleFunction(), omx_fbdev_sink_component_Constructor(), omx_fbdev_sink_component_GetParameter(), omx_fbdev_sink_component_Init(), omx_fbdev_sink_component_SetConfig(), omx_symbianoutputstreamsink_component_BufferMgmtCallback(), omx_symbianoutputstreamsink_component_Constructor(), omx_symbianoutputstreamsink_component_Destructor(), omx_symbianoutputstreamsink_component_GetParameter(), and omx_symbianoutputstreamsink_component_SetParameter().
#define omx_base_sink_PrivateType_FIELDS
Value:
omx_base_component_PrivateType_FIELDS \ \
  void (*BufferMgmtCallback)(OMX_COMPONENTTYPE* openmaxStandComp, OMX_BUFFERHEADERTYPE* inputbuffer);
Definition at line 53 of file omx_base_sink.h.
Typedef Documentation
typedef struct omx_base_sink_PrivateType omx_base_sink_PrivateType
base sink component private structure.
Definition at line 52 of file omx_base_sink.h.
Function Documentation
void* omx_base_sink_BufferMgmtFunction (void * param)
This is the central function for component processing. It is executed in a separate thread, is synchronized with semaphores at each port, those are released each time a new buffer is available on the given port.
Definition at line 71 of file omx_base_sink.c.
References omx_base_component_PrivateType::callbackData, omx_base_component_PrivateType::callbacks, DEB_LEV_ERR, DEB_LEV_FULL_SEQ, DEB_LEV_FUNCTION_NAME, DEB_LEV_SIMPLE_SEQ, DEBUG, dequeue(), OMX_CALLBACKTYPE::EventHandler, OMX_BASE_SINK_INPUTPORT_INDEX, OMX_BUFFERFLAG_EOS, OMX_EventBufferFlag, OMX_EventMark, OMX_FALSE, OMX_StateExecuting, OMX_StateIdle, OMX_StateInvalid, OMX_StateLoaded, OMX_StatePause, OMX_TransStateLoadedToIdle, OMX_TRUE, omx_base_PortType::pBufferQueue, omx_base_PortType::pBufferSem, OMX_COMPONENTTYPE::pComponentPrivate, PORT_IS_BEING_FLUSHED, omx_base_PortType::ReturnBufferFunction, omx_base_component_PrivateType::state, omx_base_component_PrivateType::transientState, tsem_down(), tsem_up(), and tsem_wait().
Referenced by omx_base_sink_Constructor().
OMX_ERRORTYPE omx_base_sink_Constructor (OMX_COMPONENTTYPE * openmaxStandComp, OMX_STRING cComponentName)
Base sink contructor
Definition at line 35 of file omx_base_sink.c.
References omx_base_sink_PrivateType::BufferMgmtFunction, err, omx_base_component_Constructor(), omx_base_sink_BufferMgmtFunction(), OMX_ErrorInsufficientResources, OMX_ErrorNone, and OMX_COMPONENTTYPE::pComponentPrivate.
Referenced by omx_alsasink_component_Constructor(), omx_fbdev_sink_component_Constructor(), and omx_symbianoutputstreamsink_component_Constructor().
OMX_ERRORTYPE omx_base_sink_Destructor (OMX_COMPONENTTYPE * openmaxStandComp)
The base sink destructor. It simply calls the base destructor
Definition at line 61 of file omx_base_sink.c.
References omx_base_component_Destructor().
Referenced by omx_alsasink_component_Destructor(), omx_fbdev_sink_component_Destructor(), and omx_symbianoutputstreamsink_component_Destructor().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1