OpenMAXBellagio: omxjpegdectest.h File Reference
omxjpegdectest.h File Reference
#include <OMX_Types.h>
#include <OMX_Image.h>
#include <OMX_Core.h>
#include <OMX_Component.h>
#include <pthread.h>
#include <sys/stat.h>
#include <unistd.h>
#include "tsemaphore.h"
Data Structures
struct appPrivateType
Macros
#define INPUT_BUFFER_SIZE 4096 /*Max input buffer size*/
#define OUTPUT_BUFFER_SIZE 304128 /*Max output buffer size*/
#define BUFFER_SIZE 4096
#define FRAME_WIDTH 640
#define FRAME_HEIGHT 480
#define FRAME_BUFFER_SIZE FRAME_WIDTH*FRAME_HEIGHT*3 +54 /* 640 x 480 x 2bytes x(3/2) +54bytes header*/
#define VERSIONMAJOR 1
#define VERSIONMINOR 1
#define VERSIONREVISION 0
#define VERSIONSTEP 0
Typedefs
typedef struct appPrivateType appPrivateType
Functions
OMX_ERRORTYPE jpegDecEventHandler (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_PTR pAppData, OMX_IN OMX_EVENTTYPE eEvent, OMX_IN OMX_U32 nData1, OMX_IN OMX_U32 nData2, OMX_IN OMX_PTR pEventData)
OMX_ERRORTYPE jpegDecEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
OMX_ERRORTYPE jpegDecFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
Macro Definition Documentation
#define BUFFER_SIZE 4096
Definition at line 69 of file omxjpegdectest.h.
#define FRAME_BUFFER_SIZE FRAME_WIDTH*FRAME_HEIGHT*3 +54 /* 640 x 480 x 2bytes x(3/2) +54bytes header*/
Definition at line 72 of file omxjpegdectest.h.
Referenced by main().
#define FRAME_HEIGHT 480
Definition at line 71 of file omxjpegdectest.h.
Referenced by main().
#define FRAME_WIDTH 640
Definition at line 70 of file omxjpegdectest.h.
Referenced by main().
#define INPUT_BUFFER_SIZE 4096 /*Max input buffer size*/
Definition at line 65 of file omxjpegdectest.h.
Referenced by main().
#define OUTPUT_BUFFER_SIZE 304128 /*Max output buffer size*/
Definition at line 66 of file omxjpegdectest.h.
Referenced by main().
#define VERSIONMAJOR 1
Specification version
Definition at line 76 of file omxjpegdectest.h.
#define VERSIONMINOR 1
Definition at line 77 of file omxjpegdectest.h.
#define VERSIONREVISION 0
Definition at line 78 of file omxjpegdectest.h.
#define VERSIONSTEP 0
Definition at line 79 of file omxjpegdectest.h.
Typedef Documentation
typedef struct appPrivateType appPrivateType
Function Documentation
OMX_ERRORTYPE jpegDecEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
Definition at line 310 of file omxjpegdectest.c.
References DEB_LEV_FULL_SEQ, DEB_LEV_SIMPLE_SEQ, DEBUG, err, fd, OMX_BUFFERFLAG_EOS, OMX_EmptyThisBuffer, OMX_ErrorNone, OMX_TRUE, and size.
Referenced by main().
OMX_ERRORTYPE jpegDecEventHandler (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_PTR pAppData, OMX_IN OMX_EVENTTYPE eEvent, OMX_IN OMX_U32 nData1, OMX_IN OMX_U32 nData2, OMX_IN OMX_PTR pEventData)
Definition at line 272 of file omxjpegdectest.c.
References DEB_LEV_PARAMS, DEB_LEV_SIMPLE_SEQ, DEBUG, err, OMX_PARAM_PORTDEFINITIONTYPE::format, appPrivateType::frame_height, appPrivateType::frame_width, OMX_PARAM_PORTDEFINITIONTYPE::nBufferSize, OMX_VIDEO_PORTDEFINITIONTYPE::nFrameHeight, OMX_VIDEO_PORTDEFINITIONTYPE::nFrameWidth, OMX_PARAM_PORTDEFINITIONTYPE::nPortIndex, OMX_ErrorNone, OMX_EventCmdComplete, OMX_EventPortSettingsChanged, OMX_GetConfig, OMX_GetParameter, OMX_IndexParamPortDefinition, appPrivateType::outframe_buffer_size, setHeader(), appPrivateType::stateSem, tsem_up(), and OMX_PARAM_PORTDEFINITIONTYPE::video.
Referenced by main().
OMX_ERRORTYPE jpegDecFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
Definition at line 346 of file omxjpegdectest.c.
References appPrivateType::eosSem, OMX_ErrorNone, outfile, appPrivateType::output_file, and tsem_up().
Referenced by main().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1