OpenMAXBellagio: omxsymbianoutputstreamtest.c File Reference
omxsymbianoutputstreamtest.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <pthread.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <string.h>
#include <OMX_Core.h>
#include <OMX_Component.h>
#include <OMX_Types.h>
#include <OMX_Audio.h>
#include "omxsymbianoutputstreamtest.h"
#include "tsemaphore.h"
Functions
int main (int argc, char **argv)
OMX_ERRORTYPE symbianoutputstreamEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 nData1, OMX_OUT OMX_U32 nData2, OMX_OUT OMX_PTR pEventData)
OMX_ERRORTYPE symbianoutputstreamEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
OMX_ERRORTYPE symbianoutputstreamFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
Variables
appPrivateType * appPriv
Detailed Description
Simple application that uses an OpenMAX Symbian output stream sink component. The application receives a pcm stream from a file or, if not specified, from standard input. The audio stream is inteded as stereo, at 44100 Hz.
Copyright (C) 2006-2008 Nokia Corporation and/or its subsidiary(-ies).
Author
Jaska Uimonen, Diego MELPIGNANO, Pankaj SEN, David SIORPAES, Giulio URLINI
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
2006/06/28: Symbian Output Stream Sink Test version 0.1
Definition in file omxsymbianoutputstreamtest.c.
Function Documentation
int main (int argc, char ** argv)
Ask the core for a handle to the output stream component
Set the number of ports for the sink component
Set the port definition type
Set up the PCM parameters
Definition at line 52 of file omxsymbianoutputstreamtest.c.
References BUFFER_SIZE, callbacks, appPrivateType::condition, DEB_LEV_ERR, DEB_LEV_FULL_SEQ, DEB_LEV_PARAMS, DEBUG, OMX_CALLBACKTYPE::EmptyBufferDone, err, OMX_CALLBACKTYPE::EventHandler, appPrivateType::eventSem, fd, filesize, OMX_CALLBACKTYPE::FillBufferDone, free(), handle, malloc(), appPrivateType::mutex, OMX_BUFFERHEADERTYPE::nFilledLen, OMX_BUFFERHEADERTYPE::nInputPortIndex, OMX_AUDIO_PARAM_PCMMODETYPE::nPortIndex, OMX_PORT_PARAM_TYPE::nPorts, OMX_AUDIO_PARAM_PCMMODETYPE::nSamplingRate, OMX_AllocateBuffer, OMX_CommandStateSet, OMX_EmptyThisBuffer, OMX_ErrorNone, OMX_FreeBuffer, OMX_FreeHandle(), OMX_GetHandle(), OMX_GetParameter, OMX_IndexParamAudioInit, OMX_IndexParamAudioPcm, OMX_Init(), OMX_SendCommand, OMX_SetParameter, OMX_StateExecuting, OMX_StateIdle, OMX_StateLoaded, OMX_BUFFERHEADERTYPE::pBuffer, symbianoutputstreamEmptyBufferDone(), symbianoutputstreamEventHandler(), tsem_down(), and tsem_init().
OMX_ERRORTYPE symbianoutputstreamEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
The EmptyBufferDone method is used to return emptied buffers from an input port back to the application for reuse. This is a blocking call so the application should not attempt to refill the buffers during this call, but should queue them and refill them in another thread. There is no error return, so the application shall handle any errors generated internally.
The application should return from this call within 5 msec.
Parameters
hComponent handle of the component to access. This is the component handle returned by the call to the GetHandle function.
pAppData pointer to an application defined value that was provided in the pAppData parameter to the OMX_GetHandle method for the component. This application defined value is provided so that the application can have a component specific context when receiving the callback.
pBuffer pointer to an OMX_BUFFERHEADERTYPE structure allocated with UseBuffer or AllocateBuffer indicating the buffer that was emptied.
Definition at line 237 of file omxsymbianoutputstreamtest.c.
References appPrivateType::condition, DEB_LEV_FULL_SEQ, DEBUG, appPrivateType::mutex, and OMX_ErrorNone.
Referenced by main().
OMX_ERRORTYPE symbianoutputstreamEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 nData1, OMX_OUT OMX_U32 nData2, OMX_OUT OMX_PTR pEventData)
The EventHandler method is used to notify the application when an event of interest occurs. Events are defined in the OMX_EVENTTYPE enumeration. Please see that enumeration for details of what will be returned for each type of event. Callbacks should not return an error to the component, so if an error occurs, the application shall handle it internally. This is a blocking call.
The application should return from this call within 5 msec to avoid blocking the component for an excessively long period of time.
Parameters
hComponent handle of the component to access. This is the component handle returned by the call to the GetHandle function.
pAppData pointer to an application defined value that was provided in the pAppData parameter to the OMX_GetHandle method for the component. This application defined value is provided so that the application can have a component specific context when receiving the callback.
eEvent Event that the component wants to notify the application about.
nData1 nData will be the OMX_ERRORTYPE for an error event and will be an OMX_COMMANDTYPE for a command complete event and OMX_INDEXTYPE for a OMX_PortSettingsChanged event.
nData2 nData2 will hold further information related to the event. Can be OMX_STATETYPE for a OMX_StateChange command or port index for a OMX_PortSettingsCHanged event. Default value is 0 if not used.)
pEventData Pointer to additional event-specific data (see spec for meaning).
Definition at line 222 of file omxsymbianoutputstreamtest.c.
References DEB_LEV_SIMPLE_SEQ, DEBUG, appPrivateType::eventSem, OMX_ErrorNone, and tsem_up().
Referenced by main().
OMX_ERRORTYPE symbianoutputstreamFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
The FillBufferDone method is used to return filled buffers from an output port back to the application for emptying and then reuse. This is a blocking call so the application should not attempt to empty the buffers during this call, but should queue the buffers and empty them in another thread. There is no error return, so the application shall handle any errors generated internally. The application shall also update the buffer header to indicate the number of bytes placed into the buffer.
The application should return from this call within 5 msec.
Parameters
hComponent handle of the component to access. This is the component handle returned by the call to the GetHandle function.
pAppData pointer to an application defined value that was provided in the pAppData parameter to the OMX_GetHandle method for the component. This application defined value is provided so that the application can have a component specific context when receiving the callback.
pBuffer pointer to an OMX_BUFFERHEADERTYPE structure allocated with UseBuffer or AllocateBuffer indicating the buffer that was filled.
Definition at line 250 of file omxsymbianoutputstreamtest.c.
References DEB_LEV_FULL_SEQ, DEBUG, and OMX_ErrorNotImplemented.
Variable Documentation
appPrivateType* appPriv
Definition at line 50 of file omxsymbianoutputstreamtest.c.
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1