OpenMAXBellagio: omxvoicexchange.c File Reference
omxvoicexchange.c File Reference
#include "omxvoicexchange.h"
Macros
#define COMPONENT_NAME_BASE "OMX.st.alsa.alsasrc"
#define BASE_ROLE "alsa.alsasrc"
#define COMPONENT_NAME_BASE_LEN 20
Functions
void error (char *msg)
void display_help ()
int main (int argc, char **argv)
OMX_ERRORTYPE audiosrcEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
OMX_ERRORTYPE audioencEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
OMX_ERRORTYPE audioencFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
OMX_ERRORTYPE audiodecEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
OMX_ERRORTYPE audiodecEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
OMX_ERRORTYPE audiosinkEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
Variables
OMX_CALLBACKTYPE audiosrccallbacks
OMX_CALLBACKTYPE audioenccallbacks
OMX_CALLBACKTYPE audiodeccallbacks
OMX_CALLBACKTYPE alsasinkcallbacks
appPrivateType * appPriv
OMX_BUFFERHEADERTYPE * pOutAudioEncBuffer [2]
OMX_BUFFERHEADERTYPE * pInAudioDecBuffer [2]
OMX_U32 buffer_out_size = 16384
OMX_U32 read_buffer_size =240
char temp_buffer [16384]
int temp_buffer_filled_len = 0
int rate = 0
int channel =0
char * output_file
FILE * outfile
int s_sockfd
int s_newsockfd
int s_portno =0
int s_clilen
int s_n
char s_buffer [16384]
struct sockaddr_in s_serv_addr s_cli_addr
int c_sockfd
int c_portno =0
int c_n
struct sockaddr_in c_serv_addr
struct hostent * c_server
char c_buffer [16384]
int flagIsClientPort
int flagIsServerPort
int flagIsMaster
int flagDecodedOutputReceived
int flagIsIPaddress
Detailed Description
This test application is supposed to exchange voice over the network using some client server mechanism.
Copyright (C) 2007-2008 STMicroelectronics Copyright (C) 2007-2008 Nokia Corporation and/or its subsidiary(-ies).
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Date:
2008-09-11 12:14:48 +0200 (Thu, 11 Sep 2008)
Revision
Rev:
1484
Author
Author:
pankaj_sen
Definition in file omxvoicexchange.c.
Macro Definition Documentation
#define BASE_ROLE "alsa.alsasrc"
Definition at line 34 of file omxvoicexchange.c.
#define COMPONENT_NAME_BASE "OMX.st.alsa.alsasrc"
defining global declarations
Definition at line 33 of file omxvoicexchange.c.
#define COMPONENT_NAME_BASE_LEN 20
Definition at line 35 of file omxvoicexchange.c.
Function Documentation
OMX_ERRORTYPE audiodecEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
Definition at line 728 of file omxvoicexchange.c.
References appPrivateType::audiodecHandle, BUFFER_OUT_SIZE, DEB_LEV_ERR, DEBUG, appPrivateType::eofSem, err, OMX_EmptyThisBuffer, OMX_ErrorNone, OMX_TRUE, read_buffer_size, s_buffer, s_n, s_newsockfd, and tsem_up().
OMX_ERRORTYPE audiodecEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
callback prototypes for audio Decoder
Definition at line 681 of file omxvoicexchange.c.
References appPrivateType::audiodecEventSem, DEB_LEV_ERR, DEB_LEV_SIMPLE_SEQ, DEBUG, appPrivateType::eofSem, OMX_BUFFERFLAG_EOS, OMX_CommandStateSet, OMX_ErrorNone, OMX_EventBufferFlag, OMX_EventCmdComplete, OMX_StateExecuting, OMX_StateIdle, OMX_StateInvalid, OMX_StateLoaded, OMX_StatePause, OMX_StateWaitForResources, and tsem_up().
OMX_ERRORTYPE audioencEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
Definition at line 592 of file omxvoicexchange.c.
References appPrivateType::audioencEventSem, DEB_LEV_ERR, DEB_LEV_SIMPLE_SEQ, DEBUG, appPrivateType::eofSem, OMX_BUFFERFLAG_EOS, OMX_CommandStateSet, OMX_ErrorNone, OMX_EventBufferFlag, OMX_EventCmdComplete, OMX_StateExecuting, OMX_StateIdle, OMX_StateInvalid, OMX_StateLoaded, OMX_StatePause, OMX_StateWaitForResources, and tsem_up().
OMX_ERRORTYPE audioencFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
Definition at line 638 of file omxvoicexchange.c.
References appPrivateType::audioencHandle, BUFFER_OUT_SIZE, c_buffer, c_n, c_sockfd, DEB_LEV_ERR, DEBUG, appPrivateType::eofSem, err, OMX_ErrorNone, OMX_FillThisBuffer, OMX_TRUE, and tsem_up().
OMX_ERRORTYPE audiosinkEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
Callbacks implementation of the audio source component
Definition at line 792 of file omxvoicexchange.c.
References appPrivateType::audiosinkEventSem, DEB_LEV_ERR, DEB_LEV_SIMPLE_SEQ, DEBUG, appPrivateType::eofSem, err, OMX_BUFFERFLAG_EOS, OMX_CommandStateSet, OMX_ErrorNone, OMX_EventBufferFlag, OMX_EventCmdComplete, OMX_StateExecuting, OMX_StateIdle, OMX_StateInvalid, OMX_StateLoaded, OMX_StatePause, OMX_StateWaitForResources, and tsem_up().
OMX_ERRORTYPE audiosrcEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
callbacks implementation
Definition at line 546 of file omxvoicexchange.c.
References appPrivateType::audiosrcEventSem, DEB_LEV_ERR, DEB_LEV_SIMPLE_SEQ, DEBUG, appPrivateType::eofSem, err, OMX_BUFFERFLAG_EOS, OMX_CommandPortDisable, OMX_CommandPortEnable, OMX_CommandStateSet, OMX_ErrorNone, OMX_EventBufferFlag, OMX_EventCmdComplete, OMX_EventPortSettingsChanged, OMX_StateExecuting, OMX_StateIdle, OMX_StateInvalid, OMX_StateLoaded, OMX_StatePause, OMX_StateWaitForResources, appPrivateType::sourceEventSem, and tsem_up().
void display_help ()
help display
Definition at line 111 of file omxvoicexchange.c.
References DEBUG, and DEFAULT_MESSAGES.
Referenced by main().
void error (char * msg)
Definition at line 104 of file omxvoicexchange.c.
Referenced by main(), omx_filereader_component_BufferMgmtCallback(), omx_filereader_component_Init(), omx_parser3gp_component_BufferMgmtCallback(), and omx_parser3gp_component_Init().
int main (int argc, char ** argv)
getting handles
if tunneling option is given then set up the tunnel between the components
sending commands to go to idle state
sending commands to go to executing state
Definition at line 125 of file omxvoicexchange.c.
References appPrivateType::audiodecEventSem, appPrivateType::audiodecHandle, appPrivateType::audioencEventSem, appPrivateType::audioencHandle, appPrivateType::audiosinkEventSem, appPrivateType::audiosinkHandle, appPrivateType::audiosrcEventSem, appPrivateType::audiosrcHandle, BUFFER_OUT_SIZE, buffer_out_size, c_buffer, c_n, c_portno, c_serv_addr, c_server, c_sockfd, channel, DEB_LEV_ERR, DEB_LEV_SIMPLE_SEQ, DEBUG, DEFAULT_MESSAGES, display_help(), appPrivateType::eofSem, err, error(), flagDecodedOutputReceived, flagIsClientPort, flagIsIPaddress, flagIsMaster, flagIsServerPort, free(), malloc(), OMX_AUDIO_PARAM_PCMMODETYPE::nChannels, OMX_BUFFERHEADERTYPE::nFilledLen, OMX_AUDIO_PARAM_PCMMODETYPE::nPortIndex, OMX_AUDIO_PARAM_PCMMODETYPE::nSamplingRate, OMX_AllocateBuffer, OMX_CommandStateSet, OMX_Deinit(), OMX_EmptyThisBuffer, OMX_ErrorNone, OMX_FillThisBuffer, OMX_FreeBuffer, OMX_FreeHandle(), OMX_GetHandle(), OMX_GetParameter, OMX_IndexParamAudioPcm, OMX_Init(), OMX_SendCommand, OMX_SetParameter, OMX_SetupTunnel(), OMX_StateExecuting, OMX_StateIdle, OMX_StateLoaded, OMX_TRUE, rate, read_buffer_size, s_buffer, s_cli_addr, s_clilen, s_n, s_newsockfd, s_portno, s_sockfd, setHeader(), tsem_down(), and tsem_init().
Variable Documentation
OMX_CALLBACKTYPE alsasinkcallbacks
Initial value:
= {
    .EventHandler = audiosinkEventHandler,
    .EmptyBufferDone = NULL,
    .FillBufferDone = NULL
    }
Definition at line 54 of file omxvoicexchange.c.
appPrivateType* appPriv
global variables
Definition at line 62 of file omxvoicexchange.c.
OMX_CALLBACKTYPE audiodeccallbacks
Initial value:
= {
    .EventHandler = audiodecEventHandler,
    .EmptyBufferDone = audiodecEmptyBufferDone,
    .FillBufferDone = NULL
    }
Definition at line 49 of file omxvoicexchange.c.
OMX_CALLBACKTYPE audioenccallbacks
Initial value:
= {
    .EventHandler = audioencEventHandler,
    .EmptyBufferDone = NULL,
    .FillBufferDone = audioencFillBufferDone
    }
Definition at line 43 of file omxvoicexchange.c.
OMX_CALLBACKTYPE audiosrccallbacks
Initial value:
= {
    .EventHandler = audiosrcEventHandler,
    .EmptyBufferDone = NULL,
    .FillBufferDone = NULL
    }
Definition at line 37 of file omxvoicexchange.c.
OMX_U32 buffer_out_size = 16384
Definition at line 67 of file omxvoicexchange.c.
Referenced by main().
char c_buffer[16384]
Definition at line 83 of file omxvoicexchange.c.
Referenced by audioencFillBufferDone(), and main().
int c_n
Definition at line 80 of file omxvoicexchange.c.
Referenced by audioencFillBufferDone(), and main().
int c_portno =0
Definition at line 80 of file omxvoicexchange.c.
Referenced by main().
struct sockaddr_in c_serv_addr
Definition at line 81 of file omxvoicexchange.c.
Referenced by main().
struct hostent* c_server
Definition at line 82 of file omxvoicexchange.c.
Referenced by main().
int c_sockfd
Definition at line 80 of file omxvoicexchange.c.
Referenced by audioencFillBufferDone(), and main().
int channel =0
Definition at line 72 of file omxvoicexchange.c.
Referenced by main().
int flagDecodedOutputReceived
Definition at line 89 of file omxvoicexchange.c.
Referenced by main().
int flagIsClientPort
Definition at line 86 of file omxvoicexchange.c.
Referenced by main().
int flagIsIPaddress
Definition at line 90 of file omxvoicexchange.c.
Referenced by main().
int flagIsMaster
Definition at line 88 of file omxvoicexchange.c.
Referenced by main().
int flagIsServerPort
Definition at line 87 of file omxvoicexchange.c.
Referenced by main().
FILE* outfile
Definition at line 74 of file omxvoicexchange.c.
char* output_file
Definition at line 73 of file omxvoicexchange.c.
OMX_BUFFERHEADERTYPE * pInAudioDecBuffer[2]
Definition at line 65 of file omxvoicexchange.c.
OMX_BUFFERHEADERTYPE* pOutAudioEncBuffer[2]
used with audio Encoder and Decoder
Definition at line 65 of file omxvoicexchange.c.
int rate = 0
Definition at line 72 of file omxvoicexchange.c.
Referenced by main().
OMX_U32 read_buffer_size =240
Definition at line 67 of file omxvoicexchange.c.
Referenced by audiodecEmptyBufferDone(), and main().
char s_buffer[16384]
Definition at line 77 of file omxvoicexchange.c.
Referenced by audiodecEmptyBufferDone(), and main().
struct sockaddr_in s_serv_addr s_cli_addr
Definition at line 78 of file omxvoicexchange.c.
Referenced by main().
int s_clilen
Definition at line 76 of file omxvoicexchange.c.
Referenced by main().
int s_n
Definition at line 76 of file omxvoicexchange.c.
Referenced by audiodecEmptyBufferDone(), and main().
int s_newsockfd
Definition at line 76 of file omxvoicexchange.c.
Referenced by audiodecEmptyBufferDone(), and main().
int s_portno =0
Definition at line 76 of file omxvoicexchange.c.
Referenced by main().
int s_sockfd
Definition at line 76 of file omxvoicexchange.c.
Referenced by main().
char temp_buffer[16384]
Definition at line 69 of file omxvoicexchange.c.
Referenced by omx_parser3gp_component_BufferMgmtCallback().
int temp_buffer_filled_len = 0
Definition at line 70 of file omxvoicexchange.c.
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1