OpenMAXBellagio: omxvideocapturetest.c File Reference
omxvideocapturetest.c File Reference
#include "omxvideocapturetest.h"
Macros
#define COMPONENT_NAME "OMX.st.video_src"
Functions
void display_help ()
OMX_ERRORTYPE test_OpenClose (OMX_STRING component_name)
int main (int argc, char **argv)
OMX_ERRORTYPE videosrcEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
OMX_ERRORTYPE videosrcFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
Variables
OMX_COLOR_FORMATTYPE COLOR_CONV_OUT_RGB_FORMAT = OMX_COLOR_Format24bitRGB888
OMX_BUFFERHEADERTYPE * pOutBuffer1
OMX_BUFFERHEADERTYPE * pOutBuffer2
OMX_U32 buffer_out_size
OMX_PARAM_PORTDEFINITIONTYPE paramPort
OMX_VIDEO_PARAM_PORTFORMATTYPE omxVideoParam
OMX_CALLBACKTYPE videosrccallbacks
OMX_U32 out_width = 0
OMX_U32 out_height = 0
appPrivateType * appPriv
char * output_file
FILE * outfile
int flagIsOutputExpected
Detailed Description
Test application that uses a OpenMAX component, a generic video videosrc. The application receives an video stream (.yuv) captured using a camera. The capture picture is then stored into a file, which can be seen by a yuv viewer.
Copyright (C) 2007-2008 STMicroelectronics Copyright (C) 2007-2008 Nokia Corporation and/or its subsidiary(-ies).
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Date:
2008-02-13 16:34:49 +0100 (Wed, 13 Feb 2008)
Revision
Rev:
1304
Author
Author:
giulio_urlini
Definition in file omxvideocapturetest.c.
Macro Definition Documentation
#define COMPONENT_NAME "OMX.st.video_src"
defining global declarations
Definition at line 34 of file omxvideocapturetest.c.
Referenced by main().
Function Documentation
void display_help ()
help display
Definition at line 74 of file omxvideocapturetest.c.
Referenced by main().
int main (int argc, char ** argv)
setting input picture width to a default value (vga format) for allocation of video videosrc buffers
getting video videosrc handle
output buffer size calculation based on input dimension speculation
sending command to video videosrc component to go to idle state
sending command to video videosrc component to go to executing state
state change of all components from executing to idle
sending command to all components to go to loaded state
freeing buffers of video videosrc input ports
closing the output file
Definition at line 97 of file omxvideocapturetest.c.
References buffer_out_size, COMPONENT_NAME, DEB_LEV_ERR, DEB_LEV_PARAMS, DEB_LEV_SIMPLE_SEQ, DEBUG, DEFAULT_MESSAGES, display_help(), appPrivateType::eofSem, err, flagIsOutputExpected, free(), malloc(), OMX_AllocateBuffer, OMX_CommandStateSet, OMX_Deinit(), OMX_ErrorNone, OMX_FillThisBuffer, OMX_FreeBuffer, OMX_FreeHandle(), OMX_GetHandle(), OMX_Init(), OMX_MAX_STRINGNAME_SIZE, OMX_SendCommand, OMX_StateExecuting, OMX_StateIdle, OMX_StateLoaded, OMX_TRUE, out_height, out_width, outfile, output_file, test_OpenClose(), tsem_down(), tsem_init(), appPrivateType::videosrcEventSem, and appPrivateType::videosrchandle.
OMX_ERRORTYPE test_OpenClose (OMX_STRING component_name)
Definition at line 83 of file omxvideocapturetest.c.
References DEB_LEV_ERR, DEBUG, DEFAULT_MESSAGES, err, OMX_ErrorNone, OMX_FreeHandle(), OMX_GetHandle(), and appPrivateType::videosrchandle.
Referenced by main().
OMX_ERRORTYPE videosrcEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
Callbacks implementation of the video videosrc component
Definition at line 264 of file omxvideocapturetest.c.
References DEB_LEV_ERR, DEB_LEV_SIMPLE_SEQ, DEBUG, appPrivateType::eofSem, err, OMX_BUFFERFLAG_EOS, OMX_CommandStateSet, OMX_ErrorNone, OMX_EventBufferFlag, OMX_EventCmdComplete, OMX_EventPortSettingsChanged, OMX_StateExecuting, OMX_StateIdle, OMX_StateInvalid, OMX_StateLoaded, OMX_StatePause, OMX_StateWaitForResources, tsem_up(), and appPrivateType::videosrcEventSem.
OMX_ERRORTYPE videosrcFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
if there is color conv component in processing state then send this buffer, in non tunneled case else in non tunneled case, write the output buffer contents in the specified output file
Definition at line 315 of file omxvideocapturetest.c.
References DEB_LEV_ERR, DEBUG, err, OMX_BUFFERFLAG_EOS, OMX_ErrorNone, OMX_FillThisBuffer, OMX_TRUE, and outfile.
Variable Documentation
appPrivateType* appPriv
Definition at line 55 of file omxvideocapturetest.c.
OMX_U32 buffer_out_size
Definition at line 42 of file omxvideocapturetest.c.
Referenced by main().
OMX_COLOR_FORMATTYPE COLOR_CONV_OUT_RGB_FORMAT = OMX_COLOR_Format24bitRGB888
global variables
Definition at line 37 of file omxvideocapturetest.c.
int flagIsOutputExpected
Definition at line 60 of file omxvideocapturetest.c.
Referenced by main().
OMX_VIDEO_PARAM_PORTFORMATTYPE omxVideoParam
Definition at line 45 of file omxvideocapturetest.c.
OMX_U32 out_height = 0
Definition at line 53 of file omxvideocapturetest.c.
Referenced by main().
OMX_U32 out_width = 0
Definition at line 52 of file omxvideocapturetest.c.
Referenced by main().
FILE* outfile
Definition at line 58 of file omxvideocapturetest.c.
Referenced by main(), and videosrcFillBufferDone().
char* output_file
Definition at line 57 of file omxvideocapturetest.c.
Referenced by main().
OMX_PARAM_PORTDEFINITIONTYPE paramPort
Definition at line 44 of file omxvideocapturetest.c.
OMX_BUFFERHEADERTYPE* pOutBuffer1
used with video videosrc
Definition at line 40 of file omxvideocapturetest.c.
OMX_BUFFERHEADERTYPE * pOutBuffer2
Definition at line 40 of file omxvideocapturetest.c.
OMX_CALLBACKTYPE videosrccallbacks
Initial value:
= { .EventHandler = videosrcEventHandler,
  .EmptyBufferDone = NULL,
  .FillBufferDone = videosrcFillBufferDone
  }
Definition at line 47 of file omxvideocapturetest.c.
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1