OpenMAXBellagio: omxvideocapnplay.c File Reference
omxvideocapnplay.c File Reference
#include "omxvideocapnplay.h"
Macros
#define COMPONENT_NAME_BASE "OMX.st.video_src"
#define BASE_ROLE "video_src"
#define COMPONENT_NAME_BASE_LEN 20
Functions
int setPortParameters ()
void display_help ()
OMX_ERRORTYPE test_OMX_ComponentNameEnum ()
OMX_ERRORTYPE test_OMX_RoleEnum (OMX_STRING component_name)
OMX_ERRORTYPE test_OMX_ComponentEnumByRole (OMX_STRING role_name)
OMX_ERRORTYPE test_OpenClose (OMX_STRING component_name)
int main (int argc, char **argv)
OMX_ERRORTYPE fb_sinkEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
OMX_ERRORTYPE fb_sinkEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
OMX_ERRORTYPE colorconvEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
OMX_ERRORTYPE colorconvEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
OMX_ERRORTYPE colorconvFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
OMX_ERRORTYPE videosrcEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
OMX_ERRORTYPE videosrcFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
Variables
OMX_CALLBACKTYPE videosrccallbacks
OMX_CALLBACKTYPE colorconv_callbacks
OMX_CALLBACKTYPE fbdev_sink_callbacks
appPrivateType * appPriv
OMX_COLOR_FORMATTYPE COLOR_CONV_OUT_RGB_FORMAT = OMX_COLOR_Format24bitRGB888
OMX_BUFFERHEADERTYPE * pOutBuffer1
OMX_BUFFERHEADERTYPE * pOutBuffer2
OMX_BUFFERHEADERTYPE * pInBufferColorConv1
OMX_BUFFERHEADERTYPE * pInBufferColorConv2
OMX_BUFFERHEADERTYPE * pOutBufferColorConv1
OMX_BUFFERHEADERTYPE * pOutBufferColorConv2
OMX_BUFFERHEADERTYPE * pInBufferSink1
OMX_BUFFERHEADERTYPE * pInBufferSink2
int buffer_in_size = 4096
OMX_U32 buffer_out_size
OMX_U32 outbuf_colorconv_size
OMX_PARAM_PORTDEFINITIONTYPE paramPort
OMX_PARAM_PORTDEFINITIONTYPE omx_colorconvPortDefinition
OMX_PARAM_COMPONENTROLETYPE paramRole
OMX_VIDEO_PARAM_PORTFORMATTYPE omxVideoParam
OMX_U32 out_width = 176
OMX_U32 out_height = 144
char * output_file
FILE * outfile
int flagIsOutputExpected
int flagDecodedOutputReceived
int flagIsColorConvRequested
int flagIsSinkRequested
int flagIsFormatRequested
int flagSetupTunnel
Detailed Description
Test application that uses a OpenMAX component, a generic video source. The application receives an video stream (.m4v or .264) decoded by a multiple format source component. The decoded output is seen by a yuv viewer.
Copyright (C) 2007-2008 STMicroelectronics Copyright (C) 2007-2008 Nokia Corporation and/or its subsidiary(-ies).
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Date:
2008-08-04 13:53:29 +0200 (Mon, 04 Aug 2008)
Revision
Rev:
579
Author
Author:
pankaj_sen
Definition in file omxvideocapnplay.c.
Macro Definition Documentation
#define BASE_ROLE "video_src"
Definition at line 35 of file omxvideocapnplay.c.
Referenced by main().
#define COMPONENT_NAME_BASE "OMX.st.video_src"
defining global declarations
Definition at line 34 of file omxvideocapnplay.c.
Referenced by main().
#define COMPONENT_NAME_BASE_LEN 20
Definition at line 36 of file omxvideocapnplay.c.
Function Documentation
OMX_ERRORTYPE colorconvEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
Definition at line 984 of file omxvideocapnplay.c.
References DEB_LEV_ERR, DEBUG, appPrivateType::eofSem, err, OMX_BUFFERHEADERTYPE::nFilledLen, OMX_ErrorNone, OMX_FillThisBuffer, OMX_BUFFERHEADERTYPE::pBuffer, tsem_up(), and appPrivateType::videosrchandle.
OMX_ERRORTYPE colorconvEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
callbacks implementation of color converter component
Definition at line 933 of file omxvideocapnplay.c.
References appPrivateType::colorconvEventSem, DEB_LEV_ERR, DEB_LEV_SIMPLE_SEQ, DEBUG, appPrivateType::eofSem, OMX_BUFFERFLAG_EOS, OMX_CommandPortDisable, OMX_CommandPortEnable, OMX_CommandStateSet, OMX_ErrorNone, OMX_EventBufferFlag, OMX_EventCmdComplete, OMX_StateExecuting, OMX_StateIdle, OMX_StateInvalid, OMX_StateLoaded, OMX_StatePause, OMX_StateWaitForResources, and tsem_up().
OMX_ERRORTYPE colorconvFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
if there is no sink component then write buffer content in output file, in non tunneled case else in non tunneled case, call the sink comp handle to process this buffer as its input buffer
Definition at line 1021 of file omxvideocapnplay.c.
References DEB_LEV_ERR, DEBUG, err, appPrivateType::fbdev_sink_handle, flagIsSinkRequested, flagSetupTunnel, OMX_BUFFERHEADERTYPE::nFilledLen, OMX_BUFFERFLAG_EOS, OMX_EmptyThisBuffer, OMX_ErrorNone, OMX_FillThisBuffer, OMX_TRUE, outfile, and OMX_BUFFERHEADERTYPE::pBuffer.
void display_help ()
help display
Definition at line 200 of file omxvideocapnplay.c.
Referenced by main().
OMX_ERRORTYPE fb_sinkEmptyBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
Definition at line 896 of file omxvideocapnplay.c.
References appPrivateType::colorconv_handle, DEB_LEV_ERR, DEBUG, appPrivateType::eofSem, err, OMX_BUFFERHEADERTYPE::nFilledLen, OMX_ErrorNone, OMX_FillThisBuffer, OMX_BUFFERHEADERTYPE::pBuffer, and tsem_up().
OMX_ERRORTYPE fb_sinkEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
callbacks implementation of video sink component
Definition at line 845 of file omxvideocapnplay.c.
References DEB_LEV_ERR, DEB_LEV_SIMPLE_SEQ, DEBUG, appPrivateType::eofSem, appPrivateType::fbdevSinkEventSem, OMX_BUFFERFLAG_EOS, OMX_CommandPortDisable, OMX_CommandPortEnable, OMX_CommandStateSet, OMX_ErrorNone, OMX_EventBufferFlag, OMX_EventCmdComplete, OMX_StateExecuting, OMX_StateIdle, OMX_StateInvalid, OMX_StateLoaded, OMX_StatePause, OMX_StateWaitForResources, and tsem_up().
int main (int argc, char ** argv)
if color converter component is not selected then sink component will not work, even if specified
output file name check
getting video source handle
getting color converter component handle, if specified
getting sink component handle - if reqd'
output buffer size calculation based on input dimension speculation
if tunneling option is given then set up the tunnel between the components
sending command to video source component to go to idle state
in tunnel case, change the color conv and sink comp state to idle
if tunneling option is not given then allocate buffers on video source output port
in non tunneled case, using buffers in color conv input port, allocated by video dec component output port
allocating buffers in the color converter compoennt output port
send command to change color onv and sink comp in executing state
sending command to video source component to go to executing state
state change of all components from executing to idle
sending command to all components to go to loaded state
freeing buffers of color conv and sink component
freeing buffers of video source input ports
closing the output file
Definition at line 362 of file omxvideocapnplay.c.
References BASE_ROLE, buffer_out_size, COLOR_CONV_OUT_RGB_FORMAT, appPrivateType::colorconv_handle, appPrivateType::colorconvEventSem, COMPONENT_NAME_BASE, DEB_LEV_ERR, DEB_LEV_PARAMS, DEB_LEV_SIMPLE_SEQ, DEBUG, DEFAULT_MESSAGES, display_help(), appPrivateType::eofSem, err, appPrivateType::fbdev_sink_handle, appPrivateType::fbdevSinkEventSem, flagDecodedOutputReceived, flagIsColorConvRequested, flagIsFormatRequested, flagIsOutputExpected, flagIsSinkRequested, flagSetupTunnel, free(), malloc(), OMX_PARAM_PORTDEFINITIONTYPE::nBufferSize, OMX_PARAM_PORTDEFINITIONTYPE::nPortIndex, OMX_AllocateBuffer, OMX_COLOR_Format16bitARGB1555, OMX_COLOR_Format16bitBGR565, OMX_COLOR_Format16bitRGB565, OMX_COLOR_Format24bitBGR888, OMX_COLOR_Format24bitRGB888, OMX_COLOR_Format32bitARGB8888, OMX_COLOR_Format32bitBGRA8888, OMX_CommandStateSet, OMX_Deinit(), OMX_ErrorNone, OMX_FillThisBuffer, OMX_FreeBuffer, OMX_FreeHandle(), OMX_GetHandle(), OMX_GetParameter, OMX_IndexParamPortDefinition, OMX_Init(), OMX_MAX_STRINGNAME_SIZE, OMX_SendCommand, OMX_SetupTunnel(), OMX_StateExecuting, OMX_StateIdle, OMX_StateLoaded, OMX_TRUE, OMX_UseBuffer, out_height, out_width, outbuf_colorconv_size, outfile, output_file, OMX_BUFFERHEADERTYPE::pBuffer, setHeader(), setPortParameters(), appPrivateType::sourceEventSem, test_OMX_ComponentEnumByRole(), test_OMX_ComponentNameEnum(), test_OMX_RoleEnum(), test_OpenClose(), tsem_down(), tsem_init(), and appPrivateType::videosrchandle.
int setPortParameters ()
this function sets the color converter and video sink port characteristics based on the video source output port settings
setting the color converter and sink component chararacteristics, if selected - both in tunneled as well as non tunneled case
setting the color conv input port width, height it will be same as the video source output port width, height
setting the color converter output width height it will be same as input dimensions
setting the input color format of color converter component it will be same as output yuv color format of the source component
setting output RGB color format of the color converter component
if video sink component is selected then set its input port settings accroding to the output port settings of the color converter component
Definition at line 102 of file omxvideocapnplay.c.
Referenced by main().
OMX_ERRORTYPE test_OMX_ComponentEnumByRole (OMX_STRING role_name)
Definition at line 299 of file omxvideocapnplay.c.
References DEB_LEV_ERR, DEBUG, DEFAULT_MESSAGES, err, free(), malloc(), OMX_ErrorNone, OMX_GetComponentsOfRole(), and OMX_MAX_STRINGNAME_SIZE.
Referenced by main().
OMX_ERRORTYPE test_OMX_ComponentNameEnum ()
Definition at line 234 of file omxvideocapnplay.c.
References DEBUG, DEFAULT_MESSAGES, err, free(), malloc(), OMX_ComponentNameEnum(), OMX_ErrorNone, and OMX_MAX_STRINGNAME_SIZE.
Referenced by main().
OMX_ERRORTYPE test_OMX_RoleEnum (OMX_STRING component_name)
Definition at line 257 of file omxvideocapnplay.c.
References DEB_LEV_ERR, DEB_LEV_SIMPLE_SEQ, DEBUG, DEFAULT_MESSAGES, err, malloc(), OMX_ErrorInvalidComponentName, OMX_ErrorNone, OMX_GetRolesOfComponent(), and OMX_MAX_STRINGNAME_SIZE.
Referenced by main().
OMX_ERRORTYPE test_OpenClose (OMX_STRING component_name)
Definition at line 347 of file omxvideocapnplay.c.
References DEB_LEV_ERR, DEBUG, DEFAULT_MESSAGES, err, OMX_ErrorNone, OMX_FreeHandle(), OMX_GetHandle(), and appPrivateType::videosrchandle.
Referenced by main().
OMX_ERRORTYPE videosrcEventHandler (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_EVENTTYPE eEvent, OMX_OUT OMX_U32 Data1, OMX_OUT OMX_U32 Data2, OMX_OUT OMX_PTR pEventData)
Callbacks implementation of the video source component
Definition at line 1065 of file omxvideocapnplay.c.
OMX_ERRORTYPE videosrcFillBufferDone (OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE * pBuffer)
if there is color conv component in processing state then send this buffer, in non tunneled case else in non tunneled case, write the output buffer contents in the specified output file
Definition at line 1119 of file omxvideocapnplay.c.
Variable Documentation
appPrivateType* appPriv
global variables
Definition at line 55 of file omxvideocapnplay.c.
int buffer_in_size = 4096
Definition at line 65 of file omxvideocapnplay.c.
OMX_U32 buffer_out_size
Definition at line 66 of file omxvideocapnplay.c.
Referenced by main().
OMX_COLOR_FORMATTYPE COLOR_CONV_OUT_RGB_FORMAT = OMX_COLOR_Format24bitRGB888
Definition at line 57 of file omxvideocapnplay.c.
Referenced by main(), and setPortParameters().
OMX_CALLBACKTYPE colorconv_callbacks
Initial value:
= { .EventHandler = colorconvEventHandler,
    .EmptyBufferDone = colorconvEmptyBufferDone,
    .FillBufferDone = colorconvFillBufferDone
    }
Definition at line 43 of file omxvideocapnplay.c.
OMX_CALLBACKTYPE fbdev_sink_callbacks
Initial value:
= { .EventHandler = fb_sinkEventHandler,
    .EmptyBufferDone = fb_sinkEmptyBufferDone,
    .FillBufferDone = NULL
    }
Definition at line 48 of file omxvideocapnplay.c.
int flagDecodedOutputReceived
Definition at line 80 of file omxvideocapnplay.c.
Referenced by main().
int flagIsColorConvRequested
Definition at line 81 of file omxvideocapnplay.c.
Referenced by main(), setPortParameters(), and videosrcFillBufferDone().
int flagIsFormatRequested
Definition at line 83 of file omxvideocapnplay.c.
Referenced by main().
int flagIsOutputExpected
Definition at line 79 of file omxvideocapnplay.c.
Referenced by main().
int flagIsSinkRequested
Definition at line 82 of file omxvideocapnplay.c.
Referenced by colorconvFillBufferDone(), main(), and setPortParameters().
int flagSetupTunnel
Definition at line 84 of file omxvideocapnplay.c.
Referenced by colorconvFillBufferDone(), main(), and videosrcFillBufferDone().
OMX_PARAM_PORTDEFINITIONTYPE omx_colorconvPortDefinition
Definition at line 70 of file omxvideocapnplay.c.
Referenced by SetPortParametersVideo().
OMX_VIDEO_PARAM_PORTFORMATTYPE omxVideoParam
Definition at line 72 of file omxvideocapnplay.c.
OMX_U32 out_height = 144
Definition at line 74 of file omxvideocapnplay.c.
Referenced by main(), and setPortParameters().
OMX_U32 out_width = 176
Definition at line 73 of file omxvideocapnplay.c.
Referenced by main(), and setPortParameters().
OMX_U32 outbuf_colorconv_size
Definition at line 67 of file omxvideocapnplay.c.
Referenced by main().
FILE* outfile
Definition at line 77 of file omxvideocapnplay.c.
Referenced by colorconvFillBufferDone(), main(), and videosrcFillBufferDone().
char* output_file
Definition at line 76 of file omxvideocapnplay.c.
Referenced by main().
OMX_PARAM_PORTDEFINITIONTYPE paramPort
Definition at line 69 of file omxvideocapnplay.c.
OMX_PARAM_COMPONENTROLETYPE paramRole
Definition at line 71 of file omxvideocapnplay.c.
OMX_BUFFERHEADERTYPE* pInBufferColorConv1
used with color converter if selected
Definition at line 62 of file omxvideocapnplay.c.
OMX_BUFFERHEADERTYPE * pInBufferColorConv2
Definition at line 62 of file omxvideocapnplay.c.
OMX_BUFFERHEADERTYPE* pInBufferSink1
Definition at line 63 of file omxvideocapnplay.c.
OMX_BUFFERHEADERTYPE * pInBufferSink2
Definition at line 63 of file omxvideocapnplay.c.
OMX_BUFFERHEADERTYPE* pOutBuffer1
used with video source
Definition at line 60 of file omxvideocapnplay.c.
OMX_BUFFERHEADERTYPE * pOutBuffer2
Definition at line 60 of file omxvideocapnplay.c.
OMX_BUFFERHEADERTYPE * pOutBufferColorConv1
Definition at line 62 of file omxvideocapnplay.c.
OMX_BUFFERHEADERTYPE * pOutBufferColorConv2
Definition at line 62 of file omxvideocapnplay.c.
OMX_CALLBACKTYPE videosrccallbacks
Initial value:
= { .EventHandler = videosrcEventHandler,
    .EmptyBufferDone = NULL,
    .FillBufferDone = videosrcFillBufferDone
    }
Definition at line 38 of file omxvideocapnplay.c.
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1