OpenMAXBellagio: queue.h File Reference
queue.h File Reference
#include <pthread.h>
Data Structures
struct qelem_t
struct queue_t
Macros
#define MAX_QUEUE_ELEMENTS 10
Typedefs
typedef struct qelem_t qelem_t
typedef struct queue_t queue_t
Functions
void queue_init (queue_t *queue)
void queue_deinit (queue_t *queue)
void queue (queue_t *queue, void *data)
void * dequeue (queue_t *queue)
int getquenelem (queue_t *queue)
Detailed Description
Implements a simple LIFO structure used for queueing OMX buffers.
Copyright (C) 2007-2008 STMicroelectronics Copyright (C) 2007-2008 Nokia Corporation and/or its subsidiary(-ies).
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
Date:
2008-06-27 12:00:23 +0200 (Fri, 27 Jun 2008)
Revision
Rev:
554
Author
Author:
pankaj_sen
Definition in file queue.h.
Macro Definition Documentation
#define MAX_QUEUE_ELEMENTS 10
Maximum number of elements in a queue
Definition at line 35 of file queue.h.
Referenced by queue_deinit(), and queue_init().
Typedef Documentation
typedef struct qelem_t qelem_t
Output port queue element. Contains an OMX buffer header type
Definition at line 38 of file queue.h.
typedef struct queue_t queue_t
This structure contains the queue
Function Documentation
void* dequeue (queue_t * queue)
Dequeue an element from the given queue descriptor
Parameters
queue the queue descriptor from which to dequeue the element
Returns
the element that has bee dequeued. If the queue is empty a NULL value is returned
Definition at line 107 of file queue.c.
References qelem_t::data, queue_t::first, queue_t::mutex, queue_t::nelem, and qelem_t::q_forw.
Referenced by base_port_DisablePort(), base_port_FlushProcessingBuffers(), clocksrc_port_FlushProcessingBuffers(), compMessageHandlerFunction(), omx_alsasink_component_ClockPortHandleFunction(), omx_alsasink_component_port_FlushProcessingBuffers(), omx_audio_mixer_BufferMgmtFunction(), omx_base_component_DoStateSet(), omx_base_filter_BufferMgmtFunction(), omx_base_sink_BufferMgmtFunction(), omx_base_source_BufferMgmtFunction(), omx_base_source_twoport_BufferMgmtFunction(), omx_clocksrc_BufferMgmtFunction(), omx_fbdev_sink_component_ClockPortHandleFunction(), omx_fbdev_sink_component_port_FlushProcessingBuffers(), omx_jpegdec_component_BufferMgmtFunction(), omx_jpegenc_component_BufferMgmtFunction(), and omx_parser3gp_component_BufferMgmtCallback().
int getquenelem (queue_t * queue)
Returns the number of elements hold in the queue
Parameters
queue the requested queue
Returns
the number of elements in the queue
Definition at line 128 of file queue.c.
References queue_t::mutex, and queue_t::nelem.
void queue (queue_t * queue, void * data)
Enqueue an element to the given queue descriptor
Parameters
queue the queue descritpor where to queue data
data the data to be enqueued
Definition at line 89 of file queue.c.
References qelem_t::data, queue_t::last, queue_t::mutex, queue_t::nelem, and qelem_t::q_forw.
Referenced by base_clock_port_SendBufferFunction(), base_port_AllocateTunnelBuffer(), base_port_FlushProcessingBuffers(), base_port_ReturnBufferFunction(), base_port_SendBufferFunction(), clocksrc_port_FlushProcessingBuffers(), omx_alsasink_component_port_FlushProcessingBuffers(), omx_alsasink_component_port_SendBufferFunction(), omx_base_component_SendCommand(), omx_fbdev_sink_component_port_FlushProcessingBuffers(), omx_fbdev_sink_component_port_SendBufferFunction(), and videosrc_port_AllocateTunnelBuffer().
void queue_deinit (queue_t * queue)
Deinitialize a queue descriptor flushing all of its internal data
Parameters
queue the queue descriptor to dump
Definition at line 65 of file queue.c.
References queue_t::first, free(), MAX_QUEUE_ELEMENTS, queue_t::mutex, and qelem_t::q_forw.
Referenced by base_port_Destructor(), and omx_base_component_Destructor().
void queue_init (queue_t * queue)
Initialize a queue descriptor
Parameters
queue The queue descriptor to initialize. The user needs to allocate the queue
Definition at line 41 of file queue.c.
References queue_t::first, queue_t::last, malloc(), MAX_QUEUE_ELEMENTS, queue_t::mutex, queue_t::nelem, and qelem_t::q_forw.
Referenced by base_port_Constructor(), and omx_base_component_Constructor().
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1