OpenMAXBellagio: rdswitch.c File Reference
rdswitch.c File Reference
#include "cdjpeg.h"
#include <ctype.h>
Macros
#define MAX_SCANS 100 /* quite arbitrary limit */
Functions
boolean read_quant_tables (j_compress_ptr cinfo, char *filename, boolean force_baseline)
boolean read_scan_script (j_compress_ptr cinfo, char *filename)
boolean set_quality_ratings (j_compress_ptr cinfo, char *arg, boolean force_baseline)
boolean set_quant_slots (j_compress_ptr cinfo, char *arg)
boolean set_sample_factors (j_compress_ptr cinfo, char *arg)
Macro Definition Documentation
#define MAX_SCANS 100 /* quite arbitrary limit */
Referenced by read_scan_script().
Function Documentation
boolean read_quant_tables (j_compress_ptr cinfo, char * filename, boolean force_baseline)
Definition at line 74 of file rdswitch.c.
References DCTSIZE2, FALSE, jpeg_add_quant_table(), NUM_QUANT_TBLS, and TRUE.
boolean read_scan_script (j_compress_ptr cinfo, char * filename)
Definition at line 159 of file rdswitch.c.
References jpeg_scan_info::Ah, jpeg_scan_info::Al, jpeg_scan_info::component_index, jpeg_scan_info::comps_in_scan, DCTSIZE2, FALSE, JPOOL_IMAGE, MAX_COMPS_IN_SCAN, MAX_SCANS, MEMCOPY, jpeg_scan_info::Se, SIZEOF, jpeg_scan_info::Ss, and TRUE.
boolean set_quality_ratings (j_compress_ptr cinfo, char * arg, boolean force_baseline)
Definition at line 267 of file rdswitch.c.
References FALSE, jpeg_default_qtables(), jpeg_quality_scaling(), NUM_QUANT_TBLS, and TRUE.
boolean set_quant_slots (j_compress_ptr cinfo, char * arg)
Definition at line 299 of file rdswitch.c.
References FALSE, MAX_COMPONENTS, NUM_QUANT_TBLS, and TRUE.
boolean set_sample_factors (j_compress_ptr cinfo, char * arg)
Definition at line 334 of file rdswitch.c.
References FALSE, MAX_COMPONENTS, and TRUE.
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1