OpenMAXBellagio: jpeg_source_mgr Struct Reference
jpeg_source_mgr Struct Reference
#include <jpeglib.h>
Data Fields
const JOCTET * next_input_byte
size_t bytes_in_buffer
void(* init_source)()
boolean(* fill_input_buffer)()
void(* skip_input_data)()
boolean(* resync_to_restart)()
void(* term_source)()
Detailed Description
Definition at line 744 of file jpeglib.h.
Field Documentation
size_t jpeg_source_mgr::bytes_in_buffer
Definition at line 746 of file jpeglib.h.
Referenced by jpeg_data_src(), and jpeg_stdio_src().
boolean(* jpeg_source_mgr::fill_input_buffer)()
Definition at line 749 of file jpeglib.h.
Referenced by jpeg_data_src(), and jpeg_stdio_src().
void(* jpeg_source_mgr::init_source)()
Definition at line 748 of file jpeglib.h.
Referenced by jpeg_data_src(), and jpeg_stdio_src().
const JOCTET* jpeg_source_mgr::next_input_byte
Definition at line 745 of file jpeglib.h.
Referenced by jpeg_data_src(), and jpeg_stdio_src().
boolean(* jpeg_source_mgr::resync_to_restart)()
Definition at line 751 of file jpeglib.h.
Referenced by jpeg_data_src(), and jpeg_stdio_src().
void(* jpeg_source_mgr::skip_input_data)()
Definition at line 750 of file jpeglib.h.
Referenced by jpeg_data_src(), and jpeg_stdio_src().
void(* jpeg_source_mgr::term_source)()
Definition at line 752 of file jpeglib.h.
Referenced by jpeg_data_src(), and jpeg_stdio_src().
The documentation for this struct was generated from the following file:
jpeglib.h
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1