OpenMAXBellagio: jpeg_destination_mgr Struct Reference
jpeg_destination_mgr Struct Reference
#include <jpeglib.h>
Data Fields
JOCTET * next_output_byte
size_t free_in_buffer
void(* init_destination)()
boolean(* empty_output_buffer)()
void(* term_destination)()
Detailed Description
Definition at line 732 of file jpeglib.h.
Field Documentation
boolean(* jpeg_destination_mgr::empty_output_buffer)()
Definition at line 737 of file jpeglib.h.
Referenced by jpeg_stdio_dest().
size_t jpeg_destination_mgr::free_in_buffer
Definition at line 734 of file jpeglib.h.
void(* jpeg_destination_mgr::init_destination)()
Definition at line 736 of file jpeglib.h.
Referenced by jpeg_stdio_dest().
JOCTET* jpeg_destination_mgr::next_output_byte
Definition at line 733 of file jpeglib.h.
void(* jpeg_destination_mgr::term_destination)()
Definition at line 738 of file jpeglib.h.
Referenced by jpeg_stdio_dest().
The documentation for this struct was generated from the following file:
jpeglib.h
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1