OpenMAXBellagio: jpeg_memory_mgr Struct Reference
jpeg_memory_mgr Struct Reference
#include <jpeglib.h>
Data Fields
void *(* alloc_small)()
void *(* alloc_large)()
JSAMPARRAY(* alloc_sarray)()
JBLOCKARRAY(* alloc_barray)()
jvirt_sarray_ptr(* request_virt_sarray)()
jvirt_barray_ptr(* request_virt_barray)()
void(* realize_virt_arrays)()
JSAMPARRAY(* access_virt_sarray)()
JBLOCKARRAY(* access_virt_barray)()
void(* free_pool)()
void(* self_destruct)()
long max_memory_to_use
long max_alloc_chunk
Detailed Description
Definition at line 775 of file jpeglib.h.
Field Documentation
JBLOCKARRAY(* jpeg_memory_mgr::access_virt_barray)()
Definition at line 809 of file jpeglib.h.
Referenced by jinit_memory_mgr().
JSAMPARRAY(* jpeg_memory_mgr::access_virt_sarray)()
Definition at line 804 of file jpeglib.h.
Referenced by jinit_memory_mgr().
JBLOCKARRAY(* jpeg_memory_mgr::alloc_barray)()
Definition at line 786 of file jpeglib.h.
Referenced by jinit_memory_mgr().
void*(* jpeg_memory_mgr::alloc_large)()
Definition at line 780 of file jpeglib.h.
Referenced by jinit_memory_mgr().
JSAMPARRAY(* jpeg_memory_mgr::alloc_sarray)()
Definition at line 783 of file jpeglib.h.
Referenced by jinit_memory_mgr().
void*(* jpeg_memory_mgr::alloc_small)()
Definition at line 778 of file jpeglib.h.
Referenced by jinit_memory_mgr(), and jpeg_data_src().
void(* jpeg_memory_mgr::free_pool)()
Definition at line 810 of file jpeglib.h.
Referenced by jinit_memory_mgr().
long jpeg_memory_mgr::max_alloc_chunk
Definition at line 821 of file jpeglib.h.
Referenced by jinit_memory_mgr().
long jpeg_memory_mgr::max_memory_to_use
Definition at line 818 of file jpeglib.h.
Referenced by jinit_memory_mgr(), and main().
void(* jpeg_memory_mgr::realize_virt_arrays)()
Definition at line 799 of file jpeglib.h.
Referenced by jinit_memory_mgr().
jvirt_barray_ptr(* jpeg_memory_mgr::request_virt_barray)()
Definition at line 798 of file jpeglib.h.
Referenced by jinit_memory_mgr().
jvirt_sarray_ptr(* jpeg_memory_mgr::request_virt_sarray)()
Definition at line 792 of file jpeglib.h.
Referenced by jinit_memory_mgr().
void(* jpeg_memory_mgr::self_destruct)()
Definition at line 811 of file jpeglib.h.
Referenced by jinit_memory_mgr().
The documentation for this struct was generated from the following file:
jpeglib.h
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1