OpenMAXBellagio: OMX_CALLBACKTYPE Struct Reference
OMX_CALLBACKTYPE Struct Reference
#include <OMX_Core.h>
Data Fields
OMX_ERRORTYPE(* EventHandler)(OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_PTR pAppData, OMX_IN OMX_EVENTTYPE eEvent, OMX_IN OMX_U32 nData1, OMX_IN OMX_U32 nData2, OMX_IN OMX_PTR pEventData)
OMX_ERRORTYPE(* EmptyBufferDone)(OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_PTR pAppData, OMX_IN OMX_BUFFERHEADERTYPE *pBuffer)
OMX_ERRORTYPE(* FillBufferDone)(OMX_OUT OMX_HANDLETYPE hComponent, OMX_OUT OMX_PTR pAppData, OMX_OUT OMX_BUFFERHEADERTYPE *pBuffer)
Detailed Description
Definition at line 458 of file OMX_Core.h.
Field Documentation
OMX_ERRORTYPE(* OMX_CALLBACKTYPE::EventHandler)(OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_PTR pAppData, OMX_IN OMX_EVENTTYPE eEvent, OMX_IN OMX_U32 nData1, OMX_IN OMX_U32 nData2, OMX_IN OMX_PTR pEventData)
The EventHandler method is used to notify the application when an event of interest occurs. Events are defined in the OMX_EVENTTYPE enumeration. Please see that enumeration for details of what will be returned for each type of event. Callbacks should not return an error to the component, so if an error occurs, the application shall handle it internally. This is a blocking call.
The application should return from this call within 5 msec to avoid blocking the component for an excessively long period of time.
Parameters
hComponent handle of the component to access. This is the component handle returned by the call to the GetHandle function.
pAppData pointer to an application defined value that was provided in the pAppData parameter to the OMX_GetHandle method for the component. This application defined value is provided so that the application can have a component specific context when receiving the callback.
eEvent Event that the component wants to notify the application about.
nData1 nData will be the OMX_ERRORTYPE for an error event and will be an OMX_COMMANDTYPE for a command complete event and OMX_INDEXTYPE for a OMX_PortSettingsChanged event.
nData2 nData2 will hold further information related to the event. Can be OMX_STATETYPE for a OMX_StateChange command or port index for a OMX_PortSettingsCHanged event. Default value is 0 if not used.)
pEventData Pointer to additional event-specific data (see spec for meaning).
Definition at line 491 of file OMX_Core.h.
Referenced by base_port_FreeBuffer(), base_port_FreeTunnelBuffer(), main(), omx_base_component_MessageHandler(), omx_base_sink_BufferMgmtFunction(), omx_base_source_BufferMgmtFunction(), videosrc_port_FreeBuffer(), and videosrc_port_FreeTunnelBuffer().
The documentation for this struct was generated from the following file:
OMX_Core.h
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1