OpenMAXBellagio: cjpeg_source_struct Struct Reference
cjpeg_source_struct Struct Reference
#include <cdjpeg.h>
Data Fields
void(* start_input)(j_compress_ptr cinfo, cjpeg_source_ptr sinfo)
JDIMENSION(* get_pixel_rows)(j_compress_ptr cinfo, cjpeg_source_ptr sinfo)
void(* finish_input)(j_compress_ptr cinfo, cjpeg_source_ptr sinfo)
FILE * input_file
JSAMPARRAY buffer
JDIMENSION buffer_height
Detailed Description
Definition at line 26 of file cdjpeg.h.
Field Documentation
JSAMPARRAY cjpeg_source_struct::buffer
Definition at line 36 of file cdjpeg.h.
Referenced by main().
JDIMENSION cjpeg_source_struct::buffer_height
Definition at line 37 of file cdjpeg.h.
void(* cjpeg_source_struct::finish_input)(j_compress_ptr cinfo, cjpeg_source_ptr sinfo)
Definition at line 32 of file cdjpeg.h.
Referenced by jinit_read_bmp(), jinit_read_ppm(), jinit_read_targa(), and main().
JDIMENSION(* cjpeg_source_struct::get_pixel_rows)(j_compress_ptr cinfo, cjpeg_source_ptr sinfo)
Definition at line 30 of file cdjpeg.h.
Referenced by main().
FILE* cjpeg_source_struct::input_file
Definition at line 34 of file cdjpeg.h.
Referenced by main().
void(* cjpeg_source_struct::start_input)(j_compress_ptr cinfo, cjpeg_source_ptr sinfo)
Definition at line 28 of file cdjpeg.h.
Referenced by jinit_read_bmp(), jinit_read_ppm(), jinit_read_targa(), and main().
The documentation for this struct was generated from the following file:
cdjpeg.h
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1