OpenMAXBellagio: BOSA_COMPONENTLOADER Struct Reference
BOSA_COMPONENTLOADER Struct Reference
Component loader entry points.
#include <component_loader.h>
Data Fields
OMX_ERRORTYPE(* BOSA_InitComponentLoader)(struct BOSA_COMPONENTLOADER *loader)
The constructor of the component loader.
OMX_ERRORTYPE(* BOSA_DeInitComponentLoader)(struct BOSA_COMPONENTLOADER *loader)
The destructor of the component loader.
OMX_ERRORTYPE(* BOSA_CreateComponent)(struct BOSA_COMPONENTLOADER *loader, OMX_HANDLETYPE *pHandle, OMX_STRING cComponentName, OMX_PTR pAppData, OMX_CALLBACKTYPE *pCallBacks)
The component costructor of the current component loader.
OMX_ERRORTYPE(* BOSA_DestroyComponent)(struct BOSA_COMPONENTLOADER *loader, OMX_HANDLETYPE hComponent)
The component destructor of the current component loader.
OMX_ERRORTYPE(* BOSA_ComponentNameEnum)(struct BOSA_COMPONENTLOADER *loader, OMX_STRING cComponentName, OMX_U32 nNameLength, OMX_U32 nIndex)
An enumerator of the components handled by the current component loader.
OMX_ERRORTYPE(* BOSA_GetRolesOfComponent)(struct BOSA_COMPONENTLOADER *loader, OMX_STRING compName, OMX_U32 *pNumRoles, OMX_U8 **roles)
This function implements the OMX_GetRolesOfComponent standard function for the current component loader.
OMX_ERRORTYPE(* BOSA_GetComponentsOfRole)(struct BOSA_COMPONENTLOADER *loader, OMX_STRING role, OMX_U32 *pNumComps, OMX_U8 **compNames)
This function implements the OMX_GetComponentsOfRole standard function for the current component loader.
void * loaderPrivate
The reference to the current component loader private data.
Detailed Description
Component loader entry points.
The component loader generic structure contains the entry points for each component loader. The list of component loaders is filled using a special function, called AddComponentLoader.
Definition at line 41 of file component_loader.h.
Field Documentation
OMX_ERRORTYPE(* BOSA_COMPONENTLOADER::BOSA_ComponentNameEnum)(struct BOSA_COMPONENTLOADER *loader, OMX_STRING cComponentName, OMX_U32 nNameLength, OMX_U32 nIndex)
An enumerator of the components handled by the current component loader.
This function implements the OMX_ComponentNameEnum function for the specific component loader
Parameters
loader Private data of the component loader
cComponentName A pointer to a null terminated string with the component name. The names of the components are strings less than 127 bytes in length plus the trailing null for a maximum size of 128 bytes (OMX_MAX_STRINGNAME_SIZE).
nNameLength The number of characters in the cComponentName string. With all component name strings restricted to less than 128 characters (including the trailing null) it is recomended that the caller provide a input string for the cComponentName of 128 characters.
nIndex A number containing the enumeration index for the component. Multiple calls to OMX_ComponentNameEnum with increasing values of nIndex will enumerate through the component names in the system until OMX_ErrorNoMore is returned. The value of nIndex is 0 to (N-1), where N is the number of valid installed components in the system.
Returns
OMX_ErrorNone If the command successfully executes
OMX_ErrorNoMore If the value of nIndex exceeds the number of components handled by the component loader minus 1
Definition at line 144 of file component_loader.h.
Referenced by st_static_InitComponentLoader().
OMX_ERRORTYPE(* BOSA_COMPONENTLOADER::BOSA_CreateComponent)(struct BOSA_COMPONENTLOADER *loader, OMX_HANDLETYPE *pHandle, OMX_STRING cComponentName, OMX_PTR pAppData, OMX_CALLBACKTYPE *pCallBacks)
The component costructor of the current component loader.
This function implements the OMX_GetHandle function for the specific component loader. Its interface is the same as the standard GetHandle function, except that the first parameter that contains the private data of the specific component loader.
Parameters
loader Private data of the component loader
pHandle the openmax handle returned by the function, or NULL in case of failure.
cComponentName A string that contains the standard component's name
pAppData private data of the component (if needed)
pCallBacks IL client callback function pointers passed to the component
Returns
OMX_ErrorNone if the component is correctly constructed and returned
OMX_ErrorComponentNotFound if the component is not found
OMX_ErrorInsufficientResources if the component exists but can not be allocated.
Definition at line 87 of file component_loader.h.
Referenced by OMX_GetHandle(), and st_static_InitComponentLoader().
OMX_ERRORTYPE(* BOSA_COMPONENTLOADER::BOSA_DeInitComponentLoader)(struct BOSA_COMPONENTLOADER *loader)
The destructor of the component loader.
The component loader destructor is called by the OMX_Deinit function. It is implemented by the specific component loader. It must free every specific resource used by the component loader.
Parameters
loader the specific component loader. This parameter is also specific to the component loader, and its structure is defined by each loader.
Returns
OMX_ErrorNone
Definition at line 65 of file component_loader.h.
Referenced by OMX_Deinit(), and st_static_InitComponentLoader().
OMX_ERRORTYPE(* BOSA_COMPONENTLOADER::BOSA_DestroyComponent)(struct BOSA_COMPONENTLOADER *loader, OMX_HANDLETYPE hComponent)
The component destructor of the current component loader.
This function implements the OMX_FreeHandle function for the specific component loader. Its interface is the same as the standard FreeHandle function, except that the first parameter that contains the private data of the specific component loader.
Parameters
loader Private data of the component loader
pHandle the openmax handle returned by the function, or NULL in case of failure.
cComponentName A string that contains the standard component's name
pAppData private data of the component (if needed)
pCallBacks IL client callback function pointers passed to the component
Returns
OMX_ErrorNone if the component is correctly constructed and returned
OMX_ErrorComponentNotFound if the component is not found
OMX_ErrorInsufficientResources if the component exists but can not be allocated.
Definition at line 114 of file component_loader.h.
Referenced by OMX_FreeHandle(), and st_static_InitComponentLoader().
OMX_ERRORTYPE(* BOSA_COMPONENTLOADER::BOSA_GetComponentsOfRole)(struct BOSA_COMPONENTLOADER *loader, OMX_STRING role, OMX_U32 *pNumComps, OMX_U8 **compNames)
This function implements the OMX_GetComponentsOfRole standard function for the current component loader.
This function will return the number of components that support the given role and (if the compNames field is non-NULL) the names of those components. The call will fail if an insufficiently sized array of names is supplied. To ensure the array is sufficiently sized the client should:
first call this function with the compNames field NULL to determine the number of component names
second call this function with the compNames field pointing to an array of names allocated according to the number returned by the first call.
Parameters
loader Private data of the component loader
role This is generic standard component name consisting only of component class name and the type within that class (e.g. 'audio_decoder.aac').
pNumComps This is used both as input and output. If compNames is NULL, the input is ignored and the output specifies how many components support the given role. If compNames is not NULL, on input it bounds the size of the input structure and on output, it specifies the number of components string names listed within the compNames parameter.
compNames If NULL this field is ignored. If non-NULL this points to an array of 128-byte strings which accepts a list of the names of all physical components that implement the specified standard component name. Each name is NULL terminated. numComps indicates the number of names.
Definition at line 211 of file component_loader.h.
Referenced by OMX_GetComponentsOfRole(), and st_static_InitComponentLoader().
OMX_ERRORTYPE(* BOSA_COMPONENTLOADER::BOSA_GetRolesOfComponent)(struct BOSA_COMPONENTLOADER *loader, OMX_STRING compName, OMX_U32 *pNumRoles, OMX_U8 **roles)
This function implements the OMX_GetRolesOfComponent standard function for the current component loader.
This function will return the number of roles supported by the given component and (if the roles field is non-NULL) the names of those roles. The call will fail if an insufficiently sized array of names is supplied. To ensure the array is sufficiently sized the client should:
first call this function with the roles field NULL to determine the number of role names
second call this function with the roles field pointing to an array of names allocated according to the number returned by the first call.
Parameters
loader Private data of the component loader
compName The name of the component being queried about.
pNumRoles This parameter is used both as input and output. If roles is NULL, the input is ignored and the output specifies how many roles the component supports. If compNames is not NULL, on input it bounds the size of the input structure and on output, it specifies the number of roles string names listed within the roles parameter.
roles If NULL this field is ignored. If non-NULL this points to an array of 128-byte strings which accepts a list of the names of all standard components roles implemented on the specified component name. numComps indicates the number of names.
Definition at line 176 of file component_loader.h.
Referenced by OMX_GetRolesOfComponent(), and st_static_InitComponentLoader().
OMX_ERRORTYPE(* BOSA_COMPONENTLOADER::BOSA_InitComponentLoader)(struct BOSA_COMPONENTLOADER *loader)
The constructor of the component loader.
The component loader creator is called by the OMX_Init function. It is implemented by the specific component loader. It must allocate any resource needed by the component loader.
Parameters
loader A private data structure, if needed by the component loader. This data structure is passed every time a function of this loader is called.
Returns
OMX_ErrorInsufficientResources if the component loader can not be constructed
Definition at line 53 of file component_loader.h.
Referenced by OMX_Init(), and st_static_InitComponentLoader().
void* BOSA_COMPONENTLOADER::loaderPrivate
The reference to the current component loader private data.
The current loader specified by this structure is described with this generic pointer that contains the private data of the loader.
Definition at line 222 of file component_loader.h.
Referenced by BOSA_ST_ComponentNameEnum(), BOSA_ST_CreateComponent(), BOSA_ST_DeInitComponentLoader(), BOSA_ST_GetComponentsOfRole(), BOSA_ST_GetRolesOfComponent(), and BOSA_ST_InitComponentLoader().
The documentation for this struct was generated from the following file:
component_loader.h
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1