OpenMAXBellagio: djpeg_dest_struct Struct Reference
djpeg_dest_struct Struct Reference
#include <cdjpeg.h>
Data Fields
void(* start_output)(j_decompress_ptr cinfo, djpeg_dest_ptr dinfo)
void(* put_pixel_rows)(j_decompress_ptr cinfo, djpeg_dest_ptr dinfo, JDIMENSION rows_supplied)
void(* finish_output)(j_decompress_ptr cinfo, djpeg_dest_ptr dinfo)
FILE * output_file
JSAMPARRAY buffer
JDIMENSION buffer_height
Detailed Description
Definition at line 47 of file cdjpeg.h.
Field Documentation
JSAMPARRAY djpeg_dest_struct::buffer
Definition at line 68 of file cdjpeg.h.
Referenced by jinit_write_bmp(), jinit_write_gif(), jinit_write_ppm(), jinit_write_targa(), and main().
JDIMENSION djpeg_dest_struct::buffer_height
Definition at line 69 of file cdjpeg.h.
Referenced by jinit_write_bmp(), jinit_write_gif(), jinit_write_ppm(), jinit_write_targa(), and main().
void(* djpeg_dest_struct::finish_output)(j_decompress_ptr cinfo, djpeg_dest_ptr dinfo)
Definition at line 59 of file cdjpeg.h.
Referenced by jinit_write_bmp(), jinit_write_gif(), jinit_write_ppm(), jinit_write_targa(), and main().
FILE* djpeg_dest_struct::output_file
Definition at line 62 of file cdjpeg.h.
Referenced by main().
void(* djpeg_dest_struct::put_pixel_rows)(j_decompress_ptr cinfo, djpeg_dest_ptr dinfo, JDIMENSION rows_supplied)
Definition at line 56 of file cdjpeg.h.
Referenced by jinit_write_bmp(), jinit_write_gif(), jinit_write_ppm(), and main().
void(* djpeg_dest_struct::start_output)(j_decompress_ptr cinfo, djpeg_dest_ptr dinfo)
Definition at line 52 of file cdjpeg.h.
Referenced by jinit_write_bmp(), jinit_write_gif(), jinit_write_ppm(), jinit_write_targa(), and main().
The documentation for this struct was generated from the following file:
cdjpeg.h
Generated for OpenMAX Bellagio rel. 0.9.1 by 1.5.1